### ISSUE TITLE
Add a conda-forge as a test during pre-tag testing

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#1008]
During the next release (0.42.0) -- run the pre-tag test (testing the commit that would be tagged as a release) through conda-forge.

See also: https://github.com/numba/numba/wiki/Minutes_2023_10_24#0-discussion

**Comment by sklam** [comment]
Bumping this to 0.43.0 milestone. @gmarkall did https://github.com/conda-forge/llvmlite-feedstock/pull/79 for 0.42.0rc1.

**Comment by esc** [comment]
Bumping to 0.44 -- for 0.43.0rc1 it was: https://github.com/conda-forge/llvmlite-feedstock/pull/85
