### ISSUE TITLE
Use Alias Analysis for pruning NRT-related refct calls

### ISSUE THREAD

**Issue by dlee992** [numba/llvmlite#1026]
After manually checking some LLVM IR emitted from Numba, perhaps some pairs of `NRT_incref` & `NRT_decref` can be pruned in theory, but since we don't have any alias analysis in the RefPrunePass, we couldn't do it right now. 

LLVM has mature alias analysis passes to use, e.g. https://llvm.org/docs/AliasAnalysis.html.

I only have the instinct that there exist some possibilities to make the RefPrune result better. Will provide a showcase when I notice it in IR.

**Comment by sklam** [comment]
It may require the use of typed-based AA by encoding numba's type for all pointer load/store to get the benefit.

**Comment by dlee992** [comment]
Thanks for the link! Will look into it. So it seems we have big obstacles to enable TBAA.

Maybe close this for now?

**Comment by dlee992** [comment]
close it for now. Guess it won't be done in a near future.

**Comment by dlee992** [comment]
Although I closed this, just fyi for the future: Julia has already impl-ed TBAA: https://docs.julialang.org/en/v1/devdocs/llvm/#LLVM-Alias-Analysis. Perhaps can refer to its implementation.
