### ISSUE TITLE
Failed compilation with:  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)

### ISSUE THREAD

**Issue by acardona** [numba/llvmlite#107]
I am trying to compile llvmlite in Ubuntu 14.04 with:

$ LLVM_CONFIG=/usr/bin/llvm-config-3.5 pip install --upgrade llvmlite

... which pip states will bring it up to 0.7.0 (from 0.4.0, which compiled fine a while back, but NOTE it is also failing as of today).

Leads to the error:
Traceback (most recent call last):
  File "/home/albert/.virtualenvs/env/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/albert/.virtualenvs/env/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/home/albert/.virtualenvs/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)

I understand the issue is related to coding/decoding UTF (see e.g. https://stackoverflow.com/questions/24475393/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-23-ordinal , according to a similar issue found in docker: https://github.com/docker/compose/issues/1314 )

**Comment by seibert** [comment]
According to this issue, this error is fixed in pip 6.0 and later: https://github.com/pypa/pip/issues/1137

Also note that llvmlite 0.7.0 requires LLVM 3.6, not 3.5.  Because LLVM changes their API significantly between minor releases, we only support one LLVM release at a time in llvmlite.

**Comment by acardona** [comment]
Thank you, that fixed it.
