### ISSUE TITLE
The docs refer to setting LLVM_CONFIG to llvm-config path but mean the literal binary location.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/llvmlite#108]
If the LLVM installation is in a non-standard location (i.e. not on the path), then the `LLVM_CONFIG` variable needs setting prior to compilation. The variable is documented as  `first point the LLVM_CONFIG environment variable to the path of the corresponding llvm-config (or llvm-config.exe) executable.` In fact this variable must include the path to _and_ the binary name. For example, if LLVM is installed in `/opt/llvm/` with the `llvm-config` binary located at `/opt/llvm/bin/llvm-config` then set `LLVM_CONFIG=/opt/llvm/bin/llvm-config`. This variable must be persisted through into the installation of `llvmlite` into e.g. a python environment. The docs need to be updated to reflect this.

**Comment by stuartarchibald** [comment]
Patch in #109

**Comment by pitrou** [comment]
Now fixed by the aforementioned PR.
