### ISSUE TITLE
How do I use IdentifiedStructType?

### ISSUE THREAD

**Issue by scizzorz** [numba/llvmlite#111]
In the [release notes](http://llvmlite.pydata.org/en/latest/release-notes.html), it says IdentifiedStructType has been supported since v0.2, but I can't find any documentation on it and the [source code](https://github.com/numba/llvmlite/blob/a6c58beb5d5bc44ede0430d864d4a2b2951a7ee9/llvmlite/ir/types.py#L369) says not to use it directly.

**Comment by whitequark** [comment]
Use `context.get_identified_type("name")`, where `context` can be `llvmlite.ir.global_context` or a context you created.

**Comment by scizzorz** [comment]
Thanks!
