### ISSUE TITLE
llvmlite 0.9 on Linux should not depend on curses, if possible

### ISSUE THREAD

**Issue by seibert** [numba/llvmlite#118]
LLVM 3.7 appears to have added a dependency on curses:

LLVM 3.6.2:
```
(llvmdevtest)seibert@nvidia1:~$ llvm-config --system-libs
-lz -lpthread -lrt -ldl -lm
```

LLVM 3.7.1:
```
(llvmdevtest)seibert@nvidia1:~$ llvm-config --system-libs
-lrt -ldl -lcurses -lpthread -lz -lm
```

This has the side effect of making our binary packages for llvmlite less portable, as not all Linux systems have the same version of curses that our build servers do.  If there is a way to eliminate the dependency, we should do it.

Possible options include:
1. Filter out `-lcurses` from the list of libraries when linking llvmlite and see if things still work.  As we don't depend on all of LLVM, the part that requires curses might not be statically linked into our llvm bindings library.
2. See if there is a build option when building the LLVM 3.7 dev package that disables the curses requirement

(Note: This issue was reported on the mailing list: https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/numba-users/FoljfoseoDI/YML7M0iuDAAJ)

**Comment by seibert** [comment]
I guess option 1.5 is to statically link llvmlite to curses, but that seems like overkill.

**Comment by pitrou** [comment]
Changeset f1fbb5d5a38c434c299026b1b786e7f116e6808d should hopefully fix it. Let's now wait for the Jenkins builders.

**Comment by pitrou** [comment]
Ok, I think it is fixed:
```
>>> import llvmlite
>>> llvmlite.__file__
'/home/antoine/35/lib/python3.5/site-packages/llvmlite/__init__.py'
>>> !ldd /home/antoine/35/lib/python3.5/site-packages/llvmlite/binding/libllvmlite.so
	linux-vdso.so.1 =>  (0x00007ffdd49cf000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5efa6a3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5efa49f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5efa280000)
	libz.so.1 => /home/antoine/35/lib/python3.5/site-packages/llvmlite/binding/../../../../libz.so.1 (0x00007f5efa06a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5ef9d62000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5ef9b4a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5ef9780000)
	/lib64/ld-linux-x86-64.so.2 (0x000055b0dda29000)
>>> llvmlite.__version__
'0.9.0.dev+51.g167d8e4'
```

**Comment by MatthieuDartiailh** [comment]
Great !
