### ISSUE TITLE
Fail to install in Ubuntu 14.04 LTS with llvm 3.6.0

### ISSUE THREAD

**Issue by mvaled** [numba/llvmlite#119]
I try to build the package like this in a virtualenv:

```
$ LANG=en LLVM_CONFIG=/usr/bin/llvm-config-3.6 python setup.py build
```

I get the following error:

```
/home/manu/.virtualenvs/lv/local/lib/python2.7/site-packages/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '0.9.0.dev0+45.gd3f998b' instead of '0.9.0.dev+45.gd3f998b'.
  self.metadata.version,
running build
got version from VCS {'version': '0.9.0.dev+45.gd3f998b', 'full': 'd3f998b5dd09d7bdfa23ca5cf9519faacfb0065b'}
running build_ext
/home/manu/.virtualenvs/lv/bin/python ffi/build.py
LLVM version... 3.6.0
# static-libstdc++ avoids runtime dependencies on a
# particular libstdc++ version.
g++ -static-libstdc++ -shared -I/usr/lib/llvm-3.6/include -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -ffunction-sections -fdata-sections -Wcast-qual -fno-rtti -g -flto assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -L/usr/lib/llvm-3.6/lib -flto -Wl,--exclude-libs=ALL -lLLVMIRReader -lLLVMAsmParser -lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMipo -lLLVMVectorize -lLLVMInstrumentation -lLLVMBitWriter -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMCodeGen -lLLVMScalarOpts -lLLVMProfileData -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMTarget -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMMC -lLLVMCore -lLLVMSupport -lz -lpthread -lffi -ledit -ltinfo -ldl -lm -lLLVMOProfileJIT
targets.cpp:7:45: fatal error: llvm/Analysis/TargetLibraryInfo.h: No such file or directory
 #include "llvm/Analysis/TargetLibraryInfo.h"
                                             ^
compilation terminated.
make: *** [libllvmlite.so] Error 1
Traceback (most recent call last):
  File "ffi/build.py", line 147, in <module>
    main()
  File "ffi/build.py", line 137, in main
    main_posix('linux', '.so')
  File "ffi/build.py", line 129, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
error: command '/home/manu/.virtualenvs/lv/bin/python' failed with exit status 1
```

Packages installed:

- libllvm3.4 (required indirectly by xorg)
- libllvm3.6
- llvm-3.6
- llvm-3.6-dev
- llvm-3.6-runtime
- llvm-3.6-tools

I was read the issue #85, but seems unrelated.

**Comment by seibert** [comment]
The development version of llvmlite requires LLVM 3.7.  It is difficult for us to support different minor releases of LLVM because large API changes are made between those releases.  The last version of llvmlite to support LLVM 3.6 is 0.8.0.

I just noticed that this requirement was not mentioned in the README files, so I have added it.

**Comment by mvaled** [comment]
Do you keep a branch for 0.8.x... I was trying to fix the 'setup.py' since it requires enum34 installed beforehand.  My patch is in https://github.com/mvaled/llvmlite/commit/d3f998b5dd09d7bdfa23ca5cf9519faacfb0065b, but I could not test it completely because of this...

**Comment by seibert** [comment]
We have a git tag for 0.8.0, but haven't made a branch for it as we had not planned to do further releases of llvmlite for LLVM 3.6.  Perhaps we should reconsider that.

If you don't mind using conda, we have a binary package of LLVM 3.7.1 that we use for llvmlite development:
```
conda install -c numba llvmdev
```

**Comment by mvaled** [comment]
I will have to make a 0.8.1 myself since I need to have a package that is installable with buildout and pip... We haven't used `conda` (I didn't know about it since I read the 'numba' page).  We're just starting to explore both `numba` and its related technology, but we need it not to disrupt our build/deployment process.

**Comment by mvaled** [comment]
I created a 0.8-devel branch at https://github.com/mvaled/llvmlite/tree/0.8-devel and I could build and produce a 0.8.1 release from it.  Could you upload it to pypi?

**Comment by pitrou** [comment]
Why do you need a 0.8.1 release? We don't really want to maintain bugfix branches for llvmlite.
(note you'll only be able to uploade a source package to PyPI, which means you'll need to compile llvmlite on all boxes you deploy to)

**Comment by mvaled** [comment]
The 0.8.1 release would make our buildout download the .tar.gz and, yes, compile it... So it would provide a less painful way to install it in dev box, staging servers and finally (if all goes ok) in production.

Nevertheless, though with my self-built release 0.8.1 gets properly installed in a virtualenv with pip, buildout is not properly compiling the extension and the libllvmlite.so is not built.
