### ISSUE TITLE
python setup.py install should also run build

### ISSUE THREAD

**Issue by seibert** [numba/llvmlite#12]
I discovered on accident that "python setup.py install" doesn't also build the C wrapper.  This requires an explicit "python setup.py build" call first, which is documented in the README (as I found later).

However, I think other Python packages automatically run the build step when doing install (or at least detect if it needs to be run and do it).

**Comment by whitequark** [comment]
The install step calls the build step on current master.

**Comment by abebeos** [comment]
> The install step calls the build step on current master.

closable?

**Comment by esc** [comment]
@abebeos thanks for the ping, I verified this locally and with a correct `llvmdev` a call to `python setup.py install` does indeed compile and install. I was then also able to run the tests.
