### ISSUE TITLE
Linking to LLVMOProfileJIT

### ISSUE THREAD

**Issue by pwuertz** [numba/llvmlite#121]
Compiling the current llvmlite on Ubuntu 15.10 using the llvm 3.7 packages from the standard repository fails due to a hardcoded linkage to LLVMOProfileJIT. This library doesn't exist on the system. After removing the link from Makefile.linux llvmlite builds and runs without problems.

**Comment by mschubert** [comment]
same on Archlinux

**Comment by navreetaft** [comment]
Reported it @ https://lists.alioth.debian.org/pipermail/pkg-llvm-team/2016-March/005549.html

**Comment by pitrou** [comment]
Also see previous reports at https://github.com/numba/llvmlite/pull/100#issuecomment-172625079

**Comment by pitrou** [comment]
Also, upstream issue (explaining the hardcoded linkage) at https://llvm.org/bugs/show_bug.cgi?id=25091

**Comment by pwuertz** [comment]
Is there a possible workaround for determining if llvm is built with oprofile support or not?
@pitrou: Does oprofile show up in `llvm-config --components` for you?
Maybe enable the flag after checking for LLVMOProfileJIT files in `llvm-config --libdir`?

**Comment by pitrou** [comment]
Yes, `oprofilejit` shows up in `llvm-config --components`.

**Comment by pwuertz** [comment]
Maybe the problem is in `build.py` where only a subset of --libs is requested? Maybe a plain `llvm-config --libs` indeed includes LLVMOProfileJIT as it should (ignoring the extra gtest you reported)?

**Comment by pitrou** [comment]
Thanks for suggesting that. It seems that llvm-config doesn't have the bugs it used to have anymore, so perhaps we can use `--libs all` again. I'll take a look a bit later.
