### ISSUE TITLE
Build IR structures from LLVM assembly?

### ISSUE THREAD

**Issue by zendude** [numba/llvmlite#122]
Can llvmlite build real -- python-structured -- IR from an assembly or bitcode input?  I've tried parse_assembly, but the ModRef that returns seems to have only opaque string/bitcode representations of internals, not instructions, basic blocks, etc.

Am I missing the magic sauce that dis-assembles backwards to Python objects?

**Comment by pitrou** [comment]
No, it can't. Also, you should ask this kind of questions on the Numba mailing-list, rather than on the bug tracker. Thanks in advance :-)

**Comment by scizzorz** [comment]
Is this a feature idea that was rejected for some reason (eg too much work) or is it not possible to parse IR assembly back into a Python IR structure?

From my experience, it seems like the Python IR maps one-to-one, or fairly closely to, IR assembly, so it seems likely that someone *could* parse assembly/bitcode into a Python IR structure - it's just not a feature of `llvmlite`.

**Comment by pitrou** [comment]
> it seems likely that someone could parse assembly/bitcode back into a Python IR structure - it's just not a feature of llvmlite

Right, that may be possible - though we probably don't support all existing IR features. But simply, it's lot of work and it's not something we are interested in. However, since the llvmlite IR construction API is well-defined, this is something that you may implement as a third-party library.

**Comment by scizzorz** [comment]
That's what I figured. Thanks!
