### ISSUE TITLE
Debian package / build problems on some archs

### ISSUE THREAD

**Issue by danstender** [numba/llvmlite#124]
I've packaged llvmlite for Debian. Everything's all right but on the officially supported archs there a build problems on armel, armhf and powerpc, all have failures of `test_object_cache_getbuffer (llvmlite.tests.test_binding.TestMCJit)`. I don't have time right now to get deeper into it, do you would have a suggestion how to solve this or an idea what's going on? If you like, please see the buildlogs here: https://buildd.debian.org/status/package.php?p=llvmlite&suite=experimental
Thank you.

**Comment by pitrou** [comment]
Yes, it's possible you are seeing this. The problem is some targets may need `compiler-rt` to provide some library functions at runtime, but llvmlite currently doesn't link with `compiler-rt`. This will vary depending on the architecture and the exact LLVM version (even bugfix releases may solve such issues).

**Comment by pitrou** [comment]
Out of curiosity, which version of LLVM is this building against?

**Comment by danstender** [comment]
Currently, the default LLVM-toolchain is 3.6.

Thx for the info.

**Comment by pitrou** [comment]
3.6 exactly? On ARM you may have better luck with 3.6.2.

**Comment by danstender** [comment]
It is 3.6.2 available here. I could build against 3.7 but that's also work in progress, not
available for all archs so far, too. However, I'll try with that also.

If you would have any hints for manipulating the build chain, (dirty) patching etc. to get things
working, welcome ...

**Comment by pitrou** [comment]
LLVM 3.7 will require a newer llvmlite version (0.9.0 was just released). But there's no guarantee it will work better on ARM... Right now we only support x86 (and x86-64), as that's what our CI machines have.

> If you would have any hints for manipulating the build chain, (dirty) patching etc. to get things working, welcome ...

For Debian ? I have no idea, sorry. We provide our own binaries for use with the conda package manager... By the way, you may take a look at the `conda-recipes` directory to see the LLVM patches we're maintaining there.

**Comment by danstender** [comment]
I'll figure something out. Thx for hints.

**Comment by pitrou** [comment]
By the way, we'd like if you could keep us updated on your multi-architecture testing. Thank you!

**Comment by danstender** [comment]
Yes, I'll do that!

BTW Numba is coming up next! :-)

Cheers,
DS
