### ISSUE TITLE
Is it ok to build without oprofile support on Linux

### ISSUE THREAD

**Issue by cournape** [numba/llvmlite#129]
Hi there,

While updating our llvmlite packages for canopy, I saw that a link to oprofile was added. Is it ok to disable this if one does not intend to support oprofile, or does this reduces functionalities for llvmlite/numba ?

**Comment by pitrou** [comment]
Yes, it is ok to disable it. Also, please ask questions on the Numba mailing-list, rather than on the bug tracker. Thank you!
