### ISSUE TITLE
Allow easier creation of constants

### ISSUE THREAD

**Issue by pitrou** [numba/llvmlite#131]
Right now to e.g. increment an integer you have to:
```
c = ir.Constant(op.type, 1)
res = builder.add(op, c)
```
It would be easier to write:
```
res = builder.add(op, op.type(1))
```
... that is, allow creating a constant directly by calling a type instance with the intended value as argument.

**Comment by stuartarchibald** [comment]
Would also be nice to have equivalent of things like `size_t` and `ptrdiff_t` and others from `stddef.h`, and then also ints from `stdint.h`, as definitions.

**Comment by pitrou** [comment]
> Would also be nice to have equivalent of things like size_t and ptrdiff_t and others from stddef.h, and then also ints from stdint.h, as definitions.

This is more involved as it requires knowledge of the current ABI, and the IR layer by construction isn't informed of that.
