### ISSUE TITLE
Unnecessary use of static-libstdc++ ?

### ISSUE THREAD

**Issue by ian-bertolacci** [numba/llvmlite#133]
On some systems static-libstdc++ is not installed by default (Fedora 23 being an example).
This can be problematic for academic users who do not have permissions to install static-libstdc++ or those (such as myself) who do not want to build it from source and install locally.

I have sucessfully built and run llvmlite having removed the `-static-libstdc++` flag from [ffi/Makefile.linux](https://github.com/numba/llvmlite/blob/master/ffi/Makefile.linux#L18).

Is there a reason for using static-libstdc++?
I see the "avoids runtime dependencies on a particular libstdc++ version" note, but am not sure if that's a huge concern.

Maybe by default the `build` command should compile _without_  `-static-libstdc++`, and create a `build-with-static-stdc++` command that compiles _with_  `-static-libstdc++`

**Comment by pitrou** [comment]
> I see the "avoids runtime dependencies on a particular libstdc++ version" note, but am not sure if that's a huge concern.

Well, it is, because we distribute Linux binaries that work all the way from CentOS 5 up to the newest Linux distros. This is only possible by embedding libstdc++ statically, otherwise dynamic loading would fail.

> This can be problematic for academic users who do not have permissions to install static-libstdc++ or those (such as myself) who do not want to build it from source and install locally.

You mean Fedora doesn't even provide a package for it? Do you have any idea why?

**Comment by ian-bertolacci** [comment]
> Well, it is, because we distribute Linux binaries that work all the way from CentOS 5 up to the newest Linux distros. This is only possible by embedding libstdc++ statically, otherwise dynamic loading would fail.
Interesting. That sounds like the most annoying problem ever. Thanks for the enlightenment.

> You mean Fedora doesn't even provide a package for it? Do you have any idea why?
Fedora has a package, but it's not installed by default.
That's not a problem if you have root access, but that's rare in large academic settings and sys-admins sometimes dislike being told to install certain libraries.

**Comment by pitrou** [comment]
Note that for academic settings, we (Continuum) would recommend using the Anaconda distribution ;-)
(see https://www.continuum.io/downloads)

**Comment by ian-bertolacci** [comment]
Ok. 
I did have trouble using conda before (probably wasnt doing it right).

Thanks for the help!

**Comment by ian-bertolacci** [comment]
Huh. 
That worked quite well.
Something must be broken on my home machine (water wet, sky blue...)

Thanks again.
