### ISSUE TITLE
Error while trying to build llvmlite v 0.5.1

### ISSUE THREAD

**Issue by nisrine** [numba/llvmlite#143]
Hi I m trying to build the llvmlite v 0.5.1 but I get theis error 
any help thanks 
`nisrine@nisrine:~/llvmlite$ python3 setup.py build
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build
got version from VCS {'version': '0.5.1+0.g1adfa44.dirty', 'full': '1adfa44b60f8c2347d4b30050a92958290dc78c4.dirty'}
running build_ext
/usr/bin/python3 ffi/build.py
LLVM version... 3.5.0
static-libstdc++ avoids runtime dependencies on a
particular libstdc++ version.
g++ -static-libstdc++ -shared -flto `llvm-config --cxxflags` -fno-rtti assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -flto `llvm-config --ldflags` -Wl,--exclude-libs=ALL `llvm-config --system-libs --libs all`
/bin/sh: 1: llvm-config: not found
/bin/sh: 1: llvm-config: not found
/bin/sh: 1: llvm-config: not found
assembly.cpp:1:33: fatal error: llvm/IR/LLVMContext.h: No such file or directory
 #include "llvm/IR/LLVMContext.h"
                                 ^
compilation terminated.
bitcode.cpp:1:30: fatal error: llvm-c/BitReader.h: No such file or directory
 #include "llvm-c/BitReader.h"
                              ^
compilation terminated.
In file included from core.cpp:1:0:
core.h:4:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
initfini.cpp:1:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
module.cpp:2:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
value.cpp:2:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
In file included from executionengine.cpp:1:0:
core.h:4:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
In file included from transforms.cpp:1:0:
core.h:4:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
In file included from passmanagers.cpp:1:0:
core.h:4:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
In file included from targets.cpp:1:0:
core.h:4:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
In file included from dylib.cpp:1:0:
core.h:4:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
In file included from linker.cpp:1:0:
core.h:4:25: fatal error: llvm-c/Core.h: No such file or directory
 #include "llvm-c/Core.h"
                         ^
compilation terminated.
make: *** [libllvmlite.so] Error 1
Traceback (most recent call last):
  File "ffi/build.py", line 112, in <module>
    main()
  File "ffi/build.py", line 104, in main
    main_posix('linux', '.so')
  File "ffi/build.py", line 96, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
error: command '/usr/bin/python3' failed with exit status 1
`

**Comment by pitrou** [comment]
0.5.1 is very outdated, you should try the latest version 0.9.0.

**Comment by nisrine** [comment]
but is there any way to build it because I need the v 0.5.1

**Comment by pitrou** [comment]
Best I can suggest is to read the documentation. For the 0.5.1 documentation, you'll need to build it yourself using Sphinx.

**Comment by ian-bertolacci** [comment]
It looks like you don't have have LLVM installed, or you aren't pointing to `llvm-config` with the `LLVM_CONFIG` variable. (see http://llvmlite.pydata.org/en/latest/install/index.html#compiling)
