### ISSUE TITLE
LLVMOProfileJIT missing in default LLVM installation on Debian / Ubuntu

### ISSUE THREAD

**Issue by ml31415** [numba/llvmlite#145]
Trying to install any recent version of `llvmlite`, I run into the following error:
<pre>
    g++ -static-libstdc++ -shared -I/usr/lib/llvm-3.7/include -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -ffunction-sections -fdata-sections -Wcast-qual -fno-rtti -g -flto assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -L/usr/lib/llvm-3.7/lib -flto -Wl,--exclude-libs=ALL -lLLVMIRReader -lLLVMAsmParser -lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMipo -lLLVMVectorize -lLLVMBitWriter -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMCodeGen -lLLVMScalarOpts -lLLVMProfileData -lLLVMInstCombine -lLLVMInstrumentation -lLLVMTransformUtils -lLLVMipa -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMExecutionEngine -lLLVMTarget -lLLVMAnalysis -lLLVMRuntimeDyld -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMMC -lLLVMCore -lLLVMSupport -lz -lpthread -lffi -ledit -ltinfo -ldl -lm -lLLVMOProfileJIT
    /usr/bin/ld: cannot find -lLLVMOProfileJIT
</pre>

`libLLVMOProfileJIT.a` is no where to be found after a default installation of LLVM 3.7, neither in any previous version. Do I need a custom version, or is there something else going wrong?

**Comment by seibert** [comment]
This should be fixed on the master branch.  We should be doing another llvmlite release in the next few weeks or so, or you can install from Github.

**Comment by ml31415** [comment]
Ok, master works. Thanks!
