### ISSUE TITLE
Too aggressive except on importing ctypes lib

### ISSUE THREAD

**Issue by ml31415** [numba/llvmlite#147]
In `ffi.py`
```python
try:
    lib = ctypes.CDLL(os.path.join(_lib_dir, _lib_name))
except Exception:
    # Allow finding the llvmlite DLL in the current directory, for ease
    # of bundling with frozen applications.
    lib = ctypes.CDLL(_lib_name)
```
I'm not sure if this except statement here is a good idea. For me it first swallows a serious error, then retries to find the library in a path, where there is just nothing to find, as it's not installed there in the default install. E.g. errors like this are just covered up by a meaningless not found error:

<pre>
llvmlite/tests/test_binding.py:16: in <module>
    from llvmlite import binding as llvm
llvmlite/binding/__init__.py:6: in <module>
    from .dylib import *
llvmlite/binding/dylib.py:4: in <module>
    from . import ffi
llvmlite/binding/ffi.py:39: in <module>
    lib = ctypes.CDLL(os.path.join(_lib_dir, _lib_name))
/usr/lib/python2.7/ctypes/__init__.py:365: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: /home/nimrod/workspace/llvmlite/llvmlite/binding/libllvmlite.so: undefined symbol: _ZTINSt3_V214error_categoryE
</pre>

**Comment by pitrou** [comment]
What would you suggest? ctypes always raises `OSError`, and the only visible difference between the different causes of errors is the exception message...

**Comment by ml31415** [comment]
My suggestion would either be, to skip the second try completely and let the first error propagate directly, or to reraise the initial error. I didn't really get the sense of the except statement to be honest. For me it looks like: If something goes wrong with loading the library from it's proper location, have a look in system path. I just didn't see anything in the installer, where the library would ever end up in system path, which then renders the second attempt quite useless. Though, I saw that somewhen in former versions, there was no exception handling, so I figure you had your reasons to add it.

**Comment by pitrou** [comment]
As the comment mentions, this is for people who want to freeze their application using something like `cx_Freeze`, `py2exe`, etc.

Note that on Python 3, you'll get the full exception context and so the issue doesn't apply.

**Comment by ml31415** [comment]
Hm, analyzing the original error, if it's a simple not found, and continue only then? Ugly version fork for py2, to throw the original error if the second call also fails?

**Comment by pitrou** [comment]
I don't want to start parsing OS-specific error messages :-) Your second suggestion ("Ugly version fork for py2") sounds more reasonable to me.

**Comment by ml31415** [comment]
I'd be fine with both, as long as I get some clear error, even for poor PY2 users :-) If you don't mind, I'd give it a try with a fix then.
