### ISSUE TITLE
Can't build llvmlite, option --single-version-externally-managed not recognized

### ISSUE THREAD

**Issue by krey** [numba/llvmlite#166]
Hello thank you for fixing [https://github.com/numba/llvmlite/issues/150](https://github.com/numba/llvmlite/issues/150). I am trying to install llvmlite through pip and I get the following error:

```
Collecting git+git://github.com/numba/llvmlite
  Cloning git://github.com/numba/llvmlite to /tmp/pip-5yuixewg-build
Installing collected packages: llvmlite
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-5yuixewg-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0wmlan94-record/install-record.txt --single-version-externally-managed --compile:
    /home/krey/.local/lib/python3.5/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.11.0.dev+6.gc329287' to '0.11.0.dev0+6.gc329287'
      normalized_version,
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
```
I get the same error going through pip and pip+github. Could you please advise me on fixing this?

Thank you,

k

**Comment by seibert** [comment]
I'm not directly familiar with this bug, but some searching suggests that it might be caused by an old version of pip or setuptools.  Can you upgrade pip to the latest and try again?

**Comment by krey** [comment]
Hi, thanks for the speedy response. I upgraded all my packages, pip is 8.1.1, setuptools 20.7.0.

Getting the same error

**Comment by seibert** [comment]
Following a tip from Stackoverflow that I don't fully understand, this seems to work around the issue:
```
pip install --egg git+git://github.com/numba/llvmlite
```

**Comment by krey** [comment]
Oh dear

```
Collecting git+git://github.com/numba/llvmlite
  Cloning git://github.com/numba/llvmlite to /tmp/pip-dhfiqr6k-build
Installing collected packages: llvmlite
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-dhfiqr6k-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-k_0f2z3p-record/install-record.txt --compile --user --prefix=:
    /home/krey/.local/lib/python3.5/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.11.0.dev+6.gc329287' to '0.11.0.dev0+6.gc329287'
      normalized_version,
    running install
    running build
    got version from VCS {'version': '0.11.0.dev+6.gc329287', 'full': 'c3292876a5fb404205afee3febec3f3999417339'}
    running build_ext
    /usr/bin/python /tmp/pip-dhfiqr6k-build/ffi/build.py
    LLVM version... 3.5.2
    # static-libstdc++ avoids runtime dependencies on a
    # particular libstdc++ version.
    g++ -static-libstdc++ -shared -I/usr/include -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -ffunction-sections -fdata-sections -Wcast-qual -fno-rtti -g -flto assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -L/usr/lib -flto -Wl,--exclude-libs=ALL -lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMipo -lLLVMVectorize -lLLVMBitWriter -lLLVMIRReader -lLLVMAsmParser -lLLVMR600CodeGen -lLLVMR600Desc -lLLVMR600Info -lLLVMR600AsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMHexagonCodeGen -lLLVMHexagonAsmPrinter -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMTableGen -lLLVMDebugInfo -lLLVMOption -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMJIT -lLLVMLineEditor -lLLVMMCAnalysis -lLLVMMCDisassembler -lLLVMInstrumentation -lLLVMInterpreter -lLLVMCodeGen -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMProfileData -lLLVMMCJIT -lLLVMTarget -lLLVMRuntimeDyld -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMExecutionEngine -lLLVMMC -lLLVMCore -lLLVMSupport -lz -lpthread -lffi -lcurses -ldl -lm
    assembly.cpp: In function ‘LLVMOpaqueModule* LLVMPY_ParseAssembly(LLVMContextRef, const char*, const char**)’:
    assembly.cpp:25:64: error: ‘parseAssemblyString’ was not declared in this scope
         Module *m = parseAssemblyString(ir, error, *unwrap(context)).release();
                                                                    ^
    bitcode.cpp: In function ‘void LLVMPY_WriteBitcodeToString(LLVMModuleRef, const char**, size_t*)’:
    bitcode.cpp:13:62: error: ‘LLVMWriteBitcodeToMemoryBuffer’ was not declared in this scope
         LLVMMemoryBufferRef MB = LLVMWriteBitcodeToMemoryBuffer(M);
                                                                  ^
    core.cpp: In function ‘void LLVMPY_SetCommandLine(const char*, const char*)’:
    core.cpp:36:46: error: ‘LLVMParseCommandLineOptions’ was not declared in this scope
         LLVMParseCommandLineOptions(2, argv, NULL);
                                                  ^
    module.cpp: In function ‘LLVMOpaqueModule* LLVMPY_CloneModule(LLVMModuleRef)’:
    module.cpp:223:29: error: ‘LLVMCloneModule’ was not declared in this scope
         return LLVMCloneModule(M);
                                 ^
    executionengine.cpp: In function ‘LLVMOpaqueExecutionEngine* create_execution_engine(LLVMModuleRef, LLVMTargetMachineRef, char**)’:
    executionengine.cpp:72:74: error: no matching function for call to ‘llvm::EngineBuilder::EngineBuilder(std::unique_ptr<llvm::Module>)’
         llvm::EngineBuilder eb(std::unique_ptr<llvm::Module>(llvm::unwrap(M)));
                                                                              ^
    In file included from executionengine.cpp:6:0:
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:594:3: note: candidate: llvm::EngineBuilder::EngineBuilder(llvm::Module*)
       EngineBuilder(Module *m) : M(m) {
       ^
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:594:3: note:   no known conversion for argument 1 from ‘std::unique_ptr<llvm::Module>’ to ‘llvm::Module*’
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note: candidate: llvm::EngineBuilder::EngineBuilder(const llvm::EngineBuilder&)
     class EngineBuilder {
           ^
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note:   no known conversion for argument 1 from ‘std::unique_ptr<llvm::Module>’ to ‘const llvm::EngineBuilder&’
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note: candidate: llvm::EngineBuilder::EngineBuilder(llvm::EngineBuilder&&)
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note:   no known conversion for argument 1 from ‘std::unique_ptr<llvm::Module>’ to ‘llvm::EngineBuilder&&’
    executionengine.cpp: In function ‘uint64_t LLVMPY_GetGlobalValueAddress(LLVMExecutionEngineRef, const char*)’:
    executionengine.cpp:107:46: error: ‘LLVMGetGlobalValueAddress’ was not declared in this scope
         return LLVMGetGlobalValueAddress(EE, Name);
                                                  ^
    executionengine.cpp: In function ‘uint64_t LLVMPY_GetFunctionAddress(LLVMExecutionEngineRef, const char*)’:
    executionengine.cpp:114:43: error: ‘LLVMGetFunctionAddress’ was not declared in this scope
         return LLVMGetFunctionAddress(EE, Name);
                                               ^
    executionengine.cpp: At global scope:
    executionengine.cpp:187:45: error: ‘llvm::MemoryBufferRef’ has not been declared
                                           llvm::MemoryBufferRef MBR)
                                                 ^
    executionengine.cpp:200:49: error: conflicting return type specified for ‘virtual std::unique_ptr<llvm::MemoryBuffer> LLVMPYObjectCache::getObject(const llvm::Module*)’
         virtual std::unique_ptr<llvm::MemoryBuffer> getObject(const llvm::Module* M)
                                                     ^
    In file included from executionengine.cpp:8:0:
    /usr/include/llvm/ExecutionEngine/ObjectCache.h:36:25: error:   overriding ‘virtual llvm::MemoryBuffer* llvm::ObjectCache::getObject(const llvm::Module*)’
       virtual MemoryBuffer* getObject(const Module* M) = 0;
                             ^
    /usr/include/llvm/ExecutionEngine/ObjectCache.h:30:16: warning: ‘virtual void llvm::ObjectCache::notifyObjectCompiled(const llvm::Module*, const llvm::MemoryBuffer*)’ was hidden [-Woverloaded-virtual]
       virtual void notifyObjectCompiled(const Module *M, const MemoryBuffer *Obj) = 0;
                    ^
    executionengine.cpp:186:18: warning:   by ‘virtual void LLVMPYObjectCache::notifyObjectCompiled(const llvm::Module*, int)’ [-Woverloaded-virtual]
         virtual void notifyObjectCompiled(const llvm::Module *M,
                      ^
    executionengine.cpp: In member function ‘virtual void LLVMPYObjectCache::notifyObjectCompiled(const llvm::Module*, int)’:
    executionengine.cpp:191:42: error: request for member ‘getBufferStart’ in ‘MBR’, which is of non-class type ‘int’
                                          MBR.getBufferStart(),
                                              ^
    executionengine.cpp:192:42: error: request for member ‘getBufferSize’ in ‘MBR’, which is of non-class type ‘int’
                                          MBR.getBufferSize() };
                                              ^
    executionengine.cpp: In member function ‘virtual std::unique_ptr<llvm::MemoryBuffer> LLVMPYObjectCache::getObject(const llvm::Module*)’:
    executionengine.cpp:211:21: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<llvm::MemoryBuffer>’ and ‘llvm::MemoryBuffer*’)
                     res = llvm::MemoryBuffer::getMemBufferCopy(
                         ^
    In file included from /usr/include/c++/5.3.0/memory:81:0,
                     from /usr/include/llvm/ADT/SmallVector.h:28,
                     from /usr/include/llvm/IR/DataLayout.h:24,
                     from /usr/include/llvm/IR/Module.h:20,
                     from executionengine.cpp:5:
    /usr/include/c++/5.3.0/bits/unique_ptr.h:249:7: note: candidate: std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = llvm::MemoryBuffer; _Dp = std::default_delete<llvm::MemoryBuffer>]
           operator=(unique_ptr&& __u) noexcept
           ^
    /usr/include/c++/5.3.0/bits/unique_ptr.h:249:7: note:   no known conversion for argument 1 from ‘llvm::MemoryBuffer*’ to ‘std::unique_ptr<llvm::MemoryBuffer>&&’
    /usr/include/c++/5.3.0/bits/unique_ptr.h:269:2: note: candidate: template<class _Up, class _Ep> typename std::enable_if<std::__and_<std::is_convertible<typename std::unique_ptr<_Up, _Ep>::pointer, typename std::unique_ptr<_Tp, _Dp>::_Pointer::type>, std::__not_<std::is_array<_Up> > >::value, std::unique_ptr<_Tp, _Dp>&>::type std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Up = _Up; _Ep = _Ep; _Tp = llvm::MemoryBuffer; _Dp = std::default_delete<llvm::MemoryBuffer>]
      operator=(unique_ptr<_Up, _Ep>&& __u) noexcept
      ^
    /usr/include/c++/5.3.0/bits/unique_ptr.h:269:2: note:   template argument deduction/substitution failed:
    executionengine.cpp:211:21: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘llvm::MemoryBuffer*’
                     res = llvm::MemoryBuffer::getMemBufferCopy(
                         ^
    In file included from /usr/include/c++/5.3.0/memory:81:0,
                     from /usr/include/llvm/ADT/SmallVector.h:28,
                     from /usr/include/llvm/IR/DataLayout.h:24,
                     from /usr/include/llvm/IR/Module.h:20,
                     from executionengine.cpp:5:
    /usr/include/c++/5.3.0/bits/unique_ptr.h:278:7: note: candidate: std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::nullptr_t) [with _Tp = llvm::MemoryBuffer; _Dp = std::default_delete<llvm::MemoryBuffer>; std::nullptr_t = std::nullptr_t]
           operator=(nullptr_t) noexcept
           ^
    /usr/include/c++/5.3.0/bits/unique_ptr.h:278:7: note:   no known conversion for argument 1 from ‘llvm::MemoryBuffer*’ to ‘std::nullptr_t’
    executionengine.cpp: In function ‘LLVMPYObjectCache* LLVMPY_CreateObjectCache(ObjectCacheNotifyFunc, ObjectCacheGetObjectFunc, void*)’:
    executionengine.cpp:233:72: error: invalid new-expression of abstract class type ‘LLVMPYObjectCache’
         return new LLVMPYObjectCache(notify_func, getobject_func, user_data);
                                                                            ^
    executionengine.cpp:176:7: note:   because the following virtual functions are pure within ‘LLVMPYObjectCache’:
     class LLVMPYObjectCache : public llvm::ObjectCache {
           ^
    In file included from executionengine.cpp:8:0:
    /usr/include/llvm/ExecutionEngine/ObjectCache.h:30:16: note: 	virtual void llvm::ObjectCache::notifyObjectCompiled(const llvm::Module*, const llvm::MemoryBuffer*)
       virtual void notifyObjectCompiled(const Module *M, const MemoryBuffer *Obj) = 0;
                    ^
    targets.cpp:7:45: fatal error: llvm/Analysis/TargetLibraryInfo.h: No such file or directory
    compilation terminated.
    linker.cpp: In function ‘int LLVMPY_LinkModules(LLVMModuleRef, LLVMModuleRef, int, const char**)’:
    linker.cpp:19:32: error: ‘DiagnosticInfo’ does not name a type
         auto diagnose = [&] (const DiagnosticInfo &DI) {
                                    ^
    linker.cpp:30:6: error: expected ‘)’ before ‘;’ token
         };
          ^
    linker.cpp: In lambda function:
    linker.cpp:30:6: error: expected ‘{’ before ‘;’ token
    linker.cpp: In function ‘int LLVMPY_LinkModules(LLVMModuleRef, LLVMModuleRef, int, const char**)’:
    linker.cpp:32:34: error: ‘LLVMCloneModule’ was not declared in this scope
             Src = LLVMCloneModule(Src);
                                      ^
    linker.cpp:33:74: error: no matching function for call to ‘llvm::Linker::LinkModules(llvm::Module*, llvm::Module*, LLVMPY_LinkModules(LLVMModuleRef, LLVMModuleRef, int, const char**)::<lambda(int)>&)’
         bool failed = Linker::LinkModules(unwrap(Dest), unwrap(Src), diagnose);
                                                                              ^
    In file included from linker.cpp:4:0:
    /usr/include/llvm/Linker/Linker.h:51:17: note: candidate: static bool llvm::Linker::LinkModules(llvm::Module*, llvm::Module*, unsigned int, std::__cxx11::string*)
         static bool LinkModules(Module *Dest, Module *Src, unsigned Mode,
                     ^
    /usr/include/llvm/Linker/Linker.h:51:17: note:   candidate expects 4 arguments, 3 provided
    Makefile.linux:19: recipe for target 'libllvmlite.so' failed
    make: *** [libllvmlite.so] Error 1
    Traceback (most recent call last):
      File "/tmp/pip-dhfiqr6k-build/ffi/build.py", line 141, in <module>
        main()
      File "/tmp/pip-dhfiqr6k-build/ffi/build.py", line 131, in main
        main_posix('linux', '.so')
      File "/tmp/pip-dhfiqr6k-build/ffi/build.py", line 123, in main_posix
        subprocess.check_call(['make', '-f', makefile])
      File "/usr/lib/python3.5/subprocess.py", line 584, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
    error: command '/usr/bin/python' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-dhfiqr6k-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-k_0f2z3p-record/install-record.txt --compile --user --prefix=" failed with error code 1 in /tmp/pip-dhfiqr6k-build/
```

**Comment by seibert** [comment]
You have LLVM 3.5 installed, but llvmlite only supports LLVM 3.7.  (The LLVM developers typically break compatibility between each minor release.)  You will need the current version of LLVM installed before you can proceed.

(If you can use Miniconda to install pre-built llvmlite conda packages, I would highly recommend it.  Compiling LLVM is not fun.)

**Comment by krey** [comment]
Ah yes, my mistake, thank you

**Comment by kawing-chiu** [comment]
I still got the same error while using llvm3.7 on arch linux:
```
$ llvm-ar --version
LLVM (http://llvm.org/):
  LLVM version 3.7.1
  Optimized build.
  Built Jan 15 2016 (15:55:32).
  Default target: x86_64-unknown-linux-gnu
  Host CPU: broadwell
```
Have you made it to work using llvm3.7 @krey ??

**Comment by krey** [comment]
@kawing-chiu, I haven't had time to play with it, but I was able to install (and then import) llvmlite (and numba) with [the instructions seibert gave me](https://github.com/numba/llvmlite/issues/166#issuecomment-208087126) above.

**Comment by kawing-chiu** [comment]
Thanks @krey , I can install it with that option, although do not understand why. Instinct tells me that something might still be wrong, but not necessarily in llvmlite, might be in pip. It seems that some other packages also (used to) have (seemingly) the same problem [platformio issue](https://github.com/platformio/platformio/issues/279)

**Comment by untom** [comment]
Just to chime in: I have the exact same problem using LLVM 3.7 with Python3.5 with up-to-date pip and setuptools verisons. doing a

    pip install --egg git+git://github.com/numba/llvmlite

did not solve the problem for me:

    $ pip3 install --egg git+git://github.com/numba/llvmlite
    Collecting git+git://github.com/numba/llvmlite
      Cloning git://github.com/numba/llvmlite to /tmp/pip-9a11tcrv-build
    Installing collected packages: llvmlite
      Running setup.py install for llvmlite ... error
        Complete output from command /system/apps/biosoft/python-352/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-9a11tcrv-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gk4v18yi-record/install-record.txt --compile:
        /system/apps/biosoft/python-352/lib/python3.5/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.12.0.dev+8.g30bcfc0' to '0.12.0.dev0+8.g30bcfc0'
          normalized_version,
        running install
        running build
        got version from VCS {'version': '0.12.0.dev+8.g30bcfc0', 'full': '30bcfc080ac7d36926aa602e6c19593a9149b2fb'}
        running build_ext
        /system/apps/biosoft/python-352/bin/python3.5 /tmp/pip-9a11tcrv-build/ffi/build.py
        LLVM version... # static-libstdc++ avoids runtime dependencies on a
        # particular libstdc++ version.
        g++ -static-libstdc++ -shared -I/system/apps/biosoft/llvm-3.7.1/include -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -fPIC -ffunction-sections -fdata-sections -Wcast-qual -fno-rtti -g -flto assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -L/system/apps/biosoft/llvm-3.7.1/lib -flto -Wl,--exclude-libs=ALL -lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMBitWriter -lLLVMIRReader -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUUtils -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMMIRParser -lLLVMAsmParser -lLLVMLibDriver -lLLVMOption -lLLVMDebugInfoPDB -lLLVMTableGen -lLLVMOrcJIT -lLLVMLineEditor -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMDebugInfoDWARF -lLLVMOProfileJIT -lLLVMPasses -lLLVMipo -lLLVMVectorize -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMInstCombine -lLLVMInstrumentation -lLLVMTransformUtils -lLLVMipa -lLLVMMC -lLLVMAnalysis -lLLVMCore -lLLVMSupport -lz -lpthread -ltinfo -ldl -lm -lopagent -L/lib64/oprofile/lib/oprofile -Wl,-rpath,/lib64/oprofile/lib/oprofile
        /usr/bin/ld: cannot find -lopagent
        collect2: error: ld returned 1 exit status
        make: *** [libllvmlite.so] Error 1
        3.7.1
        
        Traceback (most recent call last):
          File "/tmp/pip-9a11tcrv-build/ffi/build.py", line 152, in <module>
            main()
          File "/tmp/pip-9a11tcrv-build/ffi/build.py", line 142, in main
            main_posix('linux', '.so')
          File "/tmp/pip-9a11tcrv-build/ffi/build.py", line 134, in main_posix
            subprocess.check_call(['make', '-f', makefile])
          File "/system/apps/biosoft/python-352/lib/python3.5/subprocess.py", line 581, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
        error: command '/system/apps/biosoft/python-352/bin/python3.5' failed with exit status 1
        
        ----------------------------------------
    Command "/system/apps/biosoft/python-352/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-9a11tcrv-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gk4v18yi-record/install-record.txt --compile" failed with error code 1 in /tmp/pip-9a11tcrv-build/

**Comment by untom** [comment]
Because the error message also mentioned that it's unable to find libopagent (which is weird, because that file is in the LD_LIBRARY_PATH), i manually added that path when calling pip and ran it again (in the directory where the llvmlite code lies):



    $ pip3 install --global-option=build_ext --no-binary :all: --global-option="-L/lib64/oprofile" .                    
    /system/apps/biosoft/python-352/lib/python3.5/site-packages/pip/commands/install.py:180: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
      cmdoptions.check_install_build_global(options)
    Processing /system/apps/biosoft/python-352/tmp/llvmlite-0.11.0
    Skipping bdist_wheel for llvmlite, due to binaries being disabled for it.
    Installing collected packages: llvmlite
      Running setup.py install for llvmlite ... error
        Complete output from command /system/apps/biosoft/python-352/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-b77dj652-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" build_ext -L/lib64/oprofile install --record /tmp/pip-_wfuazd4-record/install-record.txt --single-version-externally-managed --compile:
        usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: -c --help [cmd1 cmd2 ...]
           or: -c --help-commands
           or: -c cmd --help
        
        error: option --single-version-externally-managed not recognized
        
        ----------------------------------------
    Command "/system/apps/biosoft/python-352/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-b77dj652-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" build_ext -L/lib64/oprofile install --record /tmp/pip-_wfuazd4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-b77dj652-build/
