### ISSUE TITLE
Test `test_linux` failed, raising "AssertionError: unexpected dependency u'libtinfo'.".

### ISSUE THREAD

**Issue by tianzhi0549** [numba/llvmlite#183]
I have successfully compiled and installed `llvmlite`. But when I run `python runtests.py`, it raises  `AssertionError: unexpected dependency u'libtinfo' in set([u'libgcc_s', u'libm', u'libdl', u'libpthread', u'libc', u'ld-linux-x86-64', u'libz', u'libtinfo'])`. The corresponding code is https://github.com/numba/llvmlite/blob/master/llvmlite/tests/test_binding.py#L176.

Although the test cannot be passed, I still run my program successfully.

Does anyone know why it need ensure that any dependency must be in set `allowed` and how to fix it? 
Thank you:-).

**Comment by pitrou** [comment]
It may depend on the way you built LLVM. This is mostly a test of our own build procedure, so you may ignore the failure.

**Comment by pitrou** [comment]
Closing as it's not really a bug.

**Comment by tianzhi0549** [comment]
@pitrou Thanks. I installed LLVM-3.7.1 via apt-get on Ubuntu 14.04.
