### ISSUE TITLE
 Building llvmlite requires LLVM 3.7.x. (but I have LLVM 3.8 and set the LLVM_CONFIG variable)

### ISSUE THREAD

**Issue by Rhuax** [numba/llvmlite#187]
I'm trying to run : 
```python setup.py build```
in the llvmlite directory.

I get:
```
running build
got version from VCS {'version': '0.12.1', 'full': '0641dd9dde0d0653fbab109001baf39ddc08f466'}
running build_ext
/usr/bin/python /home/ubuntu/llvmlite/ffi/build.py
LLVM version... 3.8.1

Traceback (most recent call last):
  File "/home/ubuntu/llvmlite/ffi/build.py", line 152, in <module>
    main()
  File "/home/ubuntu/llvmlite/ffi/build.py", line 142, in main
    main_posix('linux', '.so')
  File "/home/ubuntu/llvmlite/ffi/build.py", line 119, in main_posix
    raise RuntimeError(msg)
RuntimeError: Building llvmlite requires LLVM 3.7.x. Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
```

my environment variable is : ```LLVM_CONFIG=/usr/bin/llvm-config-3.8``` . 
Other then the llvm-3.8 version I do not have any other version.. What can I do?

**Comment by pitrou** [comment]
Other than install LLVM 3.7? You can use our own llvmlite binaries (see documentation about that).
Closing as this isn't a bug.

**Comment by t47io** [comment]
Shouldn't llvm 0.12.1 require llvm 3.8.x, not 3.7.x?

**Comment by Rhuax** [comment]
Yes I agree. Maybe there are still some compatibility issues.. So one should downgrade llvm from 3.8.x to 3.7.x ..

**Comment by pitrou** [comment]
> Shouldn't llvmlite 0.12.1 require llvm 3.8.x, not 3.7.x?

Not sure what you mean by that. 0.12.1 requires LLVM 3.7, as the error message says. LLVM 3.8 is in master, but unreleased yet.

**Comment by t47io** [comment]
I meant that from the quoted README, `llvmlite >=0.12` (i.e. including 0.12.1) requires `LLVM 3.8`; while the error msg `RuntimeError: Building llvmlite requires LLVM 3.7.x.` is inconsistent with the documentation.

**Comment by t47io** [comment]
And `llvm 3.8.1` is released now and default by `brew`. (See http://llvm.org/ top-right corner). Thanks!!

**Comment by pitrou** [comment]
Oops, sorry. Yes, you're right, there is a mistake in the README.

**Comment by t47io** [comment]
Thanks, would the next version (supposably `0.13.x`?) supporting `LLVM 3.8.x`? Or it still gonna take a while?

**Comment by seibert** [comment]
The llvmlite master branch already supports LLVM 3.8 (but not LLVM 3.7 anymore), and we are planning to release llvmlite 0.13.0 near the end of August.

**Comment by senderle** [comment]
And... lo and behold, homebrew now installs llvm 3.9 by default. For OS X users trying to install llvmlite, this works. For now:

```
$ brew tap homebrew/versions
$ brew install llvm38
$ LLVM_CONFIG=/usr/local/Cellar/llvm38/3.8.1/lib/llvm-3.8/bin/llvm-config pip install llvmlite
```

**Comment by kylemcdonald** [comment]
Now llvmlite is up to speed with llvm 3.9, the most recent steps for OS X are:

```
$ brew install llvm
$ LLVM_CONFIG=""/usr/local/Cellar/llvm/3.9.1/bin/llvm-config"
$ pip install llvmlite

**Comment by metorm** [comment]
@kylemcdonald 

I did what you said above, but pip is still trying to use the llvm install by the system. What can I do?
