### ISSUE TITLE
Python 2.7 enum34 dependancy

### ISSUE THREAD

**Issue by davidkallie** [numba/llvmlite#194]
Creating a port for FreeBSD, it was brought up to my attention that for python 2.7, enum34 seems to be a necessary dependency for installing llvmlite, not running post installation. It seems that llvmlite.__init__.py tries to `import enum`, however this is happening during the install. 

It seems that it should be mention that setup.py requires enum34 during the install. I mention this because in the ports system, `install_requires` tells us to use `RUN_DEPENDS` in the build system. In numba passing `RUN_DEPENDS` works as expected for the port I am working on. However for llvmlite, it complains that enum34 is missing for us to compile. It is necessary for us to use `BUILD_DEPENDS`, but it is misleading.

The conversation in question is at [PR 211346](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211346#add_comment) from Comment 11-13

Sorry for the semantics.

**Comment by pitrou** [comment]
Thanks for the report. Can you submit a PR for the required change?
