### ISSUE TITLE
get_host_cpu_features() crashes on some archs

### ISSUE THREAD

**Issue by danstender** [numba/llvmlite#224]
This is from Debian packaging, get_host_cpu_features() crashes on some ports like s390x, ppc64el etc. [1]:
```
>>> from llvmlite import binding as llvm
>>> llvm.get_host_cpu_features()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "llvmlite/binding/targets.py", line 61, in get_host_cpu_features
    outdict[feat[1:]] = flag_map[feat[0]]
IndexError: string index out of range
```
Do you have any pointers what's going wrong here? That's llvmlite 0.14.0 with LLVM 3.8.
Thanks,
DS

[1] <https://buildd.debian.org/status/package.php?p=llvmlite&suite=experimental>

**Comment by seibert** [comment]
This suggests that LLVM is returning host CPU features not prefixed by `+` or `-`.  Unfortunately, I don't think we have easy access to any of the failing platforms.  Is it possible to see what the output is from this program after llvmlite is installed:

```
from llvmlite.binding import ffi

with ffi.OutputString() as out:
    ffi.lib.LLVMPY_GetHostCPUFeatures(out)
    print(out)
```

**Comment by danstender** [comment]
Yes, sure, no problem.

E.g., on a s390x the result is this:
```
Python 2.7.13 (default, Dec 18 2016, 20:19:42) 
[GCC 6.2.1 20161215] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from llvmlite.binding import ffi
>>> with ffi.OutputString() as out:
...     ffi.lib.LLVMPY_GetHostCPUFeatures(out)
...     print(out)
... 
0
```

**Comment by danstender** [comment]
Seems so, returns nothing. Could be a regression from LLVM?

**Comment by seibert** [comment]
It may be that some targets don't have controllable CPU features.  We should handle the empty string case.

**Comment by danstender** [comment]
I've forwarded this to the LLVM team @ Debian. Some workaround would be great. If you need some more testing on theses archs please just let me know ...

**Comment by pitrou** [comment]
The output "0" (note: not the empty string) sounds rather like a bug or oddity.

**Comment by sklam** [comment]
I think the proper fix is to make LLVMPY_GetHostCPUFeatures propagate the return value from llvm::sys::getHostCPUFeatures to indicate whether it has failed to find CPU features.  Then, `get_host_cpu_features` should either return None or raise to indicate the failure.
