### ISSUE TITLE
Make documentation for older versions available on Read the Docs

### ISSUE THREAD

**Issue by lightcatcher** [numba/llvmlite#228]
It would be convenient if documentation for older versions was available on Read the Docs.
Is older documentation currently built or hosted anywhere?

**Comment by seibert** [comment]
This is a good idea.  I didn't realize that Read the Docs wasn't automatically doing this.

**Comment by seibert** [comment]
@pitrou has added versions 0.13, 0.14, and 0.15 to the Read the Docs versions list.

**Comment by lightcatcher** [comment]
Thanks! Is there any reason to not just host all versions that use the correct type of documentation? (I personally was looking for 0.12 docs, but 0.13 mostly works)

**Comment by seibert** [comment]
I think it was just to reduce the clutter in the version list (and the three clicks it takes to turn each version on :) ).  I've added back to 0.7.0.
