### ISSUE TITLE
Make docs automatically contain correct version

### ISSUE THREAD

**Issue by eamartin** [numba/llvmlite#230]
The HTML title on Read the Docs still says 0.13. I believe this is because of https://github.com/numba/llvmlite/blob/master/docs/source/conf.py#L61

From looking in ``setup.py``, it looks like the quick fix is to call ``versioneer.get_version()`` in ``conf.py`` instead of hardcoding a version number.

**Comment by esc** [comment]
<img width="381" alt="Screen Shot 2022-10-25 at 19 15 42" src="https://user-images.githubusercontent.com/41563/197839563-fb3bddd5-7454-42da-971c-ffad951991b3.png">

I will close this now, as I believe this has been long resolved as shown by the screenshot above. If this is not the case, please do re-open with more information, thank you!
