### ISSUE TITLE
Building llvmlite requires LLVM 3.9.x

### ISSUE THREAD

**Issue by demidovakatya** [numba/llvmlite#234]
```~/llvmlite   master  LLVM_CONFIG=/usr/local/Cellar/llvm@3.8/3.8.1/bin/llvm-config-3.8 python setup.py install```

I get this on mac and ubuntu (both have llvm-3.8 installed, llvm-3.9 is not available via apt neither via brew)
```
/usr/local/lib/python2.7/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '0.16.0.dev+17.ge2b69ed' to '0.16.0.dev0+17.ge2b69ed'
  normalized_version,
running install
running build
got version from VCS {'version': '0.16.0.dev+17.ge2b69ed', 'full': 'e2b69edc08f8f4245aac56de7cbf41b7850bbe95'}
running build_ext
/usr/local/opt/python/bin/python2.7 /Users/mac/llvmlite/ffi/build.py
LLVM version... 3.8.1

Traceback (most recent call last):
  File "/Users/mac/llvmlite/ffi/build.py", line 152, in <module>
    main()
  File "/Users/mac/llvmlite/ffi/build.py", line 146, in main
    main_posix('osx', '.dylib')
  File "/Users/mac/llvmlite/ffi/build.py", line 119, in main_posix
    raise RuntimeError(msg)
RuntimeError: Building llvmlite requires LLVM 3.9.x. Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1```

**Comment by mthmn20** [comment]
I'm also experiencing this issue, can't find an LLVM 3.9 package for ubuntu using <<apt-cache search llvm | grep "3.9">> (stuff comes up when you grep for "3.8")

**Comment by seibert** [comment]
Unfortunately, because LLVM makes backward incompatible changes with each minor release, llvmlite only supports one version of LLVM at a time.  llvmlite 0.15.0 (and Numba 0.30.1) should work with LLVM 3.8, or you will have to install LLVM 3.9 from source.

**Comment by sklam** [comment]
If you don't need to build llvmlite/llvm manually, you can get pre-built binaries through [conda](https://conda.io/miniconda.html).  We are also testing wheel packages for linux for the current llvmlite release.  We have it for py2.7 and py3.5 with `pip install -i https://pypi.anaconda.org/sklam/simple llvmlite`

**Comment by ericgtaylor** [comment]
conda option didn't work for me but I was able to download 3.9.0 from http://releases.llvm.org/download.html

I put it next to my other llvm versions for convenience and updated the LLVM_CONFIG, which worked!
`LLVM_CONFIG=/usr/local/Cellar/llvm@3.9.0/bin/llvm-config pip install llvmlite`

**Comment by liuhuiCNN** [comment]
> `LLVM_CONFIG=/usr/local/Cellar/llvm@3.9.0/bin/llvm-config pip install llvmlite`

it works for me, thanks a lot.
