### ISSUE TITLE
Failing to vectorize with llvmlite where LLVM is capable of vectorizing

### ISSUE THREAD

**Issue by eamartin** [numba/llvmlite#235]
I'm attempting to vectorize a simple float reduction with LLVM (v3.8) through llvmlite (v0.15).
The code does the same thing as the following:

 My test case is:
```python
import sys
import llvmlite.binding as llvm

def initialize_llvm(force=False):
    if not force and hasattr(initialize_llvm, 'done'):
        return

    llvm.initialize()
    llvm.initialize_native_target()
    llvm.initialize_native_asmprinter()
    llvm.check_jit_execution()
    initialize_llvm.done = True

mod_str = \
"""
target triple = "unknown-unknown-unknown"
target datalayout = ""

define float @"adder"(float* %"x__input")
{
entry:
  %"x" = bitcast float* %"x__input" to [1024 x float]*
  br label %"loop"
loop:
  %"loop_idx" = phi i32 [0, %"entry"], [%"next_loop_idx", %"loop"]
  %"Sum__old" = phi float [             0x0, %"entry"], [%"Sum", %"loop"]
  %"next_loop_idx" = add i32 %"loop_idx", 1
  %"x__addr_loop" = getelementptr [1024 x float], [1024 x float]* %"x", i32 0, i32 %"loop_idx"
  %"x__loop" = load float, float* %"x__addr_loop"
  %"mul" = fmul fast float 0x40091eb860000000, %"x__loop"
  %"Sum" = fadd fast float %"Sum__old", %"mul"
  %"another_iter" = icmp slt i32 %"next_loop_idx", 1024
  br i1 %"another_iter", label %"loop", label %"post_loop"
post_loop:
  ret float %"Sum"
}
"""

initialize_llvm()
mod = llvm.parse_assembly(mod_str)
mod.verify()

pmb = llvm.PassManagerBuilder()
pmb.opt = 3
pmb.loop_vectorize = True
pmb.slp_vectorize = True

fpm = llvm.FunctionPassManager(mod)
pmb.populate(fpm)

func = mod.get_function('adder')
fpm.initialize()
opt_found = fpm.run(func)
fpm.finalize()

sys.stderr.write('Optimized: %s\n' % opt_found)
print mod
```

This leads to not finding any optimizations. If I pipe the output of the program to ``opt -O3 -force-vector-width=4 -S``, then vectorized IR is generated. The IR isn't vectorized without the ``force-vector-width`` flag. Additionally, if I write the equivalent program in C program in ``test.c`` 
```
float adder(float *x) {
  float total = 0.0;
  for (int i = 0; i < 1024; i++) {
    total += 3.14f * x[i];
  }
  return total;
}
```
 then ``clang test.c -O3 -ffast-math -S -emit-llvm -o -`` gives vectorized IR.

This leads to a couple of questions:
(1) Why isn't llvmlite or ``opt`` giving vectorized IR? It seems to me that vectorizing IR requires knowledge of the target vector size, but this information isn't present in the ``FunctionPassManager`` based flow above.

(2) Is there any way to specify ``-force-vector-width`` with llvmlite? I tried inserting a ``llvm.set_option('llvm', '--force-vector-width=8')`` before creating the pass manager with no luck.

(3) Is there any way to get LLVM to dump more info about what's going on during optimization (particularly auto vectorization and loop unrolling)? A call to ``llvm.set_option('', '-debug-pass=Details')`` helps but gives no mention of loop-vectorize or anything about unrolling loops. The [LLVM autovec docs](http://llvm.org/docs/Vectorizers.html) mention the ``-Rpass=loop-vectorize`` option, but this appears to only work with ``clang`` (no luck with ``opt`` or llvmlite calling ``set_option``).

**Comment by eamartin** [comment]
From some grepping of llvmlite code, I realized my example is nearly identical to that in ``examples/sum.py``. I expect anything that can get IR (or machine code) to use vector instructions for the sum example will work for my problem.

**Comment by sklam** [comment]
There were a few things:

1)  Even though [LoopVectorizer is a FunctionPass](https://github.com/llvm-mirror/llvm/blob/master/lib/Transforms/Vectorize/LoopVectorize.cpp#L2099), somehow it needs a ModulePassManager to do the vectorization.
2) LLVM needs information about the target machine for autovectorization.  (see https://github.com/llvm-mirror/llvm/blob/master/lib/Transforms/Vectorize/LoopVectorize.cpp#L12)

So the following changes will make it work:

```python
# 1) need ModulePassManager
mpm = llvm.ModulePassManager()
# 2) need target info
target = llvm.Target.from_triple(llvm.get_process_triple())
tm = target.create_target_machine()
tm.add_analysis_passes(mpm)

pmb.populate(mpm)
opt_found = mpm.run(mod)
```

**Comment by eamartin** [comment]
Thanks @sklam . I figured the loop vectorizer needed to know something about the target (vector length), but didn't know that ``add_analysis_passes`` was the way to communicate the information.

I see way more optimization passes (from ``-debug-pass=Details``) when using the module pass manager than when using a single function pass manager. Any idea why? ``ModulePassManager`` creation leads to a call to ``LLVMCreatePassManager``, which seems to indicate llvmlite ``ModulePassManager``'s correspond to a more general PassManager within LLVM.

Is there any (easy) way to run different sets of optimizations on different functions? Particularly, I have a kernel and a function to benchmark the kernel. I'd like to fully optimize the kernel and not optimize the benchmarking harness (to avoid dead code elimination and other benchmarking pitfalls).

**Comment by sklam** [comment]
`ModulePassManager` in llvmlite maps to `PassManager` in llvm.  We find it clearer to state the scope of the pass in the name.   `ModulePassManager` is more general as it can modify the entire module. `FunctionPassManager` can only modify the function.   (See <http://llvmlite.readthedocs.io/en/latest/binding/passmanager.html#optimization-passes>).  For details, it's better to refer to LLVM documentation.  

You can try different pass combinations by manually adding them with the ``add_*`` method in <http://llvmlite.readthedocs.io/en/latest/binding/passmanager.html#llvmlite.binding.PassManager>.  However, not every pass is exposed here.  Using `opt` gives you the most control.
