### ISSUE TITLE
manylinux wheels

### ISSUE THREAD

**Issue by mdraw** [numba/llvmlite#237]
I don't how hard it would be or if it is possible at all, but it would be really helpful if llvmlite and numba were available as manylinux wheels.
Currently, installing those two modules outside of an Anaconda environment is really hard (if I'm not missing something) because of the constantly changing llvm version requirement.

**Comment by seibert** [comment]
It's on our short term todo list.  conda-build recently added the ability to make wheels at the same time as conda packages, so we will be investigating that.  We need to verify that our CI build workers meet the manylinux1 binary requirements.

**Comment by mdraw** [comment]
Sounds great! Thanks for the quick reply.

**Comment by sklam** [comment]
With https://github.com/numba/llvmlite/pull/222, I have manylinux1 wheels for testing for py2.7 and py3.5.  
Install with `pip install -i https://pypi.anaconda.org/sklam/simple llvmlite`

**Comment by mdraw** [comment]
I must have overlooked #222 when opening this issue. I just tested the wheels from https://pypi.anaconda.org/sklam/simple on my machine. Both the 2.7 one and the 3.5 one seem to work fine in clean virtualenvs with only those new wheels and numba 0.31.0 (+ dependencies) installed (I only tested numba-jitting a simple function each). Thanks!

**Comment by mdraw** [comment]
It's really nice to have official wheels for llvmlite now 👍
A little OT: Are platform wheels for numba also planned? I got a working `numba-0.32.0-cp36-cp36m-manylinux1_x86_64.whl` by running

    /opt/python/cp36-cp36m/bin/pip install -r  requirements.txt
    /opt/python/cp36-cp36m/bin/pip wheel . -w /io/wheelhouse
    auditwheel repair numba-0.32.0-cp36-cp36m-linux_x86_64.whl -w /io/wheelhouse/
inside the numba 0.32 source directory (using the docker image quay.io/pypa/manylinux1_x86_64).
