### ISSUE TITLE
[Question] How to get an IRBuilder object from a llvmlite.binding.value.ValueRef object

### ISSUE THREAD

**Issue by joxeankoret** [numba/llvmlite#260]
Hi,

I'm trying to use LLVMLite for a purpose that I'm not sure is supported right now. What I would like to do is the following:

 * Compile IR or (even better) load a byte-code file.
 * Get all the modules and all the functions in each module.
 * Get an IRBuilder like object so I can analyse all the basic blocks and each basic block's instruction.

What I really want to do is to write a source-to-source tool to convert from LLVM IR to my own totally different IR. I don't know if I'm asking the wrong question; perhaps there is another way to do so with LLVMLite?

Thanks in advance!

**Comment by sklam** [comment]
If you need to analyze existing LLVM IR/bitcode, llvmlite will not be enough.  Llvmlite is mainly designed for compiler that only need to emit LLVM IR and use the LLVM JIT.  There are insufficient facility to read and manipulate the LLVM IR created outside of llvmlite.

There's an alternative package https://github.com/revng/llvmcpy that is likely to suit your need.

**Comment by joxeankoret** [comment]
I have already used it, but it lacks many things + llvmlite looks better, but I understand. Thank you!
