### ISSUE TITLE
Still not building llvmlite dynamic library on 0.17.1

### ISSUE THREAD

**Issue by stephengroat** [numba/llvmlite#262]
using pip, still having issues not building the .so, .dylib, etc.

Please let me know what I can try to help debug

Logs from installing using pip (https://travis-ci.org/cea-sec/miasm/jobs/226220656#L513)
Logs from error (https://travis-ci.org/cea-sec/miasm/jobs/226220656#L1070)

have wheel builds been added to travis to confirm that they're working?

**Comment by sklam** [comment]
The previous workaround is to run `python setup.py build` before the wheel build.  Otherwise, the .so is not recognized by setuptools/distutils.   

Can you try the suggestion at https://github.com/numba/llvmlite/issues/258#issuecomment-293915508 ?

**Comment by stephengroat** [comment]
gotcha. thanks for the suggestion, the works.

sorry, i misunderstood the state of the wheel builds.
