### ISSUE TITLE
Is there any function like malloc_array in llvmpy?

### ISSUE THREAD

**Issue by choleraehyq** [numba/llvmlite#269]
I want to allocate heap memory using llvmlite, how can I do this? I haven't found any API like malloc or malloc_array.

**Comment by sklam** [comment]
LLVM has removed the explicit IR for doing that after v1.1.  The current way to do it is to declare a function named malloc with the right signature and call it.  See: http://lists.llvm.org/pipermail/llvm-dev/2015-December/093087.html

**Comment by choleraehyq** [comment]
Ok, that helps much.
