### ISSUE TITLE
Vectorize inner loop to SIMD width

### ISSUE THREAD

**Issue by maedoc** [numba/llvmlite#270]
From my comment on #211, 
```python
@numba.jit
def loop(a, b, c, out):
    rec_b = float32(b / 10.0)
    rec_c = float32(c * b / 42.0)
    for i in range(1000):
        for j in range(8):
            out[i, j] = a + i * rec_b + i * rec_c
```
vs
```c
void loop(float a, float b, float c, float *out)
{
  float rec_b = b / 10.0;
  float rec_c = c * b / 42.0;
  for (int i=0; i<1000; i++)
    for (int j=0; j<8; j++)
      out[i*8 + j] = a + i * rec_b + i * rec_c;
}
```
In the former, the optimized IR reported by Numba is using regular floats, while in the latter, the IR shows work done on `<8 x float>`s (using the `-march=core-avx2` flag).

If I may guess w/o reading Clang's code, it is noticing that the `j` loop matches AVX2 SIMD width here and emitting 8-wide floats.

In Clang 3.9 this require an explicit pragma, so I guess it's fairly fancy inference, and I'd be happy to have something explicit like `prange`, e.g. 
```python
for i in numba.prange(100):
    for j in numba.ilprange(8):
         out[i, j] = a + i * rec_b + i * rec_c
```
(instruction level parallelism) which could drop the for loop and use SIMD-width vector types.

**Comment by sklam** [comment]
I noticed that changing the innermost loop body to:

```python
out[i * 8 + j] = a + i * rec_b + i * rec_c
```

enables the same kind of vectorization seen in clang.  I think the numba codegen can be better in emitting the `out[i, j]`.  (Details: you will also need to force more typing by using `float32(a_variable)` due to the implicit casting in numba.)

The clang pragma corresponds to the llvm ir metadata describe in <http://llvm.org/docs/LangRef.html#llvm-loop>.  They can be emitted with llvmlite already

for example:
```python
theloopbr = bdr.cbranch(bdr.icmp_signed('<', bdr.load(j), EIGHT), bb_inner_body, bb_outer_incr)
theloopbr.set_metadata('llvm.loop', mod.add_metadata([]))
```

I think the enhancements can be done in numba unless explicit simd type is required.

**Comment by sklam** [comment]
For the 2d array case, numba is able to autovec the function as soon as it knows that `out.shape[0] == 8` is True.  Thus, the following autovec fine:

```python
@numba.jit
def loop(a, b, c, out):
    rec_b = float32(b / 10.0)
    rec_c = float32(c * b / 42.0)
    assert out.shape[0] == 8    # <---- creates an assumption about the shape
    for i in range(1000):
        for j in range(8):
            out[i, j] = a + i * rec_b + i * rec_c
```

Also note that 

```python

@njit
def loop(a, b, c, out):
    rec_b = float32(b / 10.0)
    rec_c = float32(c * b / 42.0)
    for i in range(1000):
        out[i] = a + i * rec_b + i * rec_c
```

autovec just fine as well.

@maedoc, can you explain what you want to achieve?

**Comment by maedoc** [comment]
Wow, lots of interesting details and tricks there! Thanks for looking into it and writing all that up.  I'll admit that the example is contrived, but the structure is similar to part of a differential equation code I work on. I can provide a real example, if it would be useful. I should be able to use any these techniques to achieve vectorization (in fact I'm generating code to JIT with Numba so it was just a problem to figure out what trick to use and then make sure my code generator uses the trick, such as the assertion). 

May I suggest writing some of these up on the documentation, since they are very much worthwhile speed ups? Maybe I can contribute that. 

Also, it would be a handy shortcut to have a decorator or method which checks that vectorization was achieved in a kernel, instead of having to read the assembly. What do you think?

**Comment by sklam** [comment]
I think we need to explore more on the ways llvm can autovec loops. I have just found that the most generic loop without any optimization based on the shape will autovec just fine:

```python

@njit
def loop(a, b, c, out):
    rec_b = float32(b / 10.0)
    rec_c = float32(c * b / 42.0)
    for i in range(out.shape[0]):
        for j in range(out.shape[1]):
            out[i, j] = a + i * rec_b + i * rec_c
```

But, what we don't know is the performance achieved by each technique.  We should run a benchmark of each technique and document their behavior.

**Comment by sklam** [comment]
I am closing this issue.  It is more of a numba performance discussion then a llvmlite issue.  Let's move our disscussion to the numba issue https://github.com/numba/numba/issues/2390.
