### ISSUE TITLE
docs: llvmlite.ir.IntType(bits) "bits" or "width"

### ISSUE THREAD

**Issue by electronwill** [numba/llvmlite#287]
https://llvmlite.readthedocs.io/en/latest/user-guide/ir/types.html#llvmlite.ir.IntType shows this:

class llvmlite.ir.IntType(bits)
The type of integers. The Python integer bits specifies the bitwidth of the integers having this type.
width
The width in bits.

Should it say "bits" instead of "width", or is it correct now?

@sklam

**Comment by sklam** [comment]
It is correct for the docs but the confusion is actually from the code.  The constructor takes `bits` and stores it into attributes `width`.  The doc is correctly reflecting that.

**Comment by sklam** [comment]
They are actually referring to the "bitwidth` of the integer.

**Comment by electronwill** [comment]
Understood. Thank you!
