### ISSUE TITLE
docs: Itanium exception handling ABI link

### ISSUE THREAD

**Issue by electronwill** [numba/llvmlite#288]
https://llvmlite.readthedocs.io/en/latest/user-guide/ir/ir-builder.html#llvmlite.ir.IRBuilder.landingpad

"Itanium exception handling ABI" links to https://mentorembedded.github.io/cxx-abi/abi-eh.html . This is a 404. Maybe it should be https://itanium-cxx-abi.github.io/cxx-abi/abi-eh.html ?

@sklam

**Comment by sklam** [comment]
Thanks for point it out.  The new link looks right.  It seems to be the "canonical location" now.

**Comment by electronwill** [comment]
Great! Fixed in https://github.com/numba/llvmlite/pull/289 .
