### ISSUE TITLE
llvm-config not recognized while installing

### ISSUE THREAD

**Issue by arranger1044** [numba/llvmlite#29]
I am trying to install under Ubuntu 14.04 with llvm-3.5 installed but after executing `python install setup.py` these are the errors that I get:

    running build_ext
    /usr/bin/python ffi/build.py
    # static-libstdc++ avoids runtime dependencies on a
    # particular libstdc++ version.
    g++ -static-libstdc++ -shared -flto `llvm-config --cxxflags` -fno-rtti assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -flto `llvm-config --ldflags` -Wl,--exclude-libs=ALL `llvm-config  --system-libs --libs all`
    executionengine.cpp: In function ‘LLVMOpaqueExecutionEngine*   create_execution_engine(LLVMModuleRef, LLVMTargetMachineRef, char**, bool)’:
    executionengine.cpp:68:33: error: ‘nullptr’ was not declared in this scope
     LLVMExecutionEngineRef ee = nullptr;
                                 ^
    linker.cpp:3:32: fatal error: llvm/Linker/Linker.h: No such file or directory
    #include "llvm/Linker/Linker.h"
                                ^
    compilation terminated.
    make: *** [libllvmlite.so] Error 1

I have set a symbolic link to my llvm-config-3.5 binary

**Comment by seibert** [comment]
The LLVM 3.5 shipped with Ubuntu 14.04 is not actually the final release of LLVM 3.5.  They took a development snapshot from 6 months before the final release.  (I have no idea why they did that.  Perhaps it was a dependency of some other package?)

If you want to compile llvmlite on Ubuntu 14.04, you'll need to compile the released version of LLVM 3.5 yourself, or find different LLVM packages to install.  I believe that Debian does have the correct version, but I'm not sure about the details.  (Ubuntu 14.10 also has the proper release of LLVM 3.5.)

**Comment by seibert** [comment]
It appears that LLVM also provides Ubuntu packages.  The LLVM 3.5 repository for Ubuntu 14.04 is listed on this page:

http://llvm.org/apt/

**Comment by arranger1044** [comment]
Thanks @seibert that was really tricky for me to spot. I added their repo and installed llvmlite (just had to install libedit as well).
