### ISSUE TITLE
llvmlite-0.16.0 + llvm-3.9.1 segfault when compiling a function call

### ISSUE THREAD

**Issue by jvesely** [numba/llvmlite#292]
LLVM segfaults when trying to get inlining cost:
#0  0x00007f01ac1c506d in llvm::StringMapImpl::FindKey(llvm::StringRef) const
    () from /usr/lib64/libLLVMSupport.so.39
#1  0x00007f01ac5a81cf in llvm::Module::getNamedMetadata(llvm::Twine const&) const () from /usr/lib64/libLLVMCore.so.39
#2  0x00007f01ac5a8671 in llvm::Module::getModuleFlagsMetadata() const ()
   from /usr/lib64/libLLVMCore.so.39
#3  0x00007f01ac5a86b6 in 
   from /usr/lib64/libLLVMCore.so.39
#4  0x00007f01ac5a881e in llvm::Module::getModuleFlag(llvm::StringRef) const ()
   from /usr/lib64/libLLVMCore.so.39
#5  0x00007f01ac5a9e75 in llvm::Module::getProfileSummary() ()
   from /usr/lib64/libLLVMCore.so.39
#6  0x00007f01acca4451 in llvm::ProfileSummaryInfo::computeSummary() ()
   from /usr/lib64/libLLVMAnalysis.so.39
#7  0x00007f01acca44c1 in llvm::ProfileSummaryInfo::isHotFunction(llvm::Function const*) () from /usr/lib64/libLLVMAnalysis.so.39
#8  0x00007f01acc1823b in ?? () from /usr/lib64/libLLVMAnalysis.so.39
#9  0x00007f01acc1bdfe in llvm::getInlineCost(llvm::CallSite, llvm::Function*, int, llvm::TargetTransformInfo&, llvm::AssumptionCacheTracker*, llvm::ProfileSummaryInfo*) () from /usr/lib64/libLLVMAnalysis.so.39
#10 0x00007f01acc1bfc9 in llvm::getInlineCost(llvm::CallSite, int, llvm::TargetTransformInfo&, llvm::AssumptionCacheTracker*, llvm::ProfileSummaryInfo*) ()
---Type <return> to continue, or q <return> to quit---
   /usr/lib64/libLLVMAnalysis.so.39
#11 0x00007f01aff84edb in ?? () from /usr/lib64/libLLVMipo.so.39
#12 0x00007f01aff855a1 in llvm::Inliner::shouldInline(llvm::CallSite) () from /usr/lib64/libLLVMipo.so.39
#13 0x00007f01aff8968c in llvm::Inliner::inlineCalls(llvm::CallGraphSCC&) () from /usr/lib64/libLLVMipo.so.39
#14 0x00007f01acbbd709 in ?? () from /usr/lib64/libLLVMAnalysis.so.39
#15 0x00007f01ac593c96 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/lib64/libLLVMCore.so.39
#16 0x00007f01ac529829 in LLVMRunPassManager () from /usr/lib64/libLLVMCore.so.39
#17 0x00007f01b674c38c in LLVMPY_RunPassManager () from /usr/lib64/python3.5/site-packages/llvmlite/binding/libllvmlite.so
#18 0x00007f01b9750ff0 in ffi_call_unix64 () from /usr/lib64/libffi.so.6

The function call is created using:
int32_ty = ir.IntType(32)
float_ty = ir.DoubleType()
double_ptr_ty = float_ty.as_pointer()

f = _module.get_global(name);
func_ty = ir.FunctionType(ir.VoidType(), (double_ptr_ty, double_ptr_ty, double_ptr_ty))
function = ir.Function(_module, func_ty, name='wrapper')

_x = ctx.int32_ty(x) # x is a python constant, dimension of the input matrix
_v, _m, _o = function.args
block = function.append_basic_block(name="entry")
builder = ir.IRBuilder(block)
builder.call(f, [_v, _m, _x, _x, _o])
builder.ret_void()

The generated IR looks OK. When printed I can pass ti to opt and llc without any problem.
It also works OK when f is marked with 'alwaysinline' attribute.
The same python code works OK with llvm-lite-0.19.0 and LLVM-4.0.1

**Comment by jvesely** [comment]
as much as python can be multi-threaded, so I guess not really.

**Comment by sklam** [comment]
So, if your program use llvmlite in different threads, it can cause race-condition.  Numba has this problem before.  We have to add locks around the entire compiler pipeline.

**Comment by jvesely** [comment]
sorry, I should have been more explicit. I don't use threads in the python code.
Did you mean adding locks in python invocation of llvmlite, or locks in the binding itself? if it's the latter, is there a commit that addressed this in llvmlite?

**Comment by sklam** [comment]
I meant the prior: adding locks around llvmlite usage if more than one thread is using LLVM.  But if your program is not multi-threaded, it can be something else.  It can be bugs resolved in llvmlite or LLVM if newer versions work.  I'd suggest upgrading to a newer version if possible.

**Comment by jvesely** [comment]
I haven't seen this problem for some time. Closing.
