### ISSUE TITLE
indexing array types

### ISSUE THREAD

**Issue by jvesely** [numba/llvmlite#298]
Hi,

I have a struct that includes an array. A simplified case looks like this:
```
float_ty = ir.DoubleType()
noise_ty = ir.ArrayType(float_ty, 10)
# rate, offset, noise
param_type = ir.LiteralStructType([float_ty, float_ty, noise_ty])
```
using constant indices works OK:
```
noise = builder.extract_value(params, (2, 1))
```
however when I try to use dynamic index (like in a loop):
```
index_ptr = builder.alloca(ir.IntType(32))
... # store something to index_ptr
index = builder.load(index_ptr)
noise = builder.extract_value(params, (2, index))
```
I hit a python error:
```
    def __getitem__(self, item):
>       if 0 <= item < self.size:
E       TypeError: '<=' not supported between instances of 'int' and 'LoadInstr'
```
The documentation for extract_value says that:
> If agg is of an array type, indices can be arbitrary values.

**Comment by sklam** [comment]
This looks like an error in the docs.  `builder.extract_value` should only take `int` or sequence of `int`s for indices.  To iterate the array, you should use `gep`.

**Comment by jvesely** [comment]
the problem is that I can't use `gep` with arrays eithe. the following code:
```
array_ty = ir.ArrayType(double, 3)
fnty = ir.FunctionType(double, (array_ty, double, double, double))
func = ir.Function(module, fnty, name="fpadd")

block = func.append_basic_block(name="entry")
builder = ir.IRBuilder(block)
arr, a, b, c = func.args
x = builder.gep(arr, [int_ty(2)])
y = builder.gep(arr, [int_ty(1)])
z = builder.gep(arr, [int_ty(0)])
```
leads to
```
AttributeError: 'ArrayType' object has no attribute 'pointee'
```
this is just a simplified example. real code might iterate over an array...

**Comment by alendit** [comment]
Old question, but: as @sklam said, you need an array pointer to use `gep`. `array_ty` is a literal array type, that's why you get the error. 

You can change `array_ty` to `ir.ArrayType(double, 3).as_pointer()` and pass a pointer to the array to the function. This is a better option anyways, since AFAIK there are platform specific size limits on the function parameters, with a pointer you're always on the safe side.

**Comment by jvesely** [comment]
thanks. feel free to close this issue when the docs update lands.
