### ISSUE TITLE
[pypi] mismatch between wheels versions and package metadata

### ISSUE THREAD

**Issue by bmcfee** [numba/llvmlite#302]
This is a minor issue, but the wheels on pypi for 0.20.0 cover 2.7, 3.5, and 3.6.  The package metadata says 2.7, 3.4, and 3.5 are supported, so at least one of these is inaccurate.

BTW: Congrats on getting the win wheels up! This will make a lot of things much easier!

**Comment by sklam** [comment]
Thanks for catching the mismatch.  I think we will need to fix this in the next release since pypi properly doesn't like changing the existing metadata.  I hope (and I don't think) it's causing any issue for pip user.
