### ISSUE TITLE
Fatal error while trying to build llvmlite on Ubuntu 14.04

### ISSUE THREAD

**Issue by Omer80** [numba/llvmlite#32]
I am trying to install llvmlite on my ssystem in order to install numba. I have got an error when I did `python setup.py build`, the first error that appear is 
`assembly.cpp:3:35: fatal error: llvm/AsmParser/Parser.h: No such file or directory #include "llvm/AsmParser/Parser.h"`

The question on Stackoverflow - http://askubuntu.com/q/576510/164311

**Comment by gmarkall** [comment]
Ubuntu 14.04 ships a pre-release version of LLVM 3.5, which has some headers in the wrong place.

You can use this apt repo to install the release version of LLVM 3.5: http://llvm.org/apt/

See also issues #30 and #27.

**Comment by Omer80** [comment]
I have installed the stable branch on http://llvm.org/apt/

I still get the same old fatal error - `assembly.cpp:3:35: fatal error: llvm/AsmParser/Parser.h: No such ile or directory  #include "llvm/AsmParser/Parser.h"
                                   ^
compilation terminated.`
the command `llvm-config --cxxflags` results in
`-I/usr/lib/llvm-3.4/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -Wcast-qual`

Do I need to add `-std=c++11` to the line mentioned in #27 ?

**Comment by seibert** [comment]
Based on the line "-I/usr/lib/llvm-3.4/include", you appear to have installed LLVM 3.4, which is not supported.

**Comment by Omer80** [comment]
Do I need to remove llvm3.3 and llvm3.4 before I install llvm3.5 from llvm.org/apt/ ?

The command ` dpkg --get-selections|grep llvm` results in
`libllvm3.3:amd64                install`
`libllvm3.4:amd64                install`
`libllvm3.4:i386                 install`
`libllvm3.5:amd64                install`
`llvm                        install`
`llvm-3.3                    install`
`llvm-3.3-dev                    install`
`llvm-3.3-runtime                install`
`llvm-3.4                    install`
`llvm-3.4-dev                    install`
`llvm-3.4-runtime                install`
`llvm-3.5                    install`
`llvm-3.5-dev                    install`
`llvm-3.5-runtime                install`
`llvm-runtime                    install`

**Comment by eliben** [comment]
@Omer80 see the approach described in http://eli.thegreenplace.net/2015/building-and-using-llvmlite-a-basic-example/ to avoid multiple-llvm-versions problems. It shows how to directly point the llvmlite build to the version of LLVM (which doesn't even have to be installed) you want to build with.

**Comment by pitrou** [comment]
I have updated the README to mention the existence of the LLVM_CONFIG variable. Closing as this isn't strictly speaking a bug.
