### ISSUE TITLE
Problem Installing llvmlite

### ISSUE THREAD

**Issue by xexuew** [numba/llvmlite#323]
Hi i have a problem installing librosa in my virtual env:
Error:

> Failed building wheel for llvmlite
> `Command "/home/i42tohej/neuralnetwork/ENV/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l5yu5m/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aVAJVc-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/i42tohej/neuralnetwork/ENV/include/site/python2.7/llvmlite" failed with error code 1 in /tmp/pip-build-l5yu5m/llvmlite/
> `

**Comment by janaal1** [comment]
Hi, this post may help you
https://github.com/librosa/librosa/issues/757
Have you solved the problem with a different solution?
