### ISSUE TITLE
Better detect and diagnose llvm-config

### ISSUE THREAD

**Issue by pitrou** [numba/llvmlite#33]
Some users seem to have trouble building and the messages are not always informative. The build script could detect whether llvm-config is found on the path, and has the right version ("llvm-config --version"). Also, some distros (e.g. Ubuntu) also provide "llvm-config-3.5", so we could try to fall back on that.

**Comment by eliben** [comment]
Another option is to tell the users to just directly point to their `llvm-config`. It should then handle the rest.

It's possible to build llvmlite with:

    $ LLVM_CONFIG=<path/to/llvm-config> python3.4 setup.py build

Without even installing LLVM - binary downloads for Ubuntu are available, and if you build LLVM from source this helps too.

Perhaps mentioning this in the documentation/README can help most users avoid problems.

**Comment by pitrou** [comment]
Yes, this would probably be good enough.
