### ISSUE TITLE
python 2.7 enum34 required for run, and build

### ISSUE THREAD

**Issue by ddkn** [numba/llvmlite#334]
Hello everyone,

For python  < v3.4+ builds, enum34 is required for build, and install. Is it possible to add '**setup_requires**' for enum34 for versions less that 3.4? 

For our package system, we need to set RUN_DEPENDS for packages to know to bring in py27-enum34. However, upon building enum34 is also required: relevant snippet:

>  File "setup.py", line 74, in run
    from llvmlite.utils import get_library_files
  File "llvmlite/__init__.py", line 6, in <module>
    raise ImportError("could not find the 'enum' module; please install "
ImportError: could not find the 'enum' module; please install it using e.g. 'p
ip install enum34'
*** Error code 

Any help would be greatly appreciated, as we are looking to update the llvmlite to 0.22 in ports.

See here: [FreeBSD bug 226463](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226463#c1)

**Comment by ixmatus** [comment]
I just ran into this issue too, it would be nice if `setup_requires` specified enum34 as a dependency.
