### ISSUE TITLE
Update PyPi Repository?

### ISSUE THREAD

**Issue by ben-albrecht** [numba/llvmlite#34]
Now that the ` error: option --single-version-externally-managed not recognized ` bug has been [patched](https://github.com/numba/llvmlite/commit/cdf6497dc6e37efe5e67ffd675513145d421a1e7), I think the version on PyPi should be updated, for the sake of all the projects that depend on llvmlite.

**Comment by david-zwicker** [comment]
An update of the code in the PyPi repository would be much appreciated to make the installation of the latest `numba` version painless. See related issue in numba: https://github.com/numba/numba/issues/1076#issuecomment-91367607

**Comment by pitrou** [comment]
@seibert

**Comment by pitrou** [comment]
The PyPI entry should be up-to-date now (as of v0.4.0).
