### ISSUE TITLE
Can't install llvmlite 0.23 on Windows 10

### ISSUE THREAD

**Issue by Prokhozhijj** [numba/llvmlite#345]
Environment:
Python version 3.6.5 64-bit
Visual Studio Build Tools 2017 and Visual Studion Community Edition 2017
MS Windows 10 Pro 64-bit
pip 10.0.1

C:\WINDOWS\system32>pip install llvmlite
Collecting llvmlite
  Using cached https://files.pythonhosted.org/packages/c6/0f/d33ec3d030d4de01ba251c7dcf1051cb9f558221d64421439a61b0d81020/llvmlite-0.23.0.tar.gz
Installing collected packages: llvmlite
  Running setup.py install for llvmlite ... error
    Complete output from command c:\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\WINDOWS\\TEMP\\pip-install-s3s5440i\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\WINDOWS\TEMP\pip-record-7qa755f4\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file C:\WINDOWS\TEMP\pip-install-s3s5440i\llvmlite\llvmlite/_version.py {'version': '0.23.0', 'full': 'a924507857937369bdeb795a0f2d0a85ee27a0c1'}
    running build_ext
    c:\python36\python.exe C:\WINDOWS\TEMP\pip-install-s3s5440i\llvmlite\ffi\build.py
    Trying generator 'Visual Studio 14 2015 Win64'
    Traceback (most recent call last):
      File "C:\WINDOWS\TEMP\pip-install-s3s5440i\llvmlite\ffi\build.py", line 143, in <module>
        main()
      File "C:\WINDOWS\TEMP\pip-install-s3s5440i\llvmlite\ffi\build.py", line 131, in main
        main_win32()
      File "C:\WINDOWS\TEMP\pip-install-s3s5440i\llvmlite\ffi\build.py", line 74, in main_win32
        generator = find_win32_generator()
      File "C:\WINDOWS\TEMP\pip-install-s3s5440i\llvmlite\ffi\build.py", line 62, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\WINDOWS\TEMP\pip-install-s3s5440i\llvmlite\ffi\build.py", line 27, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "c:\python36\lib\subprocess.py", line 286, in check_call
        retcode = call(*popenargs, **kwargs)
      File "c:\python36\lib\subprocess.py", line 267, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\python36\lib\subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "c:\python36\lib\subprocess.py", line 997, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'c:\\python36\\python.exe' failed with exit status 1

    ----------------------------------------
Command "c:\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\WINDOWS\\TEMP\\pip-install-s3s5440i\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\WINDOWS\TEMP\pip-record-7qa755f4\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\WINDOWS\TEMP\pip-install-s3s5440i\llvmlite\

**Comment by sarahmtynes** [comment]
Also broken for Mac OSx and Ubuntu

**Comment by stuartarchibald** [comment]
Thanks for the report. Please see: https://github.com/numba/numba/issues/2918#issuecomment-384142644

**Comment by sklam** [comment]
All the wheels are uploaded to PyPI now.
