### ISSUE TITLE
Print function on llvmlite

### ISSUE THREAD

**Issue by marcelogdeandrade** [numba/llvmlite#357]
Hello, 
I'm trying to create a compiler to my own language using llvmlite.
Maybe my issue is something trivial, but I couldn't find an answer anywhere. I tried looking into other llvmlite projects to find an answer, but I didn't solve my issue.

I'm trying to call a print function on a Value. On llvmlite docs there is nothing about a print function. I would like to know if there is some way to create a print function using llvmlite.

Thank you

**Comment by syegulalp** [comment]
I'm in the middle of using llvmlite to create my own toy language as well.

If you're trying to create a print function in your language, LLVM does not have a print function by itself. That's handled by whatever system calls are available for such things on the target operating system. For instance, you could link your resulting executable against the C standard library and use calls to `printf`.

**Comment by alendit** [comment]
@marcelogdeandrade You'd do something like [this](https://gist.github.com/alendit/defe3d518cd8f3f3e28cb46708d4c9d6).

See also [cgutils from numba](https://github.com/numba/numba/blob/c699ef8679316f40af8d0678219fa197522a741f/numba/cgutils.py#L975).

**Comment by marcelogdeandrade** [comment]
@alendit Your approach works! The only problem is that it only works with Strings defined at the time print is called when creating the IR. What I mean is that, I can't print an LLVM Instruction with it, at least I didn't find a way to do it.

Thanks anyways! It was really helpful

**Comment by alendit** [comment]
Hi Marcel,
you should be able to use any llvm value with the `printf` function, not only one defined at the compile time. The important thing is to store the value to the memory beforehand and pass a value containing a pointer to it (of type `char*`). This is exactly what is done with the value `c_str` in the example, just imagine that `c_str_val` comes from an instruction or something and not as a constant global.

**Comment by marcelogdeandrade** [comment]
@alendit And how should I encode or convert any value to and char*? For example: I have and Instruction or I'm loading a value containing an i32 or i8, if I store this value to the memory and load it on printf function, it isn't treated as a string. Should I convert this Value to an ArrayType before storing it?

Thanks for the help

**Comment by alendit** [comment]
Hi Marcel,
it's even easier with integer values: you just specify `%i` in your format string and append the value to the list of arguments. See the [updated gist](https://gist.github.com/alendit/defe3d518cd8f3f3e28cb46708d4c9d6#file-call_printf-py-L35). Since `printf` is declared with `var_arg` you call pass any number of arguments.

**Comment by marcelogdeandrade** [comment]
It worked!! Thank you very much for your help, I've been trying to do this for a long time

**Comment by alendit** [comment]
Glad to hear it!

Could you close the issue, if there are no more related problems?
