### ISSUE TITLE
Push 0.23.1 to PyPI

### ISSUE THREAD

**Issue by Jehops** [numba/llvmlite#359]
Hi,

I notice the latest release is not available on PyPI.  If this was an oversight and requires manual intervention, could it be done?  Apologies for the noise if I am missing something obvious.  I am not a Python developer.

Thank you.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think `0.23.1` is a no-op release as far as PyPI is concerned, no code changes were made, just some conda build recipe alterations, https://github.com/numba/llvmlite/blob/master/CHANGE_LOG#L1-L10. However, I expect one can still be pushed up @sklam ?

**Comment by seibert** [comment]
Is there a specific reason to push the version up, other than completeness?  There's no functional difference between 0.23.0 and 0.23.1, as @stuartarchibald mentions.

**Comment by Jehops** [comment]
There is not.  Our OS package, which I submitted an update for, pulls from PyPI.   I just noticed the version discrepancy and thought there might have been an oversight.  Please excuse the noise.

**Comment by seibert** [comment]
No worries.  Thanks for checking!
