### ISSUE TITLE
Wheel packages for python3.7

### ISSUE THREAD

**Issue by jvesely** [numba/llvmlite#376]
Python 3.7 was released in June[0]. However, pypi lists only python2.7, 3.5, and 3.6 wheel packages[1].
It'd be helpful if python3.7 wheel packages were available.

[0] https://www.python.org/downloads/release/python-370/
[1] https://pypi.org/project/llvmlite/#files

**Comment by seibert** [comment]
We should be posting wheel packages in a week or two.  Our wheel building environment hasn't been updated yet for Python 3.7.

**Comment by seibert** [comment]
Python 3.7 wheels are posted now.
