### ISSUE TITLE
Simple way to use non-native targets for code generation

### ISSUE THREAD

**Issue by eliben** [numba/llvmlite#38]
At this time, llvmlite only exports `LLVMPY_InitializeNativeTarget`. The code for linking in initialization of other targets is commented out in initfini.cpp because that would make the size of the build llvmlite .so bigger.

There should be a better/simpler way to add targets that doesn't require fudging with the source of llvmlite. In LLVM itself it's usually handled on the configuration/build level.

In other words, it would be nice to configure which targets to build while building llvmlite (as parameters to the build script). The usual LLVM way requires rebuilding LLVM with a different configuration, which may not be suitable for llvmlite, as llvmlite expects a built LLVM, which in its installed form frequently includes all targets.

In particular, this would be useful for generating code for GPU targets (NVPTX target, for example).

**Comment by pitrou** [comment]
It's true that our LLVM builds include only the native target (both for size and compilation times), but you can build llvmlite against a full LLVM without any downside, since the build system is careful to trim unused APIs. So it should be a matter of adding a build option and passing the info to llvm-config, I suppose.

**Comment by pitrou** [comment]
Ah, I suppose it also requires exposing additional initialization APIs. Patches welcome :-)

**Comment by pitrou** [comment]
Note we don't hit this in Numba since our CUDA backend uses NVidia's proprietary NVVM toolchain (based, ironically, on LLVM 3.2).

**Comment by eliben** [comment]
AFAIU, which targets actually get linked into llvmlite gets decided by which `LLVMPY_Initialize_##` functions are implemented.

The built LLVM (typically) has all targets compiled into it. A user of LLVM controls which targets to actually use by referring to the symbol `LLVMInitialize<FOO>` somewhere in his code - this makes the linker bring the target into the actual executable (or .so in llvmlite's case).

If by default we'd like to keep llvmlite linked only with the native target, the build process will have to do a bit of code generation. So if I ask the build process to link NVPTX for me, it will have to generate this C code somewhere into llvmlite:

    void LLVMPY_InitializeNVPTX() { LLVMInitializeNVPTXTarget(); }

Along with the accompanying MC and Asm printer, etc.

Otherwise (if this is not conditioned in the build process), this will cause llvmlite to always link in the NVPTX backend, which probably isn't desired for Numba and other uses.

**Comment by pitrou** [comment]
Hmm, that's a good point. Some kind of code generation would probably be needed indeed.

**Comment by pitrou** [comment]
@eliben, would PR #152 fix this issue for you?

**Comment by eliben** [comment]
Yes, thanks for pointing it out
