### ISSUE TITLE
Query ir.Module for function or global

### ISSUE THREAD

**Issue by eliben** [numba/llvmlite#39]
LLVM's Module class has `getFunction()` and `getGlobalVariable()` for name lookup.

I was looking for something similar in `ir.Module` in llvmlite. I see the `globals` attribute, but I'm not sure whether it's officially part of the public API of the class. Would it be worthwhile to expose accessor methods? Or can I assume that any non `_` prepended attribute in ir classes is public?

**Comment by pitrou** [comment]
I think it's better to expose accessor methods. We might want to make those attribute privates :)

**Comment by eliben** [comment]
I'll see if I can come up with a simple patch
