### ISSUE TITLE
Module.global_variables unexpected behavior

### ISSUE THREAD

**Issue by eliben** [numba/llvmlite#41]
`ir.Module` has two accessors `functions` and `global_variables` that show non-symmetrical behavior. `functions` returns all functions in the module. But `global_variables` returns both functions and global variables. In LLVM's value hierarchy, a `Function` is not a `GlobalVariable` (both are `GlobalValue` though). So I'd expect `global_variables` to return only the variables (or be renamed to `global_values`)

**Comment by pitrou** [comment]
Ok, I think it's fine to rename it to `global_values`, then.
