### ISSUE TITLE
Extend LLVM IR

### ISSUE THREAD

**Issue by alinalihassan** [numba/llvmlite#425]
I was wondering if there's any interest in extending the LLVM IR, for things such as different Floating Point widths, Vector Type, etc. 

Knowing that llvmlite is used by many other people, some of us are limited by the API to generate the LLVM IR, and I know the project is used primarily for Numba, but with this repo having almost 600 starts, people are definitely using it and probably outside the scope that Numba uses it.

Would PRs to extend the code generation be welcome?

**Comment by seibert** [comment]
Yes, there are definitely users of llvmlite outside of Numba.  We've been accepting new features as long as they come with documentation and unit tests, and don't fundamentally change the way that llvmlite interacts with LLVM: C wrappers that can be compiled separately and statically linked to LLVM, or pure Python string generation for IR construction.

That said, there are two open PRs for vector types that we need to evaluate and decide how to combine.

**Comment by hassanalinali** [comment]
Good to know, I'm looking forward to make a PR for different Floating Point representation,[https://releases.llvm.org/6.0.0/docs/LangRef.html#floating-point-types](as shown in LLVM 6 documentation), but I'm still undecided for the python class names.
