### ISSUE TITLE
Build problem 

### ISSUE THREAD

**Issue by erogol** [numba/llvmlite#43]
as I run this command;

sudo LLVM_CONFIG=/usr/bin/llvm-config-3.5 python setup.py build

I get;
...
executionengine.cpp: In function ‘LLVMOpaqueExecutionEngine* create_execution_engine(LLVMModuleRef, LLVMTargetMachineRef, char**, bool)’:
executionengine.cpp:68:33: error: ‘nullptr’ was not declared in this scope
     LLVMExecutionEngineRef ee = nullptr;
                                 ^
linker.cpp:3:32: fatal error: llvm/Linker/Linker.h: No such file or directory
 #include "llvm/Linker/Linker.h"
...

I installed libedit as well but still the error persists

**Comment by seibert** [comment]
Is this Ubuntu 14.04?  The LLVM shipped with Ubuntu is not actually "LLVM 3.5", but a pre-release version from 5 months prior to the final release.  You can get packages from here: http://llvm.org/apt/

**Comment by erogol** [comment]
Yes 14.04 but what is this deb command in the given site.

**Comment by erogol** [comment]
After I follow "Install (qualification branch)" instructions still I get same error

sudo LLVM_CONFIG=/usr/bin/llvm-config-3.5 python setup.py build
 is the command I tried

**Comment by pitrou** [comment]
@erogol , /usr/bin/llvm-config-3.5 will be the standard Ubuntu llvm-config, not the third-party one.

**Comment by erogol** [comment]
so what should I write there

sudo LLVM_CONFIG=/usr/bin/llvm-config-3.5 python setup.py build

**Comment by pitrou** [comment]
Well, LLVM_CONFIG should point to wherever the installed llvm-config lies.
If you can't help yourself out of this I would suggest using conda to install a prebuilt llvmlite.

**Comment by pitrou** [comment]
Closing this, as it doesn't seem to be a llvmlite bug.
