### ISSUE TITLE
Identified Struct Types doesn't implement 'gep'

### ISSUE THREAD

**Issue by hassanalinali** [numba/llvmlite#442]
Currently Identified Struct types do not implement gep, and this results in them being basically unusable. I saw that there was another issue a long time ago #52 and it also followed with a merged pull request #58, I would like to know why or when the contribution got deleted, or if you need some help to fix the issue.

I would really love to help if that's the case since Identified Struct Types are unusable, you can't store or load anything. Please let me know your opinion on the issue.

**Comment by alendit** [comment]
Hi,

I do not understand the issue completely. The implementation of typing of gep was moved to `BaseStructType` in f388093, because it seems to be identical for all struct types.

The module you want seems to be created by the following code:
```python3
import llvmlite.ir as ir

int8 = ir.IntType(8)
int32 = ir.IntType(32)

ctx = ir.global_context
book_t = ctx.get_identified_type('struct.Book')
book_t.set_body(int8, int8, int8)

m = ir.Module()
f = ir.Function(m, ir.FunctionType(int32, []), 'main')
bldr = ir.IRBuilder(f.append_basic_block())

o = bldr.alloca(book_t)
book_ptr_0 = bldr.gep(o, [int32(0), int32(0)], inbounds=True)
bldr.store(int8(5), book_ptr_0, align=1)
book_ptr_1 = bldr.gep(o, [int32(0), int32(1)], inbounds=True)
bldr.store(int8(4), book_ptr_1, align=1)
bldr.ret(int32(0))

print(m)
```

```llvm
; ModuleID = ""
target triple = "unknown-unknown-unknown"
target datalayout = ""

%"Book" = type {i8, i8, i8}
%"struct.Book" = type {i8, i8, i8}
define i32 @"main"() 
{
.2:
  %".3" = alloca %"struct.Book"
  %".4" = getelementptr inbounds %"struct.Book", %"struct.Book"* %".3", i32 0, i32 0
  store i8 5, i8* %".4", align 1
  %".6" = getelementptr inbounds %"struct.Book", %"struct.Book"* %".3", i32 0, i32 1
  store i8 4, i8* %".6", align 1
  ret i32 0
}

```

Could you provide the code which leads to the error?

**Comment by hassanalinali** [comment]
That was my bad, I was passing a list as an argument for set_body (like `[field for field in struct_fields]`.

Now I'm expanding the list with `*` and it works fine, the issue can be closed.

**Comment by alendit** [comment]
:+1: would you closed it?
