### ISSUE TITLE
Explore building llvm with all targets enabled and masking in desired components/targets

### ISSUE THREAD

**Issue by stuartarchibald** [numba/llvmlite#462]
See https://github.com/conda-forge/llvmdev-feedstock/pull/59 for discussion/context.

**Comment by jvesely** [comment]
Hi, if I understood correctly https://github.com/conda-forge/llvmdev-feedstock/pull/59 only modified the conda build. Can we get multiple targets in pypi wheels as well?
Our project (https://github.com/PrincetonUniversity/PsyNeuLink) could benefit from generating CUDA kernels. So far this only works for me using the distro (Gentoo) provided llvmlite which is built against system llvm.

**Comment by jvesely** [comment]
ping @stuartarchibald , any thoughts on providing wheels with more targets?

**Comment by stuartarchibald** [comment]
@jvesely I think technically this is feasible. However, as I understand it, it is more of an infrastructure/configuration challenge with multiple host architectures on which to build non-host target LLVM, and also there are some open-ish questions e.g. where do the wheels go for non-x86 architectures? what tool chain is suitable for non-x86? does shipping a larger binary cause problems for users with restricted environments? how big are the llvm with debug symbol builds going to be? etc. The Numba release cycle for 0.43 has just finished, the 0.44 cycle is going to be deliberately short so I expect this chnage will be considered for 0.45 (and llvmlite 0.30) by which time LLVM version 8.x.x should be released and the llvmlite will be upgrading to that. I'll raise it at the next core developer meeting.

**Comment by seibert** [comment]
I think the main request here would not affect which platforms we ship wheels for (although that is a separate question), but which targets we turn on in the existing wheels we make.

I don't know that having the ARM target enabled on an x86 wheel would be particularly useful (you would need more toolchain parts to have a feasible cross-compiler), but turning on additional non-CPU targets, like the CUDA and AMDGPU targets would be useful for some projects, as mentioned above.  I see the main constraint to be package size, but we can investigate that during the numba 0.44/llvmlite 0.29 development cycle.

**Comment by jvesely** [comment]
Thanks! Yes, I was indeed thinking of including NVPTX and AMDGPU backends (SPIRV when it gets added to LLVM).
IIUC, the main downstream user (numba) could also use the two above-mentioned GPU backends.

**Comment by stuartarchibald** [comment]
Just doing the LLVM 8 upgrade patches. I've added NVPTX and AMDGPU targets along with host to all builds, will see what it does to binary size etc.

**Comment by jvesely** [comment]
> Just doing the LLVM 8 upgrade patches. I've added NVPTX and AMDGPU targets along with host to all builds, will see what it does to binary size etc.

thanks, if there's not enough space to fit both, NVPTX would be preferable. it should also be smaller.

**Comment by jvesely** [comment]
@stuartarchibald , I've verified that my CUDA code paths work with OTS llvmlite>=0.29. feel free to close this issue.

**Comment by seibert** [comment]
Great!
