### ISSUE TITLE
Missing sdist on PyPI for 0.27.1

### ISSUE THREAD

**Issue by jakirkham** [numba/llvmlite#463]
Appears the sdist for 0.27.1 is missing on PyPI. Could it please be uploaded? Thanks. :)

**Comment by seibert** [comment]
We can do that.  Just to check, is this because the lack of sdist is breaking some tooling?

**Comment by jakirkham** [comment]
We use the PyPI sdist to build the conda-forge packages of numba and llvmlite.

**Comment by erimar77** [comment]
We also use it to build numba and llvmlite packages for the Spack package manager.  An upload would be greatly appreciated!

**Comment by seibert** [comment]
Yes, in the future we will not try to use patch release versions to fix wheel build problems.  We have learned our lesson.  :)

**Comment by jakirkham** [comment]
FWIW we just went with 0.27.0 in conda-forge after your advice :)

**Comment by seibert** [comment]
Yes, if you have the ability to human-override things, that is the correct choice.  It is the automated tools that get most confused.

**Comment by sklam** [comment]
Uploaded sdist
