### ISSUE TITLE
Please update copyright year on docs

### ISSUE THREAD

**Issue by pfalcon** [numba/llvmlite#464]
Currently, http://llvmlite.pydata.org/en/latest/ shows:

> © Copyright 2015, Continuum Analytics Revision 9ee77188.

Which gives impression that it is yet another unmaintained LLVM bindings. Which is of course not true based on the git history.

**Comment by sklam** [comment]
The copyright year is to indicate the start of the copyright claim.  We are informed by our legal counsel that the copyright year do not need to be updated.    On the other hand, we can look into ways to make the last updated date more obvious.  One thought is to date all the releases in the release notes (which we should really have done all along).
