### ISSUE TITLE
No Python 3.5 Wheel on PyPI

### ISSUE THREAD

**Issue by TobyRoseman** [numba/llvmlite#471]
The latest version of [llvmlite on PyPI](https://pypi.org/project/llvmlite/0.27.1/) doesn't have any wheels for Python 3.5. This means if someone tries to install `llvmlite` in a Python 3.5 environment, it will fail unless they happen to also have `llvm-config` installed.

**Comment by jvesely** [comment]
It will also fail on almost all Ubuntu releases because they ship LLVM that wasn't built using the system default compiler (and passes incompatible flags).

**Comment by yzhao062** [comment]
This also happens to my library and an error log is attached: https://travis-ci.org/yzhao062/pyod/jobs/505039491

It was working with llvmlite 0.27.0 and stops working with llvmlite 0.27.1, although my library does not rely on llvmlite but numba only (numba>=0.35).

This only happens to python 3.5 (starting since around 10 hours ago). Thanks for fixing.

**Comment by sniperwrb** [comment]
Yes, it happened to me too since today morning.

I used Ubuntu 18.04 (which has python 3.6 easily available) and things went well.

**Comment by seibert** [comment]
We stopped making wheels for Python 3.5 some time ago, but it is clear we need to start again.  The next release of numba (0.43) and llvmlite (0.28) are in process now and will include Python 3.5 wheels.

**Comment by mdekstrand** [comment]
@seibert thank you. I see the releases are tagged, do you have an ETA on wheel uploads?

If it is helpful for future planning: in my project using Numba (https://github.com/lenskit/lkpy), our Python version support goal is to support the Python version in the last stable (LTS if applicable) release of each of the major distributions (Ubuntu, RHEL/CentOS + EPEL, Debian). Debian Stretch is at Python 3.5. A reasonably short time after Debian Buster is released, will will no longer be supporting Python 3.5 unless specifically requested.

**Comment by Juanlu001** [comment]
PSA: To protect your CI from breaking in these circumstances,

```
export PIP_PREFER_BINARY=true
```

(pip >= 18.0)

**Comment by yzhao062** [comment]
@Juanlu001 thanks for the note. Setting this env variable in CI tools takes care of the problem. Just by curiosity, is there any drawbacks of setting this to true? Tried to search online but did not find any documentation on this.

Thanks,

**Comment by Juanlu001** [comment]
The "drawback" is that you won't live on the bleeding edge and the the latest release, even if it doesn't have a wheel yet. But that is not a real disadvantage, because most people nowadays assume that Python packages come in a pre-compiled fashiion, or at most with some light requirements. I also came here when my CI started failing, so I guess many people is in the same situation. The reality is that I only care about the latest wheel :)

**Comment by seibert** [comment]
After going a couple rounds with wheels, we've evolved our procedure to always upload wheels before sdist.  Before we changed, we had more than one unlucky person install Numba during the time when we are releasing, and get stuck trying to compile Numba from scratch.  :)

**Comment by jvesely** [comment]
wheels for python 3.5 are available on pypi. should this be closed?
https://pypi.org/project/llvmlite/#files

**Comment by seibert** [comment]
Closing since Python 3.5 wheels for the latest release are now available.

**Comment by eric-wieser** [comment]
Note that this problem has resurfaced again, 0.32.0 has no Python 3.5 artifacts: https://pypi.org/project/llvmlite/0.32.0/#files

**Comment by esc** [comment]
@eric-wieser thanks for asking about this. I believe that Python 3.5 is no longer supported and hence there are now no wheels for it: https://github.com/numba/llvmlite/pull/551

**Comment by eric-wieser** [comment]
Not according to this line: https://github.com/numba/llvmlite/blob/26059d238f4ba23dff74703dd27168591d889edd/setup.py#L183

There's no `python_requires` either.

**Comment by eric-wieser** [comment]
Ah, it looks like the 3.5 classifier was an error in the 0.32.0 release that was caught in time for 0.32.1.

However, only `python_requires` is actually respected by pip.

**Comment by esc** [comment]
@eric-wieser thanks for catching this. We updated the README too here: https://github.com/numba/numba/blob/master/README.rst -- thanks for catching the missing `python_requires`!

**Comment by esc** [comment]
@eric-wieser I have created a PR to remedy this situation here: https://github.com/numba/llvmlite/pull/590 

Thanks again for your feedback, it is much appreciated.

**Comment by astrojuanlu** [comment]
The problem with forgetting `python_requires` is that even if you fix it in a future release, the old one stays on PyPI causing trouble. I've fell in this trap myself many times, and [reported it in other high profile projects](https://github.com/python/mypy/issues/7221) :( Hopefully with [PEP 592](https://www.python.org/dev/peps/pep-0592/)) this will be easier to control, but at the moment I think the only solution is to either accept the situation, or remove the release.

**Comment by eric-wieser** [comment]
> or remove the release.

I think a way to resolve this might be to use post-releases:

* Remove the 0.32.0 release, and create a 0.32.0.post1 release with the fix
* Remove the 0.32.1 release, and create a 0.32.1.post1 release with the fix
* ... etc

**Comment by Jack-Johns** [comment]
@astrojuanlu Hi, it just gives an error saying that there is no such option as --prefer-binary. Any suggestions?

**Comment by astrojuanlu** [comment]
@Jack-Johns upgrade pip :)

**Comment by Jack-Johns** [comment]
I've upgraded pip to 20.1.1 yet it still fails to find the llvm-config file...

**Comment by eric-wieser** [comment]
@Jack-Johns: Are you using `--prefer-binary` now that you upgraded pip?

**Comment by Jack-Johns** [comment]
@eric-wieser yep after upgrading I used the recommended command and it didn't work. Error log is as follows:

```
$ pip3 install llvmlite --prefer-binary
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting llvmlite
  Using cached llvmlite-0.32.1.tar.gz (104 kB)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ur4c79j5/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ur4c79j5/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8k6r2ti6
       cwd: /tmp/pip-install-ur4c79j5/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py", line 106, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 383, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
      raise child_exception_type(errno_num, err_msg)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py", line 192, in <module>
      main()
    File "/tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py", line 182, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py", line 109, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ur4c79j5/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ur4c79j5/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j5wkovf8/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/miro/.local/include/python3.5m/llvmlite
         cwd: /tmp/pip-install-ur4c79j5/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-ur4c79j5/llvmlite/llvmlite/_version.py {'full': 'aa11b129c0b55973067422397821ae6d44fa5e70', 'version': '0.32.1'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py", line 106, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 383, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py", line 192, in <module>
        main()
      File "/tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py", line 182, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-ur4c79j5/llvmlite/ffi/build.py", line 109, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ur4c79j5/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ur4c79j5/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j5wkovf8/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/miro/.local/include/python3.5m/llvmlite Check the logs for full command output.
```

**Comment by astrojuanlu** [comment]
I see a mention to `https://www.piwheels.org/simple`, so I suspect you are on a Raspberry Pi. Wheels of packages that are not pure Python are platform-dependent, please check out https://github.com/piwheels/packages/issues/33, which in turns depends on https://github.com/numba/llvmlite/issues/314.

You will need to install llvm with your system package manager _before_ trying to `pip install llvmlite`.
