### ISSUE TITLE
LLVM 8 support

### ISSUE THREAD

**Issue by baerbock** [numba/llvmlite#476]
How far is the LLVM 8 support?

**Comment by seibert** [comment]
We're just starting to look at it now that Numba 0.43.1 is out.  So far, it looks like we can drop some of our LLVM patches, but we need to evaluate whether the SVML patch still works, and whether we need to patch out the label length limit that has been plaguing us since we switch to LLVM 7.

**Comment by stuartarchibald** [comment]
See https://github.com/numba/llvmlite/pull/478

**Comment by stuartarchibald** [comment]
https://github.com/numba/llvmlite/pull/478 is merged.
