### ISSUE TITLE
I feel sorry for not having read that `enum34` is needed for ALL version of python < 3.4, meaning that it affects python2.X as well.

### ISSUE THREAD

**Issue by hmchaitra** [numba/llvmlite#479]
I feel sorry for not having read that `enum34` is needed for ALL version of python < 3.4, meaning that it affects python2.X as well.

_Originally posted by @arranger1044 in https://github.com/numba/llvmlite/issues/36#issuecomment-71459009_

**Comment by sklam** [comment]
https://github.com/numba/llvmlite/pull/483 should have fixed the dependency on enum34.
