### ISSUE TITLE
enum34 required when installing on python 3.6

### ISSUE THREAD

**Issue by Korijn** [numba/llvmlite#482]
llvmlite==0.28.0 requires enum34 even when installing on python 3.6. this breaks python environments.

**Comment by esc** [comment]
@Korijn thanks for using llvmlite and raising this issue. The offending line seems to be:

https://github.com/numba/llvmlite/blob/master/setup.py#L163

**Comment by sklam** [comment]
https://github.com/numba/llvmlite/pull/483 should have fixed this.
