### ISSUE TITLE
Can't update to version 0.29!

### ISSUE THREAD

**Issue by linssab** [numba/llvmlite#486]
Error:
> ImportError: Numba requires at least version 0.29.0 of llvmlite.
> Installed version is 0.28.0.
> Please update llvmlite.

Tried `pip install llvmlite` and it returns:

> Requirement already satisfied: llvmlite in _______local\programs\python\python37\lib\site-packages (0.28.0)

 

Same with `pip install llvmlite --upgrade`

managed to run my code by changing the __version.py_ file under my python environment (which is totally far from ideal)

**Comment by sklam** [comment]
It sounds like you have installed the latest numba from source. It depends on the latest unreleased version of llvmlite.  If you are interested in developing numba, the preferred toolchain is `conda` and we provide nightly build of llvmlite there.  If you want a stable releases, you can `pip install numba` or `conda install numba`.

**Comment by n-io** [comment]
Neither `pip` nor `conda` appear to have the 0.29.0 release of llvmlite at the moment.

**Comment by n-io** [comment]
Why close? The question was not really answered.

**Comment by seibert** [comment]
We are in the middle of our release process, so the final packages for 0.29.0 should appear over the next few days.

**Comment by linssab** [comment]
I just posted it to kinda let know it was not working, but I also gave a workaround the issue to just make the code run for the moment by changing the version tag at  `_version.py` file of the module itself.
I'll keep it open until 0.29 gets released then 👍

**Comment by Lamar1122-art** [comment]
https://github.com/numba/llvmlite/issues/486#issue-444898859

**Comment by Lamar1122-art** [comment]
local\programs\python\python37\lib\site-packages

**Comment by emmTrump** [comment]
`pip install llvmlite --ignore-installed`,that's worked for me, thanks !!!
