### ISSUE TITLE
package installation dist-info directory doesn't comply with standards

### ISSUE THREAD

**Issue by zhimengfan1990** [numba/llvmlite#489]
With `llvmlite==0.28.0`, the wheel file basename is `llvmlite-0.28.0-1-cp27-cp27mu-manylinux1_x86_64.whl`. By the standard, the installation dist-info directory should be `llvmlite-0.28.0-1.dist-info`, while the actual directory is `llvmlite-0.28.0.dist-info`(without `-1`). This cause some error in our build system. Please fix this, thanks!

**Comment by sklam** [comment]
It seems the `.dist-info` is correctly named according to PEP 427.

> {distribution}-{version}.dist-info/ contains metadata.

(from https://www.python.org/dev/peps/pep-0427/#file-contents)

The `.dist-info` directory doesn't contain the build-tag (the `-1`).

While the `.whl` does:

> The wheel filename is {distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl.

(from https://www.python.org/dev/peps/pep-0427/#file-name-convention)

Cross-checking the deferred [PEP 491](https://www.python.org/dev/peps/pep-0491/), the file name convention has not been changed.

**Comment by zhimengfan1990** [comment]
Thanks for the clarification, I think your answer is correct, sorry for the false alarm. Close it now.
