### ISSUE TITLE
Fedora: requires building with fPIC

### ISSUE THREAD

**Issue by aeroevan** [numba/llvmlite#493]
I'm not sure if this is a problem with the llvm-config flags, but on Fedora 30 (with LLVM 8), llvmlite-0.29.0 requires `export CXX_FLTO_FLAGS=" -flto -fPIC "` to build.

**Comment by danigosa** [comment]
Same issue here, Ubuntu 18.04, `llvm-8-dev` from `llvm-toolchain-bionic-8`, same solution as @aeroevan

**Comment by sklam** [comment]
I noticed that when building pip wheels on the manylinux1 docker image that `-fPIC` was required.  I wondered if it has to do with the toolchain.

**Comment by sklam** [comment]
I think https://github.com/numba/llvmlite/pull/502 have addressed this. Closing.

Please reopen if the problem persist.
