### ISSUE TITLE
from numba import jit: No available targets are compatible with triple "arm-unknown-linux-gnu"

### ISSUE THREAD

**Issue by gnthibault** [numba/llvmlite#497]
Hi all.
I am trying to setup numba on python3 for a project to run on an arm platform. Unfortunately, I am experiencing a failure at runtime, and I don't really understand where is this coming from, and what should I do with this error ?

(I use llvm 8.0 compiled locally and latest version of llvmlite, also compiled locally)

>     from numba import jit
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/__init__.py", line 41, in <module>
>     import numba.typed
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typed/__init__.py", line 3, in <module>
>     from .typeddict import Dict
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typed/typeddict.py", line 18, in <module>
>     @njit
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/decorators.py", line 224, in njit
>     return jit(*args, **kws)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/decorators.py", line 161, in jit
>     return wrapper(pyfunc)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/decorators.py", line 177, in wrapper
>     **dispatcher_args)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/dispatcher.py", line 542, in __init__
>     self.targetctx = self.targetdescr.target_context
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/targets/registry.py", line 50, in target_context
>     return self._toplevel_target_context
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/utils.py", line 381, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
>     return cpu.CPUContext(self.typing_context)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/targets/base.py", line 250, in __init__
>     self.init()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/targets/cpu.py", line 49, in init
>     self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/targets/codegen.py", line 608, in __init__
>     self._init(self._llvm_module)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/targets/codegen.py", line 613, in _init
>     target = ll.Target.from_triple(ll.get_process_triple())
>   File "/usr/local/lib/python3.5/dist-packages/llvmlite/binding/targets.py", line 195, in from_triple
>     raise RuntimeError(str(outerr))
> RuntimeError: No available targets are compatible with triple "arm-unknown-linux-gnu"

I am using an armhf linux distribution, also I don't know if that helps:

> llvm-config --version --prefix --components --targets-built --host-target
> 8.0.0
> /usr/local
> aarch64 aarch64asmparser aarch64asmprinter aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets analysis arm armasmparser armasmprinter armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter binaryformat bitreader bitwriter codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfomsf debuginfopdb demangle dlltooldriver engine executionengine fuzzmutate globalisel instcombine instrumentation interpreter ipo irreader libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mirparser native nativecodegen objcarcopts object objectyaml option optremarks orcjit passes profiledata runtimedyld scalaropts selectiondag support symbolize tablegen target textapi transformutils vectorize windowsmanifest xray
> AArch64 ARM
> aarch64-unknown-linux-gnu

**Comment by sklam** [comment]
It'd be useful to know the output of the following:

```python
>>> from llvmlite import binding as ll
>>> print(ll.get_process_triple())  # what target does llvm thinks the process is running in?
>>> print(tuple.__itemsize__)  # 32-bit vs 64-bit build?
```

**Comment by seibert** [comment]
I checked on our Jetson TX2, and `ll.get_process_triple()` returns `'aarch64-unknown-linux-gnu'`, which matches up with what `llvm-config --host-target` also reports.

**Comment by seibert** [comment]
And our Raspberry Pi returns `armv7l-unknown-linux-gnueabihf`.  I'm not sure where plain `arm-unknown-linux-gpu` would come from....

**Comment by seibert** [comment]
I suppose the other thing to check is what the kernel reports for:
```
uname -m -p -i -o
```
Our Jetson TX2 reports:
```
$ uname -m -p -i -o
aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by gnthibault** [comment]
Ok thank you all for your feedback. Here is the output of 'uname -m -p -i -o':
aarch64 unknown unknown GNU/Linux

However although my kernel is aarch64, I do know that my distribution is a armhf userspace.

Here is what happens on the python side:

```
rock@localhost:~$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from llvmlite import binding as ll
>>> print(ll.get_process_triple())
arm-unknown-linux-gnu
>>> print(tuple.__itemsize__)
4
```

**Comment by seibert** [comment]
Hmm, so this is a situation we've never encountered.  It seems that you have a 32-bit binary running on an AArch64 system.  What distribution is this?

**Comment by gnthibault** [comment]
It is a distribution for an embedded system (actually quite powerful system on chip): https://github.com/mrfixit2001/debian_desktop

**Comment by seibert** [comment]
Our current theory is that you are running a 32-bit build of Python, which would create this mismatch.  One fix would be to switch to an AArch64 build of Python, though I don't know how feasible that is.

As for your other option of building LLVM with the 32-bit target, that also seems like a solution, but I'm not sure why you having issues with that approach.

**Comment by gnthibault** [comment]
Ok thank you a lot for your feedback. Building a full python environment in aarch64 should be feasible (my distribution is multi-arch compatible, or I can setup a fully aarch64 chroot somwhere) but require quite a lot of efforts.

To be honnest, staying fully armhf (32bits) would be much easier for me, even if I need to do an ugly temporary fix somwhere.

**Comment by sklam** [comment]
Try this to see if you have a 32-bit build of Python:

```python
$ file -L `which python`
```

Sample output on my machine:
```
/usr/bin/python: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=cde2c487269892a2815c715667ae336984b82b0c, stripped
```

**Comment by gnthibault** [comment]
file -L `which python3`
/usr/bin/python3: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=33a2bd0786c4fe4fa40f029319ceb4738cec9b82, stripped

**Comment by jjhelmus** [comment]
Can you build llvm for armhf by prefixing the build commands (./configure, make, etc) with `linux32`?  That should force the build system to treat the machine as if it is 32-bit.

**Comment by gnthibault** [comment]
Thank you for your help. Should I be fine with the following options:
-DLLVM_DEFAULT_TARGET_TRIPLE=arm-linux-gnueabihf
-DLLVM_TARGET_ARCH=ARM
-DLLVM_TARGETS_TO_BUILD=ARM

**Comment by gnthibault** [comment]
OK with the parameters I put in my previous image it worked like a charm woohoo ! thank you for your help

**Comment by seibert** [comment]
Great!  I'm glad you were able to figure it out.  :)

**Comment by dhgokul** [comment]
When tried to import numba and got below issue. Please help me to sort out this issue
RuntimeError: Unable to find target for this triple (no targets are registered)

Kernal report : $ uname -m -p -i -o
aarch64 aarch64 aarch64 GNU/Linux

$ file -L `which python`
/root/.virtualenvs/py3cv4/bin/python: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=d627ef878f18bc969e1914564d7a2c095c310c6d, stripped

cmake command:
 sudo cmake llvm-10.0.1.src/  -DLLVM_TARGETS_TO_BUILD="ARM"  -DLLVM_TARGET_ARCH=ARM -DLLVM_DEFAULT_TARGET_TRIPLE=armv8-linux-gnueabihf  -DLLVM_USE_LINKER=gold -DCMAKE_BUILD_TYPE="Release"

Python version:
>>> import llvmlite
>>> llvmlite.__version__
'0.34.0'

**Comment by esc** [comment]
@dhgokul I answered your question in #628
