### ISSUE TITLE
llvmlite can't find dylib

### ISSUE THREAD

**Issue by lewisl** [numba/llvmlite#50]
pip reports llvmlite installed successfully. It imports.  However, numba won't import:  it can't find llvmlite/binding/libllvmlite.dylib.  The same thing occurs when trying to run the tests for llvmlite.

But, there in site-packages I find the dylib:  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/llvmlite/binding/libllvmlite.dylib

If it is not supposed to be at that location, then where should it be?  

And where is Python looking for it since it is not finding it in site-packages?

And, no, I am not going to use conda or Anaconda Python.  If it can't work with a standard Python installation, then it must not be compatible with Python from the Python Software Foundation, the authoritative source.  An alternative install of Python should not be necessary.

**Comment by mmpagani** [comment]
I have a similar error and I would like to understand if there's any possible solution. Thank you for your assistance.

**Comment by seibert** [comment]
what output do you get when you run:
```
which python
which pip
```
?

**Comment by mmpagani** [comment]
$ which python
/opt/local/bin/python

$ which pip
/opt/local/bin/pip

Thank you
m

**Comment by seibert** [comment]
I think @mmpagani and @lewisl might have two different problems, so I don't know if it makes sense to try to debug both inside of one issue.  @mmpagani: Can you open a new issue and provide more detail on your individual problem?  Specifically, what errors do you see and do you see llvmlite being installed to the /Library/Frameworks/ directory or not?

Thanks.

**Comment by mmpagani** [comment]
Dear Stan,

Thank you for your email and help. I actually managed to solve the
problem by basically removing everything and reinstalling numba from
scratch via pip. Everything is working now and - disappointingly - I
don't seem able to reproduce the problem I was signalling.

Thank you so much for your help. Much appreciated.

Marco
