### ISSUE TITLE
How to switch to another LLVM version?

### ISSUE THREAD

**Issue by mohanson** [numba/llvmlite#503]
Before I install llvmlite(by `pip3 install llvmlite`), I already have LLVM installed(`llvm-config --version: 8.0.0`). Now I compiled another LLVM, but I don't known how to switich llvmlite's llvm to my new LLVM.

I tried set environment `$LLVM_CONFIG`, or remove the old llvm from the `$PATH`,  but ita all doesn't work. 

Thanks!

**Comment by seibert** [comment]
llvmlite statically links to LLVM, with reasoning described here: 

https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#why-static-linking-to-llvm

You need to recompile llvmlite to use a different LLVM.  Note that we have only tested Numba/llvmlite with LLVM 8.0.0, and not the 8.0.1 release yet (though it will probably work).  Things are more likely to break with the LLVM 9.0.0rc1.

**Comment by mohanson** [comment]
Understand, thanks!
