### ISSUE TITLE
How to add addrspace to function call?

### ISSUE THREAD

**Issue by tdh8316** [numba/llvmlite#505]
Hi, I would like to generate this LLVM IR through llvmlite.
What I want to generate is:
```llvm
%1 = tail call addrspace(1) i16 @_ZN5Print5printEPKc(%class.Print* getelementptr inbounds (%class.HardwareSerial, %class.HardwareSerial* @Serial, i16 0, i32 0, i32 0), i8* getelementptr inbounds ([14 x i8], [14 x i8]* @.str, i16 0, i16 0)) #3
```
Full LLVM IR is here: https://gist.github.com/tdh8316/12f8e79b60c18b550e3292f06a606608#file-arduino_serial-ll-L17

I tried to generate an IR using this code:
```python
string = "Hello, world!\n"
c_string = ir.Constant(ir.ArrayType(i8, len(string)), bytearray(string.encode("utf8")))

global_string = ir.GlobalVariable(m, c_string.type, name=self.id)
global_string.linkage = "private unnamed_addr"
global_string.global_constant = True
global_string.initializer = c_string

builder.call(Serial.print(m), [builder.bitcast(global_string, i32)], tail=True)
```
And the result is:
```llvm
define void @"setup"() 
{
entry:
  %".2" = bitcast [14 x i8]* @"1932411367912" to i32
  %".3" = tail call i16 @"Serial.print"(i32 %".2") ; addrspace(1)?
}

@"1932411367912" = private unnamed_addr constant [14 x i8] c"Hello, world!\0a"
declare i16 @"Serial.print"(i32 %".1") 
```

How can I add addrspace(1) at function call?
Or is there a way to directly add LLVM IR string?

**Comment by esc** [comment]
@tdh8316 thanks for following up on this and closing the issue. I presume you managed to solve it?

**Comment by tdh8316** [comment]
@esc Unfortunately not. Not working on the project in which I worked before anymore and not getting any answer for this, I decided to close this issue. I didn't know that I opened this issue a long time ago until yesterday.

**Comment by esc** [comment]
@tdh8316 well, thanks for following up anyway and closing this. It is appreciated.
