### ISSUE TITLE
Support LLVM 9

### ISSUE THREAD

**Issue by fabmazz** [numba/llvmlite#523]
LLVM 9 is out since September 19, it should be good to add support for it, since some "always up-to-date" distributions already jumped to it.

**Comment by stuartarchibald** [comment]
Thanks for the request. Testing the Numba stack against LLVM 9 will happen in this (0.31.0) release cycle, there are a number of potential problems relating to windows compilers and the POWER targets that may need addressing.

**Comment by esemeniuc** [comment]
A quick fix is to run
```bash
pip install git+https://github.com/jschueller/llvmlite.git@patch-1
```

**Comment by stuartarchibald** [comment]
Unless I am mistaken, the above patch is not adding support, it is just removing the version check.

**Comment by esemeniuc** [comment]
> Unless I am mistaken, the above patch is not adding support, it is just removing the version check.

Correct. It works perfectly with librosa on Arch

**Comment by flying-sheep** [comment]
People in the [PKGBUILD’s comments](https://aur.archlinux.org/packages/python-llvmlite/) report “mysterious bytecode issues” arising when using it with LLVM 9.

**Comment by stuartarchibald** [comment]
> People in the [PKGBUILD’s comments](https://aur.archlinux.org/packages/python-llvmlite/) report “mysterious jit issues with bytecode parsing” arising when using it with LLVM 9.

May this have been due to using Python 3.8 when it wasn't supported perhaps? Numba 0.47.0 was the first version to support 3.8.

**Comment by flying-sheep** [comment]
Aaah right, in November 0.47 wasn’t around.

**Comment by mjsteinbaugh** [comment]
Following up on this, LLVM 9 is working for me. Currently running Python 3.8.1 and the latest versions of dependencies from pip.

**Comment by aginiewicz** [comment]
What tests are missing for this to go mainstream? I'm interested in helping - as soon as LLVM 9 is supported I will move this package to community repository in Arch Linux (I maintain pandas package and I'm in progress of moving Numba, xarray and dependencies to make pandas on Arch more complete).

**Comment by seibert** [comment]
Our main test is verifying that Numba works once we are certain we can build LLVM 9 on all platforms we need to support.  This is in progress now, and we're aiming for a March release of Numba / llvmlite with LLVM 9 support.  (assuming we don't find code generation issues, since every LLVM release is different...)

**Comment by aaronpuchert** [comment]
The question what you allow building with and what you explicitly support are not the same.

If you know that your code isn't working on a newer version, then guard against it, but if you've just not tested it enough, this should just be a recommendation or warning. And of course you don't need to distribute this with LLVM 9 unless you feel confident about it.

If you fear that users might overlook such a warning, you can also error out and tell the user how to build the package with an unsupported newer version of LLVM if they so desire, perhaps by adding a flag. This is also what @seibert suggested in #507, if I understand correctly.

**Comment by boegel** [comment]
Are there any updates on supporting LLVM 9.x for `llvmlite`/`numba`?

Can we somehow track progress being made (a milestone for example)? Is there an updated ETA for a release that supports LLVM 9, or is it still sometime in March 2020 as @seibert suggested earlier?

No pressure, just trying to assess whether it makes sense for EasyBuild to pick up LLVM 9, or if this will block us from using the latest `numba` (see discussion in https://github.com/easybuilders/easybuild-easyconfigs/pull/10133)...

**Comment by stuartarchibald** [comment]
LLVM 9 is now largely tested but there are some problems (IIRC all of which are PPC64LE related), as a result, it unfortunately will not make the release candidate scheduled for this week. The aim is to get it done for Numba 0.50/llvmlite 0.33, which is about 7 weeks away, this permits a bit more time to work around the issues. Hope this helps.

**Comment by stuartarchibald** [comment]
https://github.com/numba/llvmlite/pull/548 puts LLVM 9 on master, thank you all for your patience and understanding.

There's also now an env var to permit building against unsupported LLVMs http://llvmlite.pydata.org/en/latest/admin-guide/install.html#compiling-llvmlite
