### ISSUE TITLE
Getting llvmlite to run under pypy

### ISSUE THREAD

**Issue by davidwynter** [numba/llvmlite#525]
After reading this [running-numba-on-pypy](https://www.embecosm.com/2017/01/19/running-numba-on-pypy/) was encouraged that I could get numba (with it's llvmlite dependency) to run under pypy3.6. But in experimenting with my dockerfile I could not get it to work. I posted details on SO here [dockerfile-fails-with-llvm-config-error-for-numba-install](https://stackoverflow.com/questions/58353351/dockerfile-fails-with-llvm-config-error-for-numba-install/58361574#58361574)
Is the only answer having a wheel created?

**Comment by jvesely** [comment]
Hi,

I'm not a llvmlite dev, but I run llvmlite in pypy3 regularly without issues. see for example [0]. You need to have llvm development packages installed for build llvmlite from sdist

[0] https://travis-ci.com/jvesely/PsyNeuLink/jobs/284087229

**Comment by esc** [comment]
@jvesely thanks for reporting back about this! I am not sure this is mentioned anywhere in the llvmlite documentation. If you are inclined, I would encourage you to consider submitting a pull-request to add some information and maybe some instructions to the documentation.

**Comment by seibert** [comment]
llvmlite is a relatively simple wrapper around LLVM, so I'm not surprised that it works with PyPy when recompiled.  Numba is much more challenging to port to PyPy, as it depends on many more Python C APIs, as well as the bytecodes themselves, which could technically be different on PyPy (but I have no idea if they are).

**Comment by jvesely** [comment]
> @jvesely thanks for reporting back about this! I am not sure this is mentioned anywhere in the llvmlite documentation. If you are inclined, I would encourage you to consider submitting a pull-request to add some information and maybe some instructions to the documentation.

I'm not sure where to add this. There already is a page on building llvm+llvmlite fro source [0].
The only thing that could be missing is that
```
LLVM_CONFIG=/path/to/llvm-config CXXFLAGS=-fPIC pip3 install llvmlite
```
can be used instead of the
```
setup.py build
setup.py install
```
sequence.
That said I've never had any trouble with using distro provided llvm-dev packages

[0] http://llvmlite.pydata.org/en/latest/admin-guide/install.html

**Comment by esc** [comment]
@jvesely I was referring more to your ability of running llvmlite in pypy3 - i.e. adding the fact that this is possible and how to do so to the docs, make sense?

**Comment by jvesely** [comment]
> @jvesely I was referring more to your ability of running llvmlite in pypy3 - i.e. adding the fact that this is possible and how to do so to the docs, make sense?

That's what I meant. Running under pypy3 is no different than installation from `sdist`.
I've used `LLVM_CONFIG=... CXXFLAGS=-fPIC pip3 install llvmlite` to run on:
 * pypy3 on x86
 * cpython on arm
 * pypy3 on arm
 * cpython on ppc64le (modulo #550)

I've opened a PR here: https://github.com/numba/llvmlite/pull/552

**Comment by esc** [comment]
@jvesely awesome, thank you!

**Comment by stonebig** [comment]
any refreshed hope on llvmlite for pypy-7.3.5 ?

**Comment by gmarkall** [comment]
> any refreshed hope on llvmlite for pypy-7.3.5 ?

I've just tried llvmlite with 7.3.4 (7.3.5 appears not to be on conda-forge) and it builds and passes tests without issue for me:

```
$ pypy --version
Python 3.7.10 (51efa818fd9b24f625078c65e8e2f6a5ac24d572, Apr 09 2021, 13:41:19)
[PyPy 7.3.4 with GCC 9.3.0]

$ pypy -c "import llvmlite; print(llvmlite.__version__)"
0.37.0dev0-23-g990a0d4

$ pypy ./runtests.py
..s............................................................s..............................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 302 tests in 3.512s

OK (skipped=2)
```

Is there a problem specifically with 7.3.5, @stonebig?

**Comment by stonebig** [comment]
Well, I'm on pypi, so relying on cgohlke good wheels.

**Comment by stonebig** [comment]
If it's OK on conda then hope is great to see it soon

**Comment by jvesely** [comment]
using pip:
```
$ sudo apt install build-essential llvm-10-dev pypy3-dev python3-pip
$ pypy3 --version
Python 3.6.9 (7.3.1+dfsg-4, Apr 22 2020, 05:15:29)
[PyPy 7.3.1 with GCC 9.3.0]
$ LLVM_CONFIG=llvm-config-10 pypy3 -m pip install llvmlite --user
$ pypy3 -c 'import llvmlite; print(llvmlite.__version__)'
0.36.0
$ pypy3 -c 'import llvmlite.tests as tests; tests.main()'
..s............................................................s..............................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 302 tests in 5.335s

OK (skipped=2)
```

If the hope is for binary wheels for pypy3, I wouldn't expect that to happen unless numba starts supporting pypy.

**Comment by gmarkall** [comment]
It seems like there are no unresolved issues here - can we close this?

**Comment by stonebig** [comment]
In fact, I just look for the pypy numba wheel now

**Comment by stonebig** [comment]
Maybe I can succeed to compile it myself... will try

**Comment by esc** [comment]
> In fact, I just look for the pypy numba wheel now

That's good, so let's close this issue and open a new feature request for Pypy wheels?

**Comment by stonebig** [comment]
Do as you see best

**Comment by gmarkall** [comment]
Feature request created in #725.

**Comment by esc** [comment]
@gmarkall thank you!
