### ISSUE TITLE
Failed to install llvmlite with Python 3.8 (pip)

### ISSUE THREAD

**Issue by eidalex** [numba/llvmlite#527]
Hi, 
I first try to install **numba** with Python 3.8 ... it went wrong. I seemed like there was a problem with llvmlite. Indeed, when trying to install **llvmlite**, alone It went wrong and I had the error:

ERROR: Command errored out with exit status 1: 'C:\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\\AppData\\Local\\Temp\\pip-install-7u87xl57\\llvmlite\\setup.py'"'"'; __file__='"'"'C:\\Users\\\AppData\\Local\\Temp\\pip-install-7u87xl57\\llvmlite\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\AppData\Local\Temp\pip-record-no_sgdu3\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

I simply use the command : `pip install llvmlite`.

- Operating System: Windows 10 Enterprise 1709
- Python version : 3.8

Am I doing something wrong ? 
Thank you in advance :)

**Comment by esc** [comment]
@eidalex thanks for asking about this. I believe that neither Numba and probably also llvmlite currently don't support Python 3.8:

see also: https://twitter.com/numba_jit/status/1189933337391095808

**Comment by seibert** [comment]
Yeah, we haven't built wheels for Python 3.8 since Numba won't support the new bytecode usage until our December release.

**Comment by adamsol** [comment]
`easy_install llvmlite` works for me in Python 3.8.

**Comment by seibert** [comment]
I assume you have LLVM already available in your environment.

**Comment by adamsol** [comment]
I do have clang installed, and I also have used llvmlite with an older version of Python before. I don't exactly understand why `easy_install` worked and `pip install` didn't, though.

**Comment by jvesely** [comment]
Using `pip install llvmlite` works ok for me with system llvm (Linux).
llvmlite also works (simple code generation and JIT execution) on both x86[0] and aarch64[1].
[0] https://travis-ci.org/PrincetonUniversity/PsyNeuLink/jobs/611787117#L773
[1] https://travis-ci.com/jvesely/PsyNeuLink/jobs/256177919#L931

Having wheels for python3.8 and aarch64 would help shave few minutes from those CI runs.

**Comment by eidalex** [comment]
> 
> 
> @eidalex thanks for asking about this. I believe that Numba (and probably also llvmlite) currently don't support Python 3.8:
> 
> see also: https://twitter.com/numba_jit/status/1189933337391095808

Thanks for the reply ! I'll check status.

**Comment by phedwards** [comment]
I understand Numba 0.47 will support Python 3.8 and Numba 0.47 is due in December.  Do we know when in December it will be released?

**Comment by seibert** [comment]
Our target is to have a release candidate conda packages posted on December 19.  We don't typically put our release candidates on PyPI, so the PyPI wheels would appear slightly before or after the new year.

**Comment by jvesely** [comment]
> Our target is to have a release candidate conda packages posted on December 19. We don't typically put our release candidates on PyPI, so the PyPI wheels for the final release would appear slightly before or after the new year.

Is there a chance to have llvmlite wheels up earlier than that? do the problems wrt python 3.8 affect llvmlite as well?
thank you.

**Comment by abhishek429998** [comment]
I am also facing similar error with numba installation on jetpack4.2 I had separately installed llvm using apt-get still facing problem installing llvmlite

**Comment by Juanlu001** [comment]
llvmlite 0.31 is released, with Python 3.8 compatible wheels :tada:

**Comment by stuartarchibald** [comment]
Closing as 3.8 support is complete. Thanks for the input all.

**Comment by Bapi-Reddy** [comment]
For ubunut  sytems: sudo apt-get install libllvm-10-ocaml-dev libllvm10 llvm-10 llvm-10-dev llvm-10-doc llvm-10-examples llvm-10-runtime. This worked for me

**Comment by giorgiberia** [comment]
what about 3.9

**Comment by esc** [comment]
@giorgiberia see: https://github.com/numba/numba/issues/6345

**Comment by jdesman1** [comment]
Found in this reddit thread: https://www.reddit.com/r/Ubuntu/comments/g98cxm/help_installing_llvmlite_dependency_of_numba/

I was able to do the following: 
`sudo apt-get install libllvm-97-ocaml-dev libllvm9 llvm-9 llvm-9-dev llvm-9-doc llvm-9-examples llvm-9-runtime
`

`
export LLVM_CONFIG='/usr/bin/llvm-config-7'
`

`
pip3 install numba
`
