### ISSUE TITLE
"The currently supported LLVM version---LLVM 3.8", Execution engine docs say

### ISSUE THREAD

**Issue by pfalcon** [numba/llvmlite#534]
Here: https://llvmlite.readthedocs.io/en/latest/user-guide/binding/execution-engine.html and here: https://github.com/numba/llvmlite/blob/master/docs/source/user-guide/binding/execution-engine.rst

This is closely related to https://github.com/numba/llvmlite/issues/464 .

**Comment by stuartarchibald** [comment]
Thanks for the report. This just needs fixing.
