### ISSUE TITLE
Could I use llvmlite to complie django?

### ISSUE THREAD

**Issue by Chise1** [numba/llvmlite#538]
Could I use llvmlite to complie django?

**Comment by stuartarchibald** [comment]
Thanks for the question. I suspect that `llvmlite` isn't the tool you want, but please could you provide more information about what it is you want to do just to make sure? Thanks.

**Comment by Chise1** [comment]
Thank you.

**Comment by seibert** [comment]
Depending on what dependencies your Django app has, you might find [PyPy](https://pypy.org/) to be effective.
