### ISSUE TITLE
recursion with if_else context manager

### ISSUE THREAD

**Issue by Bretley** [numba/llvmlite#539]
Python version : 3.7.5
llvmlite version: (0.30.0) (from pip)

Hi, I noticed this whilst trying to generate ir for a toy language I have. I *think* this issue is due to if_else context manager issues with recursion.

In my toy language I have a very simple if-elif .. else construct (like guards in haskell).

My method to do this is to recursively nest them.

```python
def guard_codegen(guards, final, nst, ctx, depth=0):
    if not guards:
        return codegen(final[3], nst, ctx)
    current = guards.pop(0)
    condition = codegen(current[2], nst, ctx)

    with ctx['builder'].if_else(condition) as (then, else_):
        with then:
            codegen(current[5], nst, ctx)
        with else_:
            guard_codegen(guards, final, nst, ctx, depth+2)
```

However, upon entering the new context in the recursed method, the endif is inserted  into IR
(entry.endif before recursed entry.else.if)
```
define i32 @"cmp"() 
{
entry:
  %".2" = icmp slt i32 5, 6
  br i1 %".2", label %"entry.if", label %"entry.else"
entry.if:
  ret i32 -1
entry.else:
  %".5" = icmp sgt i32 5, 6
  br i1 %".5", label %"entry.else.if", label %"entry.else.else"
entry.endif:
entry.else.if:
  ret i32 1
entry.else.else:
  ret i32 0
entry.else.endif:
  br label %"entry.endif"
}
```

in C, the cmp method would be
```
int cmp() {
  if (5 < 6) { return -1; }
  else if (5 >6) { return 1; }
  else { return 0; }
}

If you need any more info or if I've messed up horribly just let me know.
I think the issue is that the new context is being set up with the same irBuilder. I tried it by creating a new irbuilder off of the block of the current one but that did not fix it

**Comment by Bretley** [comment]
The example I've posted only recurses with context once, which means that the entry.endif is being put into the IR directly before the nested / recursed if/else

**Comment by sklam** [comment]
The location of the `entry.endif` should not matter for the semantic. All basicblocks for the `.if_else()` are inserted early on at: https://github.com/numba/llvmlite/blob/6435ea21f73dbf909a0418ed16375361e40d9892/llvmlite/ir/builder.py#L308-L310.  It is needed so that inside `then` and `else`, you can jump to the `endif`.

**Comment by Bretley** [comment]
I'm new to this and didn't really know what to make of it. I just did it manually because my use case called for only the innermost if to have an else.  Thank you though
