### ISSUE TITLE
Please fix the llvm version check

### ISSUE THREAD

**Issue by yurivict** [numba/llvmlite#541]
https://github.com/numba/llvmlite/blob/master/ffi/build.py#L112

It first checks for 8.0, 7.0, 7.1, and then says that it needs LLVM versions 7+. I have 9.0, and it fails. Please check properly so that any 7+ version would pass. Obviously, the current ```or``` syntax with list can not possibly suffice.

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue is that LLVM 9+ is not supported and the checking and error message needs updating.
