### ISSUE TITLE
ppc64le: failed to get host cpu features

### ISSUE THREAD

**Issue by jvesely** [numba/llvmlite#550]
I've run into issues using llvmlite 0.31.0 on linux ppc64le [0 -- the errors start halfway through the log]?

```
    __cpu_features = binding.get_host_cpu_features().flatten()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def get_host_cpu_features():
        """
        Returns a dictionary-like object indicating the CPU features for current
        architecture and whether they are enabled for this CPU.  The key-value pairs
        are the feature name as string and a boolean indicating whether the feature
        is available.  The returned value is an instance of ``FeatureMap`` class,
        which adds a new method ``.flatten()`` for returning a string suitable for
        use as the "features" argument to ``Target.create_target_machine()``.
    
        If LLVM has not implemented this feature or it fails to get the information,
        this function will raise a RuntimeError exception.
        """
        with ffi.OutputString() as out:
            outdict = FeatureMap()
            if not ffi.lib.LLVMPY_GetHostCPUFeatures(out):
>               raise RuntimeError("failed to get host cpu features.")
E               RuntimeError: failed to get host cpu features.
```

[0] https://api.travis-ci.com/v3/job/283524633/log.txt

**Comment by esc** [comment]
@jvesely thanks for submitting this, I have queued it for triage.

**Comment by stuartarchibald** [comment]
@jvesely is this a "new" problem, i.e. used to work but now does not? Or is this something from trying out on ppc64le?

**Comment by jvesely** [comment]
It was the first time I've tried ppc64le. digging a bit deeper I don't think ppc64le ever worked.
`getHostCPUFeatures` returns `false` on anything other than x86 or arm [0],
and the C wrapper uses the return value to populate the features string.
I think that returning NULL does not indicate error, and shouldn't throw an exception.
 
[0] https://github.com/llvm/llvm-project/blob/master/llvm/lib/Support/Host.cpp#L1570

**Comment by seibert** [comment]
Do we understand why this doesn't affect Numba (which we continuously test on PPC)?

**Comment by jvesely** [comment]
> Do we understand why this doesn't affect Numba (which we continuously test on PPC)?

numba uses a custom wrapper that ignores the `RuntimeError` thrown by `get_host_cpu_features`:
https://github.com/numba/numba/blob/master/numba/core/codegen.py#L855

**Comment by seibert** [comment]
and presumably we're not testing this function in llvmlite's unit tests? (which we also run on PPC)

**Comment by stuartarchibald** [comment]
I just shelled into a power8 machine. `llvmlite.binding.get_host_cpu_features()` raises a `RuntimeError()` as per the OP.

**Comment by stuartarchibald** [comment]
> and presumably we're not testing this function in llvmlite's unit tests? (which we also run on PPC)

workarounds: https://github.com/numba/llvmlite/blob/master/llvmlite/tests/test_binding.py#L305-L333

**Comment by jvesely** [comment]
> and presumably we're not testing this function in llvmlite's unit tests? (which we also run on PPC)

Are those tests publicly accessible? I've checked that travis doesn't include ppc64le configuration and uses custom docker images which are only for x64 and x32 (which looks more like x86 than x32).

**Comment by stuartarchibald** [comment]
> > and presumably we're not testing this function in llvmlite's unit tests? (which we also run on PPC)
> 
> Are those tests publicly accessible? I've checked that travis doesn't include ppc64le configuration and uses custom docker images which are only for x64 and x32 (which looks more like x86 than x32).

No, sadly not. The Numba project has a build farm with real hardware for all these architectures so it can build and test against them, it's not public.
