### ISSUE TITLE
Build issue with LLVM-8.0.1 & llvmlite-0.31.0: 'libllvmlite.so' failed

### ISSUE THREAD

**Issue by openedev** [numba/llvmlite#553]
Hi,

I found a build issue with LLVM-8.0.1 for llvmlite-0.31.1 release. I have built the LVMM-8.0.1 and link to llvmlite using buildroot environment. Let me know if I miss anything.

Build Log:
(cd /home/open/output/build/python-llvmlite-0.31.0//; _PYTHON_SYSCONFIGDATA_NAME="_sysconfigdata__linux_aarch64-linux-gnu" PATH="/home/open/output/host/bin:/home/open/output/host/sbin:/home/open/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" PATH="/home/open/output/host/bin:/home/open/output/host/sbin:/home/open/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" AR="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-ar" AS="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-as" LD="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-ld" NM="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-nm" CC="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-gcc" GCC="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-gcc" CPP="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-cpp" CXX="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-g++" FC="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-gfortran" F77="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-gfortran" RANLIB="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-ranlib" READELF="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-readelf" STRIP="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-strip" OBJCOPY="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-objcopy" OBJDUMP="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-objdump" AR_FOR_BUILD="/usr/bin/ar" AS_FOR_BUILD="/usr/bin/as" CC_FOR_BUILD="/usr/bin/gcc" GCC_FOR_BUILD="/usr/bin/gcc" CXX_FOR_BUILD="/usr/bin/g++" LD_FOR_BUILD="/usr/bin/ld" CPPFLAGS_FOR_BUILD="-I/home/open/output/host/include" CFLAGS_FOR_BUILD="-O2 -I/home/open/output/host/include" CXXFLAGS_FOR_BUILD="-O2 -I/home/open/output/host/include" LDFLAGS_FOR_BUILD="-L/home/open/output/host/lib -Wl,-rpath,/home/open/output/host/lib" FCFLAGS_FOR_BUILD="" DEFAULT_ASSEMBLER="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-as" DEFAULT_LINKER="/home/open/output/host/bin/aarch64-buildroot-linux-gnu-ld" CPPFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  " CXXFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  " LDFLAGS="" FCFLAGS=" -Os " FFLAGS=" -Os " PKG_CONFIG="/home/open/output/host/bin/pkg-config" STAGING_DIR="/home/open/output/host/aarch64-buildroot-linux-gnu/sysroot" INTLTOOL_PERL=/usr/bin/perl PYTHONPATH="/home/open/output/target/usr/lib/python3.8/" PYTHONNOUSERSITE=1 _python_sysroot=/home/open/output/host/aarch64-buildroot-linux-gnu/sysroot _python_prefix=/usr _python_exec_prefix=/usr  /home/open/output/host/bin/python setup.py build  )
running build
got version from expanded keyword {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
running build_ext
/home/open/output/host/bin/python /home/open/output/build/python-llvmlite-0.31.0/ffi/build.py
LLVM version... 8.0.1

SVML not detected
make[1]: Entering directory '/home/open/output/build/python-llvmlite-0.31.0/ffi'
static-libstdc++ avoids runtime dependencies on a
particular libstdc++ version.
/home/open/output/host/bin/aarch64-buildroot-linux-gnu-g++  -shared -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os   -I/home/open/output/host/include -std=c++11 -fno-exceptions -fno-rtti -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -g -flto assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp object_file.cpp -o libllvmlite.so  -L/home/open/output/host/lib -flto -Wl,--exclude-libs=ALL -lLLVM-9
/home/open/output/host/lib/gcc/aarch64-buildroot-linux-gnu/7.4.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: skipping incompatible /home/open/output/host/lib/libLLVM-9.so when searching for -lLLVM-9
/home/open/output/host/lib/gcc/aarch64-buildroot-linux-gnu/7.4.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/ccXnr6Qp.ltrans0.ltrans.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN4llvm27DiagnosticPrinterRawOStreamE@@LLVM_9' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/open/output/host/lib/gcc/aarch64-buildroot-linux-gnu/7.4.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/ccXnr6Qp.ltrans0.ltrans.o(.text+0x2c): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZTVN4llvm27DiagnosticPrinterRawOStreamE@@LLVM_9'
/home/open/output/host/lib/gcc/aarch64-buildroot-linux-gnu/7.4.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Makefile.linux:20: recipe for target 'libllvmlite.so' failed
make[1]: *** [libllvmlite.so] Error 1
make[1]: Leaving directory '/home/open/output/build/python-llvmlite-0.31.0/ffi'
Traceback (most recent call last):
  File "/home/open/output/build/python-llvmlite-0.31.0/ffi/build.py", line 168, in <module>
    main()
  File "/home/open/output/build/python-llvmlite-0.31.0/ffi/build.py", line 158, in main
    main_posix('linux', '.so')
  File "/home/open/output/build/python-llvmlite-0.31.0/ffi/build.py", line 150, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/home/open/output/target/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2.
error: command '/home/open/output/host/bin/python' failed with exit status 1

**Comment by sklam** [comment]
The build log says it's picking up a LLVM9.

**Comment by openedev** [comment]
@sklam sorry, I have pasted the another log, please check below. however rest are same.

https://paste.ubuntu.com/p/SkpZ7WYNyN/

**Comment by openedev** [comment]
@sklam explicit mentioning of -fPIC seems fixing the issue. any inputs?

--- a/ffi/Makefile.linux
+++ b/ffi/Makefile.linux
@@ -19,7 +19,7 @@ all: $(OUTPUT)
 $(OUTPUT): $(SRC) $(INCLUDE)
        # static-libstdc++ avoids runtime dependencies on a
        # particular libstdc++ version.
-       $(CXX) $(CXX_STATIC_LINK) -shared $(CXXFLAGS) $(SRC) -o $(OUTPUT) $(LDFLAGS) $(LIBS)
+       $(CXX) $(CXX_STATIC_LINK) -shared -fPIC $(CXXFLAGS) $(SRC) -o $(OUTPUT) $(LDFLAGS) $(LIBS)
 
 clean:
        rm -rf test $(OUTPUT)

**Comment by sklam** [comment]
We have seen a few issues relating to `-fPIC`.  It's not clear to me in what situation we need it. It seems to depends on which compiler version is used.

**Comment by nehaljwani** [comment]
@sklam The compiler activation scripts for Anaconda Distribution Compilers inject `-fPIC` unconditionally (vis `CXXFLAGS`): https://github.com/AnacondaRecipes/ctng-compiler-activation-feedstock/blob/f9ee66fe68bd6ffacb59894065f2614d8215891f/recipe/conda_build_config.yaml#L29

This is the reason why you are seeing reports from people not using the Anaconda Compilers Toolchain.

**Comment by esc** [comment]
From what I can tell this issue refers to an older version of LLVM and llvmlite and in addition the issues identified regarding `-fPIC` have been resolved. Hence I am closing this issue now assuming resolved. Please feel free to comment if that is not the case. Thank you!
