### ISSUE TITLE
undefined symbol: LLVMInitializeInstCombine from EasyBuild of numba

### ISSUE THREAD

**Issue by kelseymh** [numba/llvmlite#574]
I originally posted this in the EasyBuild community ([easyconfig #10318](https://github.com/easybuilders/easybuild-easyconfigs/issues/10318), but after searching, I found related issues here ( #441 and #182 ).

After a successful build (using EasyBuild's "foss-2018b" toolchain with GCC 7.3.0) of numba 0.26.0 against LLVM/6.0.0 and Python 3.6.6, the numba executable itself fails to run, reporting back

> `OSError: /scratch/group/mitchcomp/eb/x86_64/sw/numba/0.37.0-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so: undefined symbol: LLVMInitializeInstCombine`

I found that the libllvmlite.so contains dynamic links to all of the LLVM .so libraries, and while that symbol is "u" in libllvmlite.so, it ought to get resolved from the LLVMInstCombine.so library, found via LD_LIBRARY_PATH.

If I understand the llvmlite documentation and ffi/Makefile comments, that .so library should have been built internally with static linkage, pulling all of the LLVM symbols into it, to avoid the shared library dependence.  Clearly this didn't happen. :-)

In Makefile.linux the build action includes a Make variable I don't recognize, which likely has some bearing on my issue:

> `$(CXX) $(CXX_STATIC_LINK) -shared $(CXXFLAGS) $(SRC) -o $(OUTPUT) $(LDFLAGS) $(LIBS)`

Where should CXX_STATIC_LINK be defined?  And what value should it have?  I notice that this variable doesn't appear in either Makefile.freebsd or Makefile.osx.

**Comment by kelseymh** [comment]
My colleage at Texas A&M HPRC found an old [bug report](https://github.com/librosa/librosa/issues/794) in the [librosa](https://github.com/librosa) package with this same issue.  It turns out to have been fixed in LLVM/6.0.1, which we now have installed at HPRC.  Using it eliminates the undefined symbol error above, while switching back to LLVM/6.0.0 (without rebuilding) restores the error.

**Comment by esc** [comment]
@kelseymh thanks for following up on this and closing this issue.
