### ISSUE TITLE
LLVM 10 testing status

### ISSUE THREAD

**Issue by seibert** [numba/llvmlite#583]
This issue is for tracking the evaluation and testing of LLVM 10:

- [ ] Create PR which updates llvmdev conda build recipe to 10.0.  Need to check if existing patches are still required, and/or adjust patches if conflicts.
- [ ] Confirm llvmdev builds and passes tests on all platforms.  Upload conda packages with `dev` label to `numba` channel.
- [ ] Create PR which updates llvmlite to build against new llvmdev.
- [ ] Verify llvmlite passes tests on all platforms.  Upload conda packages with `llvmX` label to `numba` channel.
- [ ] Run Numba test suite against patched llvmlite on all platforms.

Issues to keep an eye out for:
- Do the SVML patches need updating?
- Is PPC still crashing hard?
- What is the compiler situation on Windows?  Can we / are we bumping all package builds to VS2017?

**Comment by esc** [comment]
Oh, just noticed this issue while trawling through old issues on this tracker. Much of the above work has gone into: #599 and it would be good to get a review on that.

**Comment by stuartarchibald** [comment]
In testing Numba agains LLVM 10 the following bugs were reported upstream (thanks @esc for doing the reports):
https://bugs.llvm.org/show_bug.cgi?id=47003 (CMake problem, likely impacts all targets)
https://bugs.llvm.org/show_bug.cgi?id=46996 (AArch64 problem, register to register copy hitting an assertion)

**Comment by abebeos** [comment]
Looks like this issue needs an update.

**Comment by stuartarchibald** [comment]
@abebeos thanks, closing as https://github.com/numba/llvmlite/pull/599 implements.
