### ISSUE TITLE
Install on Ubuntu 14.04

### ISSUE THREAD

**Issue by blu-elephant** [numba/llvmlite#61]
I get this error when trying to install `llvmlite` on Ubuntu 14.04 LTS:

    running build
    got version from VCS {'version': '0.4.0+50.gdb2256a', 'full': 'db2256a17baaf23ba470aee12c99d204206b96d3'}
    running build_ext
    /usr/bin/python ffi/build.py
    LLVM version... 3.5.0
    # static-libstdc++ avoids runtime dependencies on a
    # particular libstdc++ version.
    g++ -static-libstdc++ -shared -flto `llvm-config --cxxflags` -fno-rtti assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -flto `llvm-config --ldflags` -Wl,--exclude-libs=ALL `llvm-config --system-libs --libs all`
    /usr/bin/ld: cannot find -lz
    collect2: error: ld returned 1 exit status
    make: *** [libllvmlite.so] Error 1
    Traceback (most recent call last):
    File "ffi/build.py", line 112, in <module>
        main()
      File "ffi/build.py", line 104, in main
        main_posix('linux', '.so')
      File "ffi/build.py", line 96, in main_posix
        subprocess.check_call(['make', '-f', makefile])
      File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
    error: command '/usr/bin/python' failed with exit status 1

I know about issue [30](https://github.com/numba/llvmlite/issues/30), [32](https://github.com/numba/llvmlite/issues/32) and [27](https://github.com/numba/llvmlite/issues/27) . 

I'm trying the method described in [this post](http://eli.thegreenplace.net/2015/building-and-using-llvmlite-a-basic-example/) i.e. downloading the binaries but no luck.

To be clear, I have `libedit-dev, llvm-3.5-dev, enum34` installed and I'm using `python 2.7.6` and getting nowhere. Help appreciated.

**Comment by jriehl** [comment]
You are most likely missing the zlib library.  Looking at my Ubuntu platform I have the following installed:
```
i   zlib1g                                           - compression library - runtime
i A zlib1g-dev                                       - compression library - development
```

**Comment by blu-elephant** [comment]
Thanks. I have a look tomorrow when I'm back at my machine.

**Comment by blu-elephant** [comment]
All done. I had `zlib1g` installed, just needed to apt-get install `zlib1g-dev`. Also, to import `numba` in the python terminal, I had to do a `pip install funcsigs`

**Comment by saxbophone** [comment]
Can I suggest that this is put into the docs? I have just had the same issue on a fairly fresh install of Ubuntu 15.10 and these libraries aren't listed as deps for compilation.

**Comment by rolandog** [comment]
In my case, besides lacking the `zlib1g` and `zlib1g-dev` packages, I also got an error for `/usr/bin/ld: cannot find -ledit`, which was fixed by installing the `libedit-dev` package. This too might be needed as a dependency for numba.

**Comment by pitrou** [comment]
Those are automatic dependencies for LLVM. Trying to list them in the documentation would probably mean the docs would quickly get out of sync.

**Comment by saxbophone** [comment]
@pitrou ok thanks – what do you mean by dependencies for LLVM? I already had LLVM installed on my machine before I tried installing this so I guess you mean a development version of LLVM that this library needs to build?

**Comment by pitrou** [comment]
I mean these are dependencies for linking against LLVM, as given out by `llvm-config --system-libs`. I don't know why the Ubuntu `llvm-dev` package doesn't depend on them.

**Comment by saxbophone** [comment]
Ok @pitrou thanks for clearing that up :smile: :+1:
