### ISSUE TITLE
Publishing 0.34.0 to PyPI

### ISSUE THREAD

**Issue by jakirkham** [numba/llvmlite#619]
It looks like [`0.34.0`]( https://github.com/numba/llvmlite/releases/tag/v0.34.0 ) was tagged recently. Though it doesn't appear there are PyPI packages (unless I'm missing something). Would it be possible to upload PyPI packages as well (in particular an `sdist` would be quite helpful ;)?

**Comment by esc** [comment]
@jakirkham thanks for asking about this! The release and build process for llvmlite is quite resource intensive, so it can take a day or two between tagging the release in our git repository and the packages arriving on anaconda.org and pypi.org. The packages should hopefully arrive soon and I will leave this issue open until they do. For future reference, we usually issue a ticket in the Numba repository with a checklist of all the tasks for a Numba/llvmlite release, in this case, the ticket is here:

https://github.com/numba/numba/issues/6119

**Comment by esc** [comment]
The wheels for `llvmlite` version `0.34.0` have now arrived on PyPi:

https://pypi.org/project/llvmlite/0.34.0/#files

I am closing this issue now, because I believe it is resolved. Please feel free to re-open if this does not appear to be the case. Thank you!

**Comment by jakirkham** [comment]
Thanks Valentin! 😀
