### ISSUE TITLE
PyPi llvm-lite package

### ISSUE THREAD

**Issue by ChrisPattison** [numba/llvmlite#620]
Someone appears to have published a package on pypi named llvm-lite (c.f. llvmlite ) . Is this someone typo-squatting?
https://pypi.org/project/llvm-lite/

**Comment by seibert** [comment]
It appears to be someone who has copied the llvmlite source code from around release 0.33.0.  A quick scan of the sdist doesn't reveal any malicious code (and the module name is still `llvmlite` despite the project name), but this is still problematic.  Thanks for letting us know.  We'll talk to the PyPI admins.

**Comment by seibert** [comment]
Opened an issue here: https://github.com/pypa/pypi-support/issues/555
