### ISSUE TITLE
Can not use zeroinitializer vector as mask in shuffle_vector

### ISSUE THREAD

**Issue by LHolten** [numba/llvmlite#629]
code like this doesn't work, but it should
```python
vector = ir.VectorType(int32, 3)([1, 2, 3])
mask = ir.VectorType(int32, 3)(None)
builder.shuffle_vector(vector, vector, mask)
```
instead we get
```
IndexError: mask values need to be in range(0, 6)
```

**Comment by sklam** [comment]
I see. It is failing to interpret that `null` is `0`.

**Comment by NavyaZaveri** [comment]
@sklam  I'm not so sure if this is a bug - is `int32` a nullable type? If so, then it might make sense to convert `None` to `0`

Otherwise something like this would work fine: 
```
mask = ir.VectorType(int32, 3)(0)
```
