### ISSUE TITLE
Supporting LLVM 11.*

### ISSUE THREAD

**Issue by jakirkham** [numba/llvmlite#639]
LLVM 11.0 was [recently released]( https://www.phoronix.com/scan.php?page=news_item&px=LLVM-11.0-Released ). Would be good if we are also able to use this with llvmlite.

**Comment by stuartarchibald** [comment]
Thanks for asking @jakirkham. LLVM 11 will, at the earliest, be supported in the llvmlite 0.36/Numba 0.53 releases. As usual it'll probably take some time to ensure it works ok on all the supported platforms, and to port patches etc for it.

**Comment by jakirkham** [comment]
Yep no worries. Know you are all hard at work with Numba 0.52. Just raising this so we can track it somewhere 🙂

**Comment by esc** [comment]
@jakirkham W/o making any promises, a realistic expectation would be, that we will release support in Q1 or Q2 2021 year.

**Comment by seibert** [comment]
Since I'm seeing some comments on twitter indicating that LLVM 11 is required for macOS ARM support, I will note here that we are getting some M1 Mac minis for our internal Numba build farm very soon, which will allow us to test on that platform.

**Comment by xhochy** [comment]
> Since I'm seeing some comments on twitter indicating that LLVM 11 is required for macOS ARM support, I will note here that we are getting some M1 Mac minis for our internal Numba build farm very soon, which will allow us to test on that platform.

It seems like LLVM 10 is enough, trying that out in https://github.com/numba/llvmlite/pull/677 later today

**Comment by AdrianBunk** [comment]
> > Since I'm seeing some comments on twitter indicating that LLVM 11 is required for macOS ARM support, I will note here that we are getting some M1 Mac minis for our internal Numba build farm very soon, which will allow us to test on that platform.
> 
> It seems like LLVM 10 is enough, trying that out in #677 later today. Locally, I could Use Numba with that.

In either case a possible complication is https://github.com/numba/llvmlite/blame/master/README.rst#L65-L67

**Comment by tedmiddleton** [comment]
Short of actually offically supporting LLVM 11 and LLVM 12, could you just remove the restriction against using newer versions in the setup installer? I can understand the lower-bound limit, but does the project really need to guard against newer versions with an upper-bound limit?

**Comment by esc** [comment]
Work items required:

- [ ] Prepare a patch to build `llvmdev` from LLVM 11.*
- [ ] Run all test suits on internal build farm
- [ ] Iterate until all issues resolved

**Comment by esc** [comment]
News about the LLVM 11.* release can be found here. I will update the issue title to be more general about the LLVM version.

**Comment by abebeos** [comment]
(you should in any case move those work-items into the original issue, so visitors see them immediately. same for https://github.com/numba/llvmlite/issues/639#issuecomment-759287482)

> Work items required:
> 
>     * [ ]  Prepare a patch to build `llvmdev` from LLVM 11.*

I would expect a branch here, to follow the work

>     * [ ]  Run all test suits on internal build farm

public tests would catch first issues on the branch (visible for all, thus folks can jump in)

>     * [ ]  Iterate until all issues resolved

Issues need to be filed in public

same for llvm12 (#688)

**Comment by esc** [comment]
> (you should in any case move those work-items into the original issue, so visitors see them immediately. same for [#639 (comment)](https://github.com/numba/llvmlite/issues/639#issuecomment-759287482))

I do not understand this comment, please clarify.

**Comment by abebeos** [comment]
If you don't have a dedicated milestone/project, then at least keep all relevant information within one issue, in the initiall issue-text (and not within comments).

So you could file a e.g. a new issue re llvm11 (similar to #688), then add https://github.com/numba/llvmlite/issues/639#issuecomment-759284869 and https://github.com/numba/llvmlite/issues/639#issuecomment-759287482 and all upcoming relevant information to it.

This way, interested parties can find the relevant info immediately. 

(though as stated, I would prefer to have the dev process open, e.g. branch/issues/milestones, to be able to follow/contribute without barriers)

**Comment by danieldjewell** [comment]
FWIW, for reasons I'm not sure of, it appears that LLVM 10.* has been removed from some Linux distributions and replaced with 11.* while LLVM 9.* is still there... (see https://packages.debian.org/sid/llvm-11 from Debian Sid).

Are there any downsides to using 9 vs 10?

Also, perhaps it would be good to add some additional logic around checking for ```llvm-config``` to also check for ```llvm-config-10``` and ```llvm-config-9``` so that automatic builds won't break (e.g. removing the need to manually set ```LLVM_CONFIG=llvm-config-9```)

**Comment by gmarkall** [comment]
> FWIW, for reasons I'm not sure of, it appears that LLVM 10.* has been removed from some Linux distributions and replaced with 11.* while LLVM 9.* is still there... (see https://packages.debian.org/sid/llvm-11 from Debian Sid).

Sid is a rolling release, so versions will continually change as time passes: https://wiki.debian.org/DebianUnstable

Possibly something in Sid still depends on LLVM 9 but nothing depends on 10?

> Are there any downsides to using 9 vs 10?

Numba and llvmlite generally only support a single version of LLVM for a given platform at a time, so the downside of attempting to use LLVM 9 with the latest versions of Numba and llvmlite is that it may not be compatible. Presently they support LLVM 10 except on AArch64, which uses LLVM 9 - so using LLVM 9 on non-AArch64 architectures will not have been as well-tested.

**Comment by mrodozov** [comment]
> support LLVM 10 except on AArch64 

well, we are building and using numba 52, llvmlite 33 and llvm10 on Arm an Power8 so I'm curious what's not supported exactly

**Comment by mrodozov** [comment]
I had trouble with two things building from source, this is the patch:

https://github.com/cms-sw/cmsdist/blob/de888139c5935232a2ada9460a303b5082f42836/py2-llvmlite-removeduplicate.patch

You can remove the duplicate class declaration and you need a to add LLVM==11 section which you don't have right now.
With this alone I built it from source. Oh and you need a condition in  ffi/build.py for llvm 11

**Comment by gmarkall** [comment]
> > support LLVM 10 except on AArch64
> 
> well, we are building and using numba 52, llvmlite 33 and llvm10 on Arm an Power8 so I'm curious what's not supported exactly

You can build and run with versions other than what's suggested in the list of supported versions (to some degree, the further away you get from the supported versions the more hacks you might need), but there is the potential to run into issues that aren't encountered with supported configurations.

llvmlite 0.33 was built and tested against LLVM 9: https://github.com/numba/llvmlite/tree/release0.33#compatibility

From 0.34 onwards: https://github.com/numba/llvmlite#compatibility:

> As of version 0.34.0, llvmlite requires LLVM 10.0.x. on all architectures except aarch64 which requires LLVM 9.0.x due to: https://bugs.llvm.org/show_bug.cgi?id=46996

**Comment by mrodozov** [comment]
Thanks for the clarification. It's a runtime indeed, I'll check it

**Comment by esc** [comment]
I will now commence work on this task.

**Comment by esc** [comment]
Anyone have preferences over:

* LLVM 11.1.0
* LLVM 11.0.1

See also: https://bugs.llvm.org/show_bug.cgi?id=46526

**Comment by mrodozov** [comment]
I do - there is a ABI incompatibilities we had trouble with for 11.0.1
So 11.1.0 is better (from my perspective)

**Comment by esc** [comment]
@mrodozov thank you for responding, I think 11.1.0 it is then. The implementation PR is now live at:

https://github.com/numba/llvmlite/pull/715

**Comment by jakirkham** [comment]
> Anyone have preferences over:
> 
> * LLVM 11.1.0
> * LLVM 11.0.1
> 
> See also: https://bugs.llvm.org/show_bug.cgi?id=46526

Do you have thoughts here @isuruf?

**Comment by PhilipVinc** [comment]
Julia 1.6, which is being considered for the next LTS, uses LLVM 11.0.1, so using that version might address issues that arise for people that call into Python from Julia and vice-versa.

**Comment by fizwit** [comment]
@mrodozov your patch worked fine for building with LLVM 11.0.0 and Numba 0.53.1.  Used LLVMLITE_SKIP_LLVM_VERSION_CHECK=1.  @esc

**Comment by esc** [comment]
@fizwit thank you for adding this and bringing it to our attention. From what i have discovered in https://github.com/numba/llvmlite/pull/715 LLVM 11 support appears very tricky and appears to need multiple additional patches for the full-stack (Numba and llvmlite() test suites to pass. So, as you can imagine I am quite surprised by your comment. Would you be able to shed some more light on what you did? Which architecture your built this for and what the results of the running the test-suite were? Thank you.

**Comment by sklam** [comment]
LLVM 11 is now available in [v0.37.0](https://github.com/numba/llvmlite/releases/tag/v0.37.0)
