### ISSUE TITLE
OSError: Could not load shared object file: llvmlite.dll

### ISSUE THREAD

**Issue by AaronX121** [numba/llvmlite#650]
Hi, I encountered a strange problem when using numba. It looks like that numba fails to run with `llvmlite.dll` missing.

However, I have validated that `llvmlite.dll` is at the location: `C:\Software\Anaconda3\lib\site-packages\llvmlite\binding`, and `import llvmlite` does not report any error.

I will appreciate it very much if anyone could help me solve this problem : )

**Package Info**
Python==3.8.3
numba==0.51.2
llvmlite==0.34.0

**Traceback**
```
In [1]: import numba
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-68d4f1bcefa7> in <module>
----> 1 import numba

C:\Software\Anaconda3\lib\site-packages\numba\__init__.py in <module>
     12 del get_versions
     13
---> 14 from numba.core import config
     15 from numba.testing import _runtests as runtests
     16 from numba.core import types, errors

C:\Software\Anaconda3\lib\site-packages\numba\core\config.py in <module>
     14
     15
---> 16 import llvmlite.binding as ll
     17
     18 IS_WIN32 = sys.platform.startswith('win32')

C:\Software\Anaconda3\lib\site-packages\llvmlite\binding\__init__.py in <module>
      2 Things that rely on the LLVM library
      3 """
----> 4 from .dylib import *
      5 from .executionengine import *
      6 from .initfini import *

C:\Software\Anaconda3\lib\site-packages\llvmlite\binding\dylib.py in <module>
      1 from ctypes import c_void_p, c_char_p, c_bool, POINTER
      2
----> 3 from llvmlite.binding import ffi
      4 from llvmlite.binding.common import _encode_string
      5

C:\Software\Anaconda3\lib\site-packages\llvmlite\binding\ffi.py in <module>
    151         break
    152 else:
--> 153     raise OSError("Could not load shared object file: {}".format(_lib_name))
    154
    155

OSError: Could not load shared object file: llvmlite.dll
```

**Comment by esc** [comment]
@AaronX121 thank you for reporting this! Which operating system are you on? My first guess would be that the install has been corrupted somehow. As a first step, I would recommend to uninstall llvmlite and numba with `conda` and then create a fresh environment and re-install Numba. The llvmlite dependency will be installed automatically.

**Comment by AaronX121** [comment]
Thanks for your reply, my operating system is windows10.

Actually, this problem occured after updating the operating system. I will first follow your suggestions :-)

**Comment by AaronX121** [comment]
Thanks! it works fine after re-installing the llvmlite and numba.

**Comment by esc** [comment]
@AaronX121 I am glad it has been resolved 🎉. Thank you for reporting back!

**Comment by xchern** [comment]
I encontered the same problem today. I finally found the problem is caused by the unsolved dependency of "llvmlite.dll". Somehow "zlib.dll" of anaconda is not properly indexed in the operating system, so windows cannot link "zlib.dll" for "llvmlite.dll", which lead to the OSError.

My solution is to simply copy "zlib.dll" to the folder of "llvmlite.dll". After this operation, "import llvmlite.binding" can work well, and also "import numba".

**Comment by esc** [comment]
@xchern that is interesting, where did you copy the `zlib.dll` from?

**Comment by xchern** [comment]
> @xchern that is interesting, where did you copy the `zlib.dll` from?

From Anaconda's "Library/bin/zlib.dll". I also noticed the package installed from "numba" channel have no problem.

**Comment by esc** [comment]
@xchern interesting, my guess would be that this has something to do with how the underlying LLVM is built. It is possible to activate/deactivate ZLIB support there and I presume the LLVMs for the package from the Numba channel and for main/defaults may have been built differently.

**Comment by gustavlindstroms** [comment]
Experiencing the same problem. However, copying the zlib.dll file into the directory does not work for me.

Python = 3.8.5
Numba = 0.51.2
llvmlite = 0.34.0

**Comment by AaronX121** [comment]
Hi @gustavlindstroms, maybe you can try to re-install the anaconda if it is not too cumbersome.

**Comment by gustavlindstroms** [comment]
> Hi @gustavlindstroms, maybe you can try to re-install the anaconda if it is not too cumbersome.

Yes I tried that, didn't work unfortunately.

**Comment by AaronX121** [comment]
Hi @gustavlindstroms, this issue has been closed. You may need to open another issue in order to get help from the maintainers.

**Comment by esc** [comment]
@gustavlindstroms @xuyxu indeed, if the issue persists, I would recommend opening a new issue or even better, starting a discussion on discourse:

https://numba.discourse.group/

**Comment by ahoyaharr** [comment]
Hi, apologies for posting in a closed issue. This issue is the top result on Google when searching for errors in the stack trace, so I would like to leave the solution that helped me:

A fresh install of MS Windows 10 does not have the C++ redistributable package that is a dependency for llvmlite and attempting importing numba without this package will produce the error in the original post. The package can be downloaded from [Microsoft's website](https://visualstudio.microsoft.com/downloads/) under "Other Tools, Frameworks, and Redistributables".

**Comment by esc** [comment]
@ahoyaharr thank you for adding, that may be useful indeed!

**Comment by rareal** [comment]
> Hi, apologies for posting in a closed issue. This issue is the top result on Google when searching for errors in the stack trace, so I would like to leave the solution that helped me:
> 
> A fresh install of MS Windows 10 does not have the C++ redistributable package that is a dependency for llvmlite and attempting importing numba without this package will produce the error in the original post. The package can be downloaded from [Microsoft's website](https://visualstudio.microsoft.com/downloads/) under "Other Tools, Frameworks, and Redistributables".

This did not fix the issue for me. Reinstalling numba and llvmlite from the conda numba channel did though.
```
conda install -c numba numba
conda install -c numba llvmlite
```

**Comment by HospitableHost** [comment]
> 

Interesting! I have the same problem when I import librosa, not numba, and surprisingly your solution work well too!

**Comment by cadip92** [comment]
I am working in Anaconda environment and installing numba using conda didn't help resolve the problem. I tried installing numba through pip and it worked:
`pip install numba`
