### ISSUE TITLE
llvmlite, how resolve ConstantExpr?

### ISSUE THREAD

**Issue by dbwodlf3** [numba/llvmlite#656]
I have instruction like below.
and i get it by 'llvmlite.binding.parse_assembly' and that instruction represented by llvmlite.binding.ValueRef
```llvm
store i8* getelementptr inbounds (i8, i8* bitcast (i32 ()* @main to i8*), i64 107), i8** %1, align 8
```

```python
# this print
# store i8* getelementptr inbounds (i8, i8* bitcast (i32 ()* @main to i8*), i64 107), i8** %1, align 8
print(instruction)

# Error Log ' raise ValueError('expected block value, got %s' % (self._kind,)) ' 
for operand in instruction.operands:
    operand.operands
```

There are any way to get ConstantExpr operands?
or get from ll file?

**Comment by gmarkall** [comment]
Are you looking to get the operands of the `getelementptr` instruction (i.e. the pointer operand and indices)? If so, I'm not sure if there's a way implemented in llvmlite to get them at present.

cc @stuartarchibald for thoughts.

**Comment by stuartarchibald** [comment]
I don't think there's anything to obtain that explicitly.
Example:
```python
from llvmlite import binding as llvm

llvm_ir = """
   ; ModuleID = "foo"
   target triple = "unknown-unknown-unknown"
   target datalayout = ""

   define i32 @main() {
        %1 = alloca i32, align 4
        %2 = alloca [1 x double], align 8
        store i32 0, i32* %1, align 4
        %3 = getelementptr inbounds [1 x double], [1 x double]* %2, i64 0, i64 0
        %4 = load double, double* %3, align 8
        ret i32 0
    }
   """

mod = llvm.parse_assembly(llvm_ir)
func = [x for x in  mod.functions][0]

print(func)
for blk in func.blocks:
    for inst in blk.instructions:
        print('=' * 80)
        print(inst)
        ops = [x for x in inst.operands]
        [print('-- index={}: ops={}'.format(ix, str(x))) for ix, x in enumerate(ops)]
```
gives:
```
define i32 @main() {
  %1 = alloca i32, align 4
  %2 = alloca [1 x double], align 8
  store i32 0, i32* %1, align 4
  %3 = getelementptr inbounds [1 x double], [1 x double]* %2, i64 0, i64 0
  %4 = load double, double* %3, align 8
  ret i32 0
}

================================================================================
  %1 = alloca i32, align 4
-- index=0: ops=i32 1
================================================================================
  %2 = alloca [1 x double], align 8
-- index=0: ops=i32 1
================================================================================
  store i32 0, i32* %1, align 4
-- index=0: ops=i32 0
-- index=1: ops=  %1 = alloca i32, align 4
================================================================================
  %3 = getelementptr inbounds [1 x double], [1 x double]* %2, i64 0, i64 0
-- index=0: ops=  %2 = alloca [1 x double], align 8
-- index=1: ops=i64 0
-- index=2: ops=i64 0
================================================================================
  %4 = load double, double* %3, align 8
-- index=0: ops=  %3 = getelementptr inbounds [1 x double], [1 x double]* %2, i64 0, i64 0
================================================================================
  ret i32 0
-- index=0: ops=i32 0
```
I don't think there's anything further available than what is present in the above.

**Comment by dbwodlf3** [comment]
you means now llvmlite, ValueRef class not yet can't express ConstantExpr?

actually, i saw some code. they use llvmpy.
but now i am not know well about ffi and llvm... if i have some idea then i will make some pr..(maybe future...)
if there are some docs or code about ffi and binding llvm, can i see?

thanks.

**Comment by gmarkall** [comment]
As a pointer for where to start looking, if you want to try to augment llvmlite to provide the information you're looking for: the functionality for getting the functions, instructions, operands, etc. is implemented in [ffi/value.cpp](https://github.com/numba/llvmlite/blob/master/ffi/value.cpp) and [llvmlite/binding/value.py](https://github.com/numba/llvmlite/blob/master/llvmlite/binding/value.py#L77) (in the `ValueRef` class) - you could add additional functions that provide access to other LLVM functions (such as `GetElementPtrInst.getPointerOperand` for example, if that's what you're looking for) to these files by taking inspiration from the functions that already exist there.

llvmpy is very old and unsupported as far as I know - I would suggest that using it wouldn't be easy or sustainable.

**Comment by dbwodlf3** [comment]
Thanks kindly developers.
