### ISSUE TITLE
Error numba 

### ISSUE THREAD

**Issue by zabbix-byte** [numba/llvmlite#657]
Wen i import numba i have this error,

OSError: Could not load shared object file: llvmlite.dll

**Comment by esc** [comment]
@zabbix-byte hi and thank you for opening this issue on the Numba issue tracker. Can you provide more information about your operating system and how you installed Numba? Thanks!

**Comment by zabbix-byte** [comment]
I solved i put another version of numpy and works

**Comment by esc** [comment]
@zabbix-byte ok, thanks for reporting back.
