### ISSUE TITLE
LLVM3.6 jenkins build requires XZ but it is not available on windows build machines

### ISSUE THREAD

**Issue by sklam** [numba/llvmlite#66]
https://github.com/numba/llvmlite/blob/llvm3.6/conda-recipes/llvmdev-jenkins/meta.yaml#L7-L8

**Comment by pitrou** [comment]
Shouldn't that be reported to the admins of the Jenkins machines?

**Comment by seibert** [comment]
That might be us (effectively).

**Comment by sklam** [comment]
originally, I made the llvm-mirror just to workaround this

**Comment by pitrou** [comment]
I would rather avoid maintaining a separate mirror.

**Comment by pitrou** [comment]
Note that using a Python 3-based conda would solve the xz issue (Python 3 bundles the lzma library and doesn't need a separate command-line executable).

**Comment by seibert** [comment]
Are we installing a new miniconda for each build in jenkins now?  If so, it should be pretty easy to switch to miniconda3.

**Comment by pitrou** [comment]
Not according to the jenkins configuration (for llvmlite), but I might have missed something.

**Comment by seibert** [comment]
OK, I think @sklam might have only updated the build process for Numba, then.  We should copy that same pattern over to llvmlite, as it should be much more repeatable.

**Comment by sklam** [comment]
I will try to update the build process for llvmlite

**Comment by pitrou** [comment]
Seems like this is fixed :)
