### ISSUE TITLE
OSError: Could not load shared object file: llvmlite.dll (Version 0.35.0 on win32 Python 3.7)

### ISSUE THREAD

**Issue by pearu** [numba/llvmlite#663]
Raised in https://ci.appveyor.com/project/pearu/rbc-mnh7b/builds/36612298

Notice that https://pypi.org/simple/llvmlite/ does not contain llvmlite-0.35.0-cp37-cp37-win32.whl and hence the llvmlite tar-ball is used under Win32. Could the error be due to the lack of llvmlite wheel for Win32 Python 3.7?

**Comment by pearu** [comment]
Confirming that the issue exists with numba 0.52 and llvmlite 0.35 but not with numba 0.51 and llvmlite 0.34.

**Comment by stuartarchibald** [comment]
@pearu does this fix it https://github.com/numba/llvmlite/issues/660#issuecomment-736522162 ?

**Comment by stuartarchibald** [comment]
Could be some failed uploads for wheels, will take a look.

**Comment by stuartarchibald** [comment]
Think @esc has just fixed it.

**Comment by pearu** [comment]
Thanks, @stuartarchibald @esc ! I confirm that the issue is fixed.

**Comment by stuartarchibald** [comment]
Great, thanks for confirming.
