### ISSUE TITLE
missing python 3.8 wheel llvmlite-0.35.0 for windows x86_64 on pypi

### ISSUE THREAD

**Issue by mpavlase** [numba/llvmlite#664]
llvmlite version 0.35.0 has no build for 64bit Python 3.8 installation (only 32bit) on pypi.

**Comment by stuartarchibald** [comment]
Thanks for the report. Should be there now https://pypi.org/simple/llvmlite/, the builds don't all appear at once!

**Comment by mpavlase** [comment]
That was so fast, thanks! 🚀

**Comment by stuartarchibald** [comment]
No problem, thanks for confirming.
