### ISSUE TITLE
Build llvmdev from source for development

### ISSUE THREAD

**Issue by abebeos** [numba/llvmlite#681]
Setting up llvmlite for source-code development is trivial.

But I struggle a bit to create a source-code-dev version of llvmdev.

What is the suggested method to work on llvmdev source-code inside a conda evn?

**Comment by esc** [comment]
@abebeos thank you for asking about this on the llvmlite issue tracker. I usually use the conda recpie found here:

https://github.com/numba/llvmlite/tree/master/conda-recipes/llvmdev

to build `llvmdev`. If I need to make changes to the llvm tree itself, I will create an appropriate patch and add it to the recipe for processing like so:

https://github.com/numba/llvmlite/blob/master/conda-recipes/llvmdev/meta.yaml#L28-L50

Hope this helps?

**Comment by abebeos** [comment]
yes, I ended up doing it like you describe.

All good!

**Comment by esc** [comment]
@abebeos thank you for reporting back and closing this issue. Happy you managed to get it to work.
