### ISSUE TITLE
fail to install on MacOS Catalina

### ISSUE THREAD

**Issue by lfnoise** [numba/llvmlite#692]
I am trying to install in a virtual environment in PyCharm on MacOS 10.15.7 with LLVM 10.0.1 installed.
#include_next <stdlib.h>  is unable to find the next stdlib.h, and also for #include_next <string.h>
I am fairly new to Python, so I am likely doing something wrong.
I downloaded LLVM 10.0.1, xattr -d -r com.apple.quarantine *, ditto to /usr/local. When that build failed as below, I thought, well maybe it needs to be in the virtual env, so I dittoed into the virtual env. That didn't work either and gives the paths below. The /usr/local build failed in the same way as below but with the /usr/local paths.
 
> pip install llvmlite
Collecting llvmlite
  Using cached llvmlite-0.35.0.tar.gz (121 kB)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f2/60_p_n308xlc8w006s6p4sc00000gn/T/pip-install-xa59akly/llvmlite_44ed2899bcce41a3aa00dfd0f96337af/setup.py'"'"'; __file__='"'"'/private/var/folders/f2/60_p_n308xlc8w006s6p4sc00000gn/T/pip-install-xa59akly/llvmlite_44ed2899bcce41a3aa00dfd0f96337af/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/f2/60_p_n308xlc8w006s6p4sc00000gn/T/pip-wheel-pvoiwv4d
       cwd: /private/var/folders/f2/60_p_n308xlc8w006s6p4sc00000gn/T/pip-install-xa59akly/llvmlite_44ed2899bcce41a3aa00dfd0f96337af/
  Complete output (166 lines):
  running bdist_wheel
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/python /private/var/folders/f2/60_p_n308xlc8w006s6p4sc00000gn/T/pip-install-xa59akly/llvmlite_44ed2899bcce41a3aa00dfd0f96337af/ffi/build.py
  LLVM version... MACOSX_DEPLOYMENT_TARGET=10.15 clang++ -std=c++11 -stdlib=libc++ -dynamiclib -I/Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include -std=c++14 -fno-exceptions -fno-rtti -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -g assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp object_file.cpp custom_passes.cpp -o libllvmlite.dylib  -L/Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lLLVMXRay -lLLVMWindowsManifest -lLLVMTableGen -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMOrcJIT -lLLVMOrcError -lLLVMJITLink -lLLVMObjectYAML -lLLVMMCA -lLLVMLTO -lLLVMObjCARCOpts -lLLVMExtensions -lPolly -lPollyISL -lLLVMPasses -lLLVMLineEditor -lLLVMLibDriver -lLLVMInterpreter -lLLVMFuzzMutate -lLLVMFrontendOpenMP -lLLVMMCJIT -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMDWARFLinker -lLLVMDlltoolDriver -lLLVMOption -lLLVMDebugInfoGSYM -lLLVMCoverage -lLLVMCoroutines -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMX86Desc -lLLVMX86Utils -lLLVMX86Info -lLLVMWebAssemblyDisassembler -lLLVMWebAssemblyCodeGen -lLLVMWebAssemblyDesc -lLLVMWebAssemblyAsmParser -lLLVMWebAssemblyInfo -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMRISCVDisassembler -lLLVMRISCVCodeGen -lLLVMRISCVAsmParser -lLLVMRISCVDesc -lLLVMRISCVUtils -lLLVMRISCVInfo -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMMSP430Disassembler -lLLVMMSP430CodeGen -lLLVMMSP430AsmParser -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFCodeGen -lLLVMBPFAsmParser -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMUtils -lLLVMARMInfo -lLLVMAMDGPUDisassembler -lLLVMAMDGPUCodeGen -lLLVMMIRParser -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUUtils -lLLVMAMDGPUInfo -lLLVMAArch64Disassembler -lLLVMMCDisassembler -lLLVMAArch64CodeGen -lLLVMCFGuard -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMDebugInfoDWARF -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMTextAPI -lLLVMBitReader -lLLVMCore -lLLVMRemarks -lLLVMBitstreamReader -lLLVMAArch64AsmParser -lLLVMMCParser -lLLVMAArch64Desc -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBinaryFormat -lLLVMAArch64Utils -lLLVMAArch64Info -lLLVMSupport -lLLVMDemangle -lz -lcurses -lm -lxml2
  In file included from assembly.cpp:1:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm/IR/LLVMContext.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from bitcode.cpp:1:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/BitReader.h:23:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from core.cpp:1:
  In file included from ./core.h:4:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Core.h:20:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from initfini.cpp:1:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Core.h:20:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from module.cpp:1:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/string:504:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/string_view:175:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/__string:57:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/algorithm:641:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cstring:60:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
  #include_next <string.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from value.cpp:1:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/string:504:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/string_view:175:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/__string:57:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/algorithm:641:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cstring:60:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
  #include_next <string.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from executionengine.cpp:1:
  In file included from ./core.h:4:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Core.h:20:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from transforms.cpp:1:
  In file included from ./core.h:4:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Core.h:20:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from passmanagers.cpp:1:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/tuple:152:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/__functional_base:15:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/typeinfo:60:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/exception:81:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cstdlib:85:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:97:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from targets.cpp:1:
  In file included from ./core.h:4:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Core.h:20:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from dylib.cpp:1:
  In file included from ./core.h:4:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Core.h:20:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from linker.cpp:1:
  In file included from ./core.h:4:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Core.h:20:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from object_file.cpp:1:
  In file included from ./core.h:4:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Core.h:20:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  In file included from custom_passes.cpp:2:
  In file included from ./core.h:4:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Core.h:20:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/Types.h:17:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/include/llvm-c/DataTypes.h:28:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/cmath:304:
  In file included from /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/math.h:301:
  /Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
  #include_next <stdlib.h>
                ^~~~~~~~~~
  1 error generated.
  make: *** [all] Error 1
  10.0.1
  
  SVML not detected
  Traceback (most recent call last):
    File "/private/var/folders/f2/60_p_n308xlc8w006s6p4sc00000gn/T/pip-install-xa59akly/llvmlite_44ed2899bcce41a3aa00dfd0f96337af/ffi/build.py", line 191, in <module>
      main()
    File "/private/var/folders/f2/60_p_n308xlc8w006s6p4sc00000gn/T/pip-install-xa59akly/llvmlite_44ed2899bcce41a3aa00dfd0f96337af/ffi/build.py", line 185, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/f2/60_p_n308xlc8w006s6p4sc00000gn/T/pip-install-xa59akly/llvmlite_44ed2899bcce41a3aa00dfd0f96337af/ffi/build.py", line 173, in main_posix
      subprocess.check_call(['make', '-f', makefile])
    File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.osx']' returned non-zero exit status 2.
  error: command '/Users/jamesmcc/PycharmProjects/sapf_in_python_exploratory/venv/bin/python' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite

Then it goes on to print the same error messages for setup.py.

**Comment by seibert** [comment]
Normally pip will install precompiled llvmlite wheels which we upload to PyPI, so you would not need to do any of this.  However, digging through the error message, I see that you are using Python 3.9.   We haven't uploaded Python 3.9 wheels for llvmlite or Numba yet because the current release of Numba doesn't support Python 3.9.  That work was just finished in the unreleased, development version of Numba.

Can you use Python 3.8 for now?  That will allow you to use the precompiled wheels, and you will not need to build llvmlite yourself.

**Comment by lfnoise** [comment]
Yes, that works. Thanks.
