### ISSUE TITLE
pip3 install llvmlite fails

### ISSUE THREAD

**Issue by GBR-613** [numba/llvmlite#697]
The command "pip3 install llvmlite" fails with the message below.

Reproduced with Ubuntu 18.04, RHEL-based Amazon2 VM, python v 3.6, 3.7 and 3.9
For my surprise, it does work with python 3.8

Please notice, looking for the error message gets a very large set of complains on such the problem during last couple of years. The recommendations are "try to re-install python package X", "try to re-install system package Y" or simply "wait for next version".

Since currently the install works with at least on one supported version of Python, you may claim that this is pip or pipy.org issue. However I believe the issue should be fixed once and forever into llvmlite package itself by making sure the installing version is compatible with installed respective pre-requisites. In such the way Python packages behave.

---
The  error message:

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uvy03y4f/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uvy03y4f/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-orvkf_4s/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.9/llvmlite
         cwd: /tmp/pip-install-uvy03y4f/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-uvy03y4f/llvmlite/llvmlite/_version.py {'version': '0.35.0', 'full': 'ea23b026930cc00824c907172383f54c9d438e6b'}
    running build_ext
    /usr/bin/python /tmp/pip-install-uvy03y4f/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-uvy03y4f/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/local/lib/python3.9/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/local/lib/python3.9/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/lib/python3.9/subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/lib/python3.9/subprocess.py", line 1819, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-uvy03y4f/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-uvy03y4f/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-uvy03y4f/llvmlite/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uvy03y4f/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uvy03y4f/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-orvkf_4s/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.9/llvmlite Check the logs for full command output.

**Comment by esc** [comment]
@GBR-613 thank you for reporting this. I understand your frustration with this issue of not being able to install llvmlite. Unfortunately for llvmlite, this is an exceptionally difficult problem to solve -- as you can tell by all the open issues -- and we welcome any ideas or suggestions you may have in this direction. Regarding the stack trace above, the latest release at the time of writing doesn't support 3.9 so that stack trace is expected. A new version that does support 3.9 is currently in the process of being released and should be available soon. However,  I am surprised that 3.6 and 3.7 failed to install. May I kindly request that you supply the stack traces for these two versions too, so that we may have a look at them? Thank you.

**Comment by esc** [comment]
It may also be worth while to try the `*.whl` file directly for 3.6 and 3.7 -- you can find the files for all supported platforms on PyPi here:

https://pypi.org/project/llvmlite/0.35.0/#files

**Comment by GBR-613** [comment]
@esc This is the stack trace for python 3.6. looking glance i don't observe any difference with 3.9, except versions references, of course.

$ python -V
Python 3.6.9
$ pip -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
$ pip install llvmlite
Collecting llvmlite
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/cd/3e/631087324bd3ffaf9a9c1c9d7d6675863e41afb31c818dd700019193e6b4/llvmlite-0.35.0.tar.gz (121kB)
    100% |████████████████████████████████| 122kB 9.2MB/s 
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tc0a9lip/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmphlze2uh1pip-wheel- --python-tag cp36:
  running bdist_wheel
  /usr/bin/python /tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.6/subprocess.py", line 423, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
  
  During handling of the above exception, another exception occurred:
    
  Traceback (most recent call last):
    File "/tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py", line 108, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tc0a9lip/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-w12eld_8-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    got version from file /tmp/pip-build-tc0a9lip/llvmlite/llvmlite/_version.py {'version': '0.35.0', 'full': 'ea23b026930cc00824c907172383f54c9d438e6b'}
    running build_ext
    /usr/bin/python /tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
    
    During handling of the above exception, another exception occurred:
        
    Traceback (most recent call last):
      File "/tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-tc0a9lip/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tc0a9lip/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-w12eld_8-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-tc0a9lip/llvmlite/

**Comment by GBR-613** [comment]
@esc Since I am using Python 3.6. on 64-bit Linux, I believe the version I need is llvmlite-0.35.0-cp36-cp36m-manylinux2010_x86_64.whl, correct?
It fails with message "... is not a supported wheel on this platform". 
And so 32-bit does too.

The system is Ubuntu 18.04 VM on AWS. May the problem be platform-specific?  I don't believe, but I will try to set up this version of Ubuntu on another platform and will tell you the result.

**Comment by GBR-613** [comment]
@esc The same occurs in Ubuntu 18.04 VM with Python 3.6 on Oracle Virtual Box.

**Comment by esc** [comment]
@GBR-613 thank you for following up on this. I believe your `pip` is too old. The `llvmlite` wheels follow the `manylinux2010` standard and you need at least `pip` 19.0 to use these wheels https://pip.pypa.io/en/stable/news/#id448 -- try updating your pip and see if that helps.

The problem you are seeing is because `pip` is unable to resolve correctly the binary wheels needed for `llvmlite` so instead you end up getting a source distribution instead. `pip` then attempts to compile this source distribution and so you end up with the error message above. Granted, the message is aimed at developers trying to compile `llvmlite` from scratch so not helpful for regular users. The next thing we should probably do, is replace that error message with a link to our documentation describing this situation and what can be done about it.

**Comment by esc** [comment]
@GBR-613 PS: 3.9 is now also supported by a release candidate, in case you wish to "take that for a spin": https://numba.discourse.group/t/numba-0-53-0-and-llvmlite-0-36-0-release-candidates/504

**Comment by GBR-613** [comment]
@esc You are right: after upgrading pip to 21.0.1 llvmlite is successfully installed with Python 3.6 (also directly from pypi.org, without necessity to download the whl file).
However I still believe there is an issue: if llvmlite is sensitive to versions of Python and pip, then respective checking should be injected to its installation mechanism. In such the way Python packages do.

**Comment by esc** [comment]
@GBR-613 thank you for reporting back about this. I will close this issue now as I believe it is resolved. Thank you for using Numba.

**Comment by esc** [comment]
@GBR-613 thank you again for your suggestions regarding improving the situation regarding dependencies and error messages, I have opened a new thread for discussion here: https://numba.discourse.group/t/fixing-filenotfounderror-errno-2-no-such-file-or-directory-llvm-config/510 -- please feel free to join in, if you wish.

**Comment by esc** [comment]
FYI: #701 was merged; that improves the handling of the `llvm-config not found` error messsag.

**Comment by codearpit07** [comment]
try sudo apt-get install llvm, and then retry the llvmlite package installation

**Comment by VishnuPonnusamy** [comment]
Hey guys i tried to uninstall the llvmlite in my system but can't able to do it so i tried to update instead but this was the log i got

PS C:\HIA\OSWorld> pip install --upgrade llvmlite
>>
Requirement already satisfied: llvmlite in c:\users\vishnu ponnusamy\anaconda3\lib\site-packages (0.39.1)
Collecting llvmlite
  Using cached llvmlite-0.42.0-cp310-cp310-win_amd64.whl.metadata (4.9 kB)
Using cached llvmlite-0.42.0-cp310-cp310-win_amd64.whl (28.1 MB)
Installing collected packages: llvmlite
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.39.1
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
