### ISSUE TITLE
Installation does not check pre-requisites

### ISSUE THREAD

**Issue by GBR-613** [numba/llvmlite#698]
About a week ago I tried to install llvmlite using pip, and the installation failed with a red herring message. The real root of the problem was that I used Python v3.9.1 for which the package was not still available.  (I suppose now it may be, and the problem is temporarily not reproduceable.)  

If versions of llvmlite are specific per Python's version, then the installation code should check whether the used version is supported. In such the way Python packages work.

I suppose checking of other pre-requisites may matter too.

**Comment by gmarkall** [comment]
Hi @GBR-613 - many thanks for reporting this issue. Do you have a copy of the error message that you received?

**Comment by GBR-613** [comment]
@gmarkall Yes, I opened issue #697 about it.
The misleading message is an issue itself:
But lack of checking of Python version (at least) is separate issue, too.

**Comment by esc** [comment]
This is probably quite easy to solve by adapting the following from Numba:

https://github.com/numba/numba/blob/master/setup.py#L34
https://github.com/numba/numba/blob/master/setup.py#L411

We should probably get this into 0.36.0RC2, it seems easy enough to fix.

(I do recall, however, that when we did this for Numba, it was not effective, as previous releases did not have this limitation included and therefore `pip` choose to select a previous release instead and again yield a potentially misleading error messages. Having said that, we should do this anyway, and cross any future bridged when we get to them. Probably when Python 3.10 is released later on in the year.)

**Comment by esc** [comment]
I have made a corresponding PR here: https://github.com/numba/llvmlite/pull/699

**Comment by esc** [comment]
#699 is now merged, so we can close this. We will see if it helps when Python 3.10 comes out in autumn.
