### ISSUE TITLE
"No such file or directory: 'llvm-config': 'llvm-config'" on Raspberry Pi 4

### ISSUE THREAD

**Issue by texadactyl** [numba/llvmlite#700]
My Raspberry Pi 4 installation with up-to-date O/S:

----- Ubuntu release -----
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
----- OS kernel name/release/version -----
5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021
----- Machine hardware platform -----
armv7l

python3 -m pip list | grep pip
pip               21.0.1

When I try this

```python3 -m pip install -U llvmlite```

then I see this:

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting llvmlite
  Using cached llvmlite-0.35.0.tar.gz (121 kB)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h_ejx14p/llvmlite_f81d081f17f548888ae1dfb6f70dd790/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h_ejx14p/llvmlite_f81d081f17f548888ae1dfb6f70dd790/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-b40b1xv3
       cwd: /tmp/pip-install-h_ejx14p/llvmlite_f81d081f17f548888ae1dfb6f70dd790/
  Complete output (26 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-h_ejx14p/llvmlite_f81d081f17f548888ae1dfb6f70dd790/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-h_ejx14p/llvmlite_f81d081f17f548888ae1dfb6f70dd790/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
```

I have seen this precise symptom before in x64 installations when ```pip``` was out of date.

Any idea what is going wrong?
Need anything else from me?

**Comment by esc** [comment]
@texadactyl thank you for asking about this. In this case `pip` is unable to find a valid binary wheel for your platform because we don't produce them (yet). To get a binary package up and running on Raspberry PIs, we do recommend a 64 bit OS (aarch64) and a miniforge installation with conda instead of `pip`.

**Comment by texadactyl** [comment]
@esc  Thanks.  The aarch64 OS, I can do but using conda or Anaconda or a derivative is a non-starter.  I am constrained to use pip for some packages developed by a science organization.  I have learned the hard way that mixing conda and pip is like gasoline and water.  )-:  Yes, we can limit the damage by attempting to pip install in a special conda environment but scientists are not very patient!

**Comment by esc** [comment]
@texadactyl thank you for following up on this. For what it is worth: work to bring binary, pip-installable wheels to the `aarch64` platform has been scheduled for the next llvmlite release.

**Comment by texadactyl** [comment]
Verified work-around for installing llvmlite on Raspberry Pi 4:
```
sudo apt install llvm-9`
LLVM_CONFIG=llvm-config-9 pip install llvmlite`
```

BUT it would be helpful to fix this permanently with a pre-built wheel.

**Comment by esc** [comment]
@texadactyl thank you for re-opening this. There is an issue tracking aarch64 wheel support here: #665 -- please subscribe to that issue to be notified as to when the wheel support will be enabled.

Also, I am doubtful that using the system provided llvm package is a good and stable solution or even a workaround we should be recommending. See also: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#what-to-be-aware-of-when-using-a-system-provided-llvm-package

Question: can we close this issue again, since it doesn't appear to be tracking any specific issue at present, or did I miss something?

**Comment by texadactyl** [comment]
@esc 

Thanks for the reference.  Subscription done.  I have alerted the other members of the Seti Institute about the Mac M1 (also aarch64) issue.  Someone has already found a work-around for MacOS which looks very similar to the one that I mentioned here.

**Comment by esc** [comment]
> @esc
> 
> Thanks for the reference. Subscription done. I have alerted the other members of the Seti Institute about the Mac M1 (also aarch64) issue. Someone has already found a work-around for MacOS which looks very similar to the one that I mentioned here.

Excellent, thank you. I hope to complete the `aarch64` wheel issue within the next month or so.
