### ISSUE TITLE
PyPI sdist for llvmlite 0.36.0

### ISSUE THREAD

**Issue by jakirkham** [numba/llvmlite#708]
Guessing we are waiting on some build pipeline in the background to upload things to PyPI, but wanted to mention here just in case. It would be good to have the sdist uploaded for `0.36.0`. This is needed to build out this package in conda-forge

**Comment by esc** [comment]
@jakirkham yes there is a delay, as usual about 24 hours, between tagging the release on Github and the build artifacts becoming available. As for the sdist, this needs to be uploaded after the wheels have been uploaded to ensure that nobody downloads the llvmlite sdist unintentionally.

**Comment by jakirkham** [comment]
Yep that all makes sense. Will look for it tomorrow. Thanks! 😄

**Comment by esc** [comment]
@jakirkham it's all uploaded now: https://pypi.org/project/llvmlite/0.36.0/#files

**Comment by jakirkham** [comment]
Thanks Valentin! 😀

**Comment by esc** [comment]
@jakirkham no problem sir! Thank you for maintain the conda-forge buildout!!

**Comment by jakirkham** [comment]
Just built `llvmlite` ( https://github.com/conda-forge/llvmlite-feedstock/pull/53 ) 🎉 Waiting for it to mirror to CDN and then we can build Numba 😄
