### ISSUE TITLE
patchin issue 

### ISSUE THREAD

**Issue by MyraBaba** [numba/llvmlite#713]
Hi,

I am trying to compile numba on JetsonTX2 with versions:

LLVM        : 7.0.1
llvm-lite.  : v0.32

when I try to pathc:
` patch -p1 -i ../llvmlite-0.32.0/conda-recipes/llvm-lto-static.patch 
can't find file to patch at input line 10
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|LTO is the only shared library built by LLVM.  It breaks llvmlite
|builds under Windows with the following message:
|
|LINK : fatal error LNK1181: cannot open input file 'LTO-NOTFOUND.obj'
|
|diff --git a/tools/lto/CMakeLists.txt b/tools/lto/CMakeLists.txt
|index 6e91351..66bea35 100644
|--- a/tools/lto/CMakeLists.txt
|+++ b/tools/lto/CMakeLists.txt
--------------------------
File to patch: 
`

gives above message. Soemthing looks not working.

What is the exact version for compiling numba from source ?

LLVM.    version: ?
llvmlite   version: ?  
numba.   version: ?

some reason we need to use PIP . No conda 

Best

**Comment by esc** [comment]
@MyraBaba thank you for reporting this. I am unable to reproduce this on fresh downloads/clones and it appears to work as advertised:

```
zsh» git status
HEAD detached at v0.32.0
nothing to commit, working tree clean
zsh» cd ../llvm-7.0.0.src
zsh» patch -p1 -i ../llvmlite/conda-recipes/llvm-lto-static.patch
patching file tools/lto/CMakeLists.txt
```

I would suggest to double check:

* Where you execute `patch` from
* Which version of LLVM you downloaded
* Which version of llvmlite you cloned

**Comment by esc** [comment]
PS: current latest version of Numba -- 0.53.1 -- and llvmlite -- 0.36.0 -- can be used with LLVM 9.0 on `aarch64`.

**Comment by MyraBaba** [comment]
I will try with Numba -- 0.53.1 -- and llvmlite -- 0.36.0 -- can be used with LLVM 9.0  and let you know.

Best

**Comment by MyraBaba** [comment]
This is what happened :



bctegra@Tegrabc:~/Downloads/llvm-project-llvmorg-9.0.0$ patch -p1 -i ../llvmlite-0.36.0/conda-recipes/llvm-lto-static.patch 
can't find file to patch at input line 18
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 256ad97f332010ab6673052fe4e562e5ed2dadd2 Mon Sep 17 00:00:00 2001
|From: Siu Kwan Lam ***@***.***>
|Date: Mon, 3 Feb 2020 14:44:54 -0600
|Subject: [PATCH] Update LTO patch
|
|LTO is the only shared library built by LLVM.  It breaks llvmlite
|builds under Windows with the following message:
|
|LINK : fatal error LNK1181: cannot open input file 'LTO-NOTFOUND.obj'
|---
| tools/lto/CMakeLists.txt | 2 +-
| 1 file changed, 1 insertion(+), 1 deletion(-)
|
|diff --git a/tools/lto/CMakeLists.txt b/tools/lto/CMakeLists.txt
|index b86e4ab..88e5ba0 100644
|--- a/tools/lto/CMakeLists.txt
|+++ b/tools/lto/CMakeLists.txt
--------------------------
File to patch:

**Comment by esc** [comment]
@MyraBaba I am not sure how to help you. This is what happens on my end:

```
$ cd /tmp
$ git clone git@github.com:numba/llvmlite.git
...
$ cd llvmlite
$ git co v0.36.0
Previous HEAD position was 26059d238f Merge pull request #576 from stuartarchibald/doc/update_release_date_032_on_rel_branch
HEAD is now at e6bb8d137d Merge pull request #706 from sklam/misc/rel0.36.0final
$ cd ..
$ wget https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/llvm-9.0.1.src.tar.xz
...
$ tar -xvJf llvm-9.0.1.src.tar.xz
...
$ cd llvm-9.0.1.src
$ patch -p1 -i ../llvmlite/conda-recipes/llvm-lto-static.patch00
patching file tools/lto/CMakeLists.txt
```

Can you execute the above commands verbatim and post the output if it doesn't work? Also, I would suggest to take a look at:
https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf to learn more about the Markdown syntax used on Github. For example, fenced code-blocks can be created by enclosing the text in tripple backticks.

**Comment by MyraBaba** [comment]
Hi @esc 

I can not manage install the latest numba with the llvmlite + llvm9.01 . Even cant compile LLVM and some patch not work .

I would love to install latest numba to my JetsonTX2 but cant.

I manage the install 

```
>>> import numba
>>> numba.__version__
'0.45.1-py3.7-linux-aarch64.egg'
>>> 
```

I hope this one has not less performant than the latest.



'''bctegra@Tegrabc:~/NMB/llvm-9.0.1.src$ patch -p1 -i ../llvmlite/conda-recipes/expect-fastmath-entrypoints-in-add-TLI-mappings.ll.patch 
can't find file to patch at input line 24
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From b4e228f9b382c8fd6c932a4606e4ad436050c19b Mon Sep 17 00:00:00 2001
|From: Tim Snyder <snyder.tim@gmail.com>
|Date: Fri, 3 Apr 2020 11:10:00 -0500
|Subject: [PATCH] expect fastmath entrypoints in  add-TLI-mappings.ll
|
|with adjusted intel-D47188-svml-VF.patch that compiles, one of the
|new tests in LLVM 10.0.0 fails because it expects SVML function
|entrypoints that do not use the 'fastmath' '_ha' suffix.  However,
|the beforementioned patch causes 'fastmath' entrypoints to be used
|in this test.
|
|Modifying the new test seems correct to me but I'm leaving it as a
|separate patch so that it is easier for others to observe the failure
|and notice this fundamentally new patch we need to make for 10.0.0
|and beyond.
|---
| test/Transforms/Util/add-TLI-mappings.ll | 14 +++++++-------
| 1 file changed, 7 insertions(+), 7 deletions(-)
|
|diff --git a/test/Transforms/Util/add-TLI-mappings.ll b/test/Transforms/Util/add-TLI-mappings.ll
|index c68a9c9a7..c63637294 100644
|--- a/test/Transforms/Util/add-TLI-mappings.ll
|+++ b/test/Transforms/Util/add-TLI-mappings.ll
--------------------------
File to patch: ^C
'''


'''[ 55%] Building CXX object lib/Transforms/Scalar/CMakeFiles/LLVMScalarOpts.dir/LoopVersioningLICM.cpp.o
cd /home/bctegra/NMB/llvm-9.0.1.src/build/lib/Transforms/Scalar && /usr/bin/c++ -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/bctegra/NMB/llvm-9.0.1.src/build/lib/Transforms/Scalar -I/home/bctegra/NMB/llvm-9.0.1.src/lib/Transforms/Scalar -I/home/bctegra/NMB/llvm-9.0.1.src/build/include -I/home/bctegra/NMB/llvm-9.0.1.src/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O3    -UNDEBUG  -fno-exceptions -fno-rtti -MD -MT lib/Transforms/Scalar/CMakeFiles/LLVMScalarOpts.dir/LoopVersioningLICM.cpp.o -MF CMakeFiles/LLVMScalarOpts.dir/LoopVersioningLICM.cpp.o.d -o CMakeFiles/LLVMScalarOpts.dir/LoopVersioningLICM.cpp.o -c /home/bctegra/NMB/llvm-9.0.1.src/lib/Transforms/Scalar/LoopVersioningLICM.cpp
/home/bctegra/NMB/llvm-9.0.1.src/lib/Transforms/Vectorize/LoopVectorize.cpp: In member function ‘void llvm::InnerLoopVectorizer::widenInstruction(llvm::Instruction&)’:
/home/bctegra/NMB/llvm-9.0.1.src/lib/Transforms/Vectorize/LoopVectorize.cpp:4164:66: error: no matching function for call to ‘llvm::TargetLibraryInfo::getVectorizedFunction(llvm::StringRef&, unsigned int&) const’
         StringRef VFnName = TLI->getVectorizedFunction(FnName, VF);
                                                     '''




'''[ 37%] Building CXX object lib/Transforms/Vectorize/CMakeFiles/LLVMVectorize.dir/LoopVectorize.cpp.o
/home/bctegra/NMB/llvm-9.0.1.src/lib/Transforms/Vectorize/LoopVectorize.cpp: In member function ‘void llvm::InnerLoopVectorizer::widenInstruction(llvm::Instruction&)’:
/home/bctegra/NMB/llvm-9.0.1.src/lib/Transforms/Vectorize/LoopVectorize.cpp:4164:66: error: no matching function for call to ‘llvm::TargetLibraryInfo::getVectorizedFunction(llvm::StringRef&, unsigned int&) const’
         StringRef VFnName = TLI->getVectorizedFunction(FnName, VF);
                                                                  ^
In file included from /home/bctegra/NMB/llvm-9.0.1.src/include/llvm/Analysis/AliasAnalysis.h:45:0,
                 from /home/bctegra/NMB/llvm-9.0.1.src/include/llvm/Transforms/Vectorize/LoopVectorize.h:59,
                 from /home/bctegra/NMB/llvm-9.0.1.src/lib/Transforms/Vectorize/LoopVectorize.cpp:56:
/home/bctegra/NMB/llvm-9.0.1.src/include/llvm/Analysis/TargetLibraryInfo.h:264:15: note: candidate: std::__cxx11::string llvm::TargetLibraryInfo::getVectorizedFunction(llvm::StringRef, unsigned int, bool&, bool) const
   std::string getVectorizedFunction(StringRef F, unsigned VF, bool &FromSVML,
               ^~~~~~~~~~~~~~~~~~~~~
/home/bctegra/NMB/llvm-9.0.1.src/include/llvm/Analysis/TargetLibraryInfo.h:264:15: note:   candidate expects 4 arguments, 2 provided
lib/Transforms/Vectorize/CMakeFiles/LLVMVectorize.dir/build.make:103: recipe for target 'lib/Transforms/Vectorize/CMakeFiles/LLVMVectorize.dir/LoopVectorize.cpp.o' failed
make[2]: *** [lib/Transforms/Vectorize/CMakeFiles/LLVMVectorize.dir/LoopVectorize.cpp.o] Error 1
CMakeFiles/Makefile2:8179: recipe for target 'lib/Transforms/Vectorize/CMakeFiles/LLVMVectorize.dir/all' failed
make[1]: *** [lib/Transforms/Vectorize/CMakeFiles/LLVMVectorize.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
+ exit 2
'''

**Comment by esc** [comment]
@MyraBaba thanks for updating. Sorry to hear you are struggling to compile the Numba/llvmlite stack. It is a tricky endeavor indeed and can be very challenging at times. However, I am glad that you managed to get something to compile. I should note also, that we hope to get bianry wheels for `aarch64` ready for the next release to support the `aarch64` use-case better. Thank you for using Numba and have a great day!

**Comment by MyraBaba** [comment]
@esc  thanks a lot . 

if its compileable to latest version I will give a shot again.

Best
