### ISSUE TITLE
problem with version 4.1

### ISSUE THREAD

**Issue by fansofzyx** [numba/llvmlite#717]
problem with version 4.1:when I execute /opt/rocm/bin/rocm-smi ,I can't get correct output.
ERROR:
Failed to get "domain" properity from properties files for kfd node 1.
rsmi_init() failed
Exception caught: rsmi_init.
ERROR:root:ROCm SMI returned 8 (the expected value is 0)

**Comment by stuartarchibald** [comment]
Thanks for the report. Can you explain a bit more about what it is you are trying to do? Thanks.

**Comment by esc** [comment]
This issue has received no attention for a while, so I will close it assuming solved. If that is not the case, please do re-open with more information, thank you.
