### ISSUE TITLE
rename master to main

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#722]
Following suit for cpython we should rename `master` to `main`. Probably it makes sense to do this after the next (0.37) release so as leave room to deal with any fallout.

**Comment by gmarkall** [comment]
Is it a good time to do this now?

**Comment by gmarkall** [comment]
(by now, I mean in the early part of 0.38 development, not literally right now :-) )

**Comment by gmarkall** [comment]
(Accidentally closed the issue)

**Comment by esc** [comment]
@gmarkall 

> Is it a good time to do this now?

Yes, I think we had consensus between @seibert @sklam @stuartarchibald and myself to do this after the 0.37.0 FINAL release.

**Comment by esc** [comment]
This was done yesterday as part of #814
