### ISSUE TITLE
Feature request: Provide wheels for PyPy

### ISSUE THREAD

**Issue by gmarkall** [numba/llvmlite#725]
Wheels for CPython are already built and uploaded to PyPI.

This issue is a request for also building wheels for PyPy.

cc @stonebig - what versions of PyPy would you request / suggest wheels should be built for?

xref: #525

**Comment by stonebig** [comment]
The windows 64 bit one for latest official pypy , so pypy3.7-v7.3.5-win64.zip

, if it's possible.

**Comment by stonebig** [comment]
As of now, I would think you would only do it for Pypy3 latest, and  python latest, so  pypy3.9-v7.3.9.
