### ISSUE TITLE
install llvmlite, but get different version

### ISSUE THREAD

**Issue by jasmine202106** [numba/llvmlite#728]
$python -m pip install llvmlite==0.31.0 
Defaulting to user installation because normal site-packages is not writeable
Collecting **_llvmlite==0.31.0_**
  Using cached llvmlite-0.31.0-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
Installing collected packages: llvmlite
Successfully installed **_llvmlite-0.36.0_**
WARNING: You are using pip version 20.3.4; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.
liey@liey-HP-Z840-Workstation:~$ python
Python 3.7.2 (default, Oct 25 2019, 11:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llvmlite
>>> **_llvmlite.__version__
'0.33.0+1.g022ab0f'_**
>>> 

why i install llvmlite0.31.0,but it shows "Successfully installed llvmlite-0.36.0", and from python import llvmlite, it shows llvmlite version is 0.33.0???
how can i install llvmlite0.31.0?

**Comment by jasmine202106** [comment]
python -m pip install -U llvmlite==0.31.0
Defaulting to user installation because normal site-packages is not writeable
Collecting llvmlite==0.31.0
Using cached llvmlite-0.31.0-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
Installing collected packages: llvmlite
Successfully installed llvmlite-0.36.0
WARNING: You are using pip version 20.3.4; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.

python -m pip uninstall llvmlite
Found existing installation: llvmlite 0.33.0+1.g022ab0f
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

python -m pip install -U llvmlite==0.32.1
Defaulting to user installation because normal site-packages is not writeable
Collecting llvmlite==0.32.1
Using cached llvmlite-0.32.1-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
Installing collected packages: llvmlite
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.48.0 requires llvmlite<0.32.0,>=0.31.0dev0, but you have llvmlite 0.32.1 which is incompatible.
Successfully installed llvmlite-0.36.0
WARNING: You are using pip version 20.3.4; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.

it seems i cannot downgrade the llvmlite version. why?

**Comment by esc** [comment]
@jasmine202106 thank you for raising this issue on the Numba issue tracker. I don't think there is much we can do here to help you. I presume this is an issue related to `pip` and I would recommend for you to try to contact the people that develop `pip` with your concerns. Best wishes and good luck!
