### ISSUE TITLE
OSError: Could not load shared object file: llvmlite.dll

### ISSUE THREAD

**Issue by asceking** [numba/llvmlite#729]
(numba version 0.53.1; llvmlite version 0.36.0)
It happens when I import numba, but no error is reported when I just import llvmlite.
My operating system is windows 10, and I installed numba and llvmlite with pip.
I tried re-installing numba and llvmlite, but that didn't work. I also tried using numba with lower version, but when I used numba 0.51 and llvmlite 0.34.0, the problem still occurred.

**Comment by esc** [comment]
@asceking thank you for reporting this. We have had a few reports about issues with the wheels for Windows in the last few weeks. As a workaround, I would suggest to try `conda` if you can and see if the issue persists.

**Comment by asceking** [comment]
Thanks, @etc ! Numba works well after I re-install it with conda.

**Comment by esc** [comment]
> Thanks, @etc ! Numba works well after I re-install it with conda.

Thank you for trying this and confirming!
