### ISSUE TITLE
How can I  install llvmlite in aarch64?

### ISSUE THREAD

**Issue by neverstoplearn** [numba/llvmlite#731]

**Comment by esc** [comment]
@neverstoplearn it depends on what your `aarch64` target is exactly (RaspberryPi, Apple Silicon M1) and if you want to use `pip` or `conda`. But I think you will find some suitable instructions here:

https://numba.readthedocs.io/en/stable/user/installing.html#installing-on-linux-armv8-aarch64-platforms
