### ISSUE TITLE
When will LLVM 12 be supported?

### ISSUE THREAD

**Issue by Tweak-1600** [numba/llvmlite#737]
I hope llvm 12 will be supported

**Comment by Tweak-1600** [comment]
When will llvm 12 be supported?

**Comment by esc** [comment]
@Tweak-1600 thank you for asking about this. We have just recently added LLVM 11 support in #715 -- and there is a ticket at #688 tracking LLVM 12 support. I would realistically expect this to become available within the next 6 to 12 months.
