### ISSUE TITLE
python 3.10 support

### ISSUE THREAD

**Issue by leifwalsh** [numba/llvmlite#740]
llvmlite currently explicitly doesn't support python 3.10. What needs to be done to lift this restriction?

I'm mostly creating this issue so I have something to watch so I can know when it's ready for 3.10, but if there's something you all need help with I'm happy to try.

**Comment by esc** [comment]
@leifwalsh I tried to run llvmlite in a Python 3.10 (beta?) docker container from here: https://hub.docker.com/_/python?tab=description -- IIRC the only thing that needs to be done right now is to remove the restriction on the Python version in setup.py and it will compile and the test suite will run (or there is a minimal amount of trivial patching, can't quite remember). 

The guard is here: https://github.com/numba/llvmlite/blob/master/setup.py#L36

If you are inclined, it would be great for you to confirm my statements above independently. If we can be sure, that no changes are needed in llvmlite for Python 3.10 that would be awesome! Let me know if you need any more pointers or if you hit any snags!

**Comment by gmarkall** [comment]
I think we'd also want to modify the CI setup to include 3.10?

Would we also drop support for 3.6, given that Numba no longer supports it?

**Comment by esc** [comment]
> I think we'd also want to modify the CI setup to include 3.10?

Yes, but I think we will need to wait until a Python 3.10 becomes available as a conda package because all our CI uses that.

> Would we also drop support for 3.6, given that Numba no longer supports it?

Yes, that was an oversight, it should have been removed for v0.37.0 RC1 -- but was missed. It doesn't hurt to include them for now, but yes, 3.6 has to go.

**Comment by bcbnz** [comment]
I've just tested 4ba6f53 with a freshly built copy of Python 3.10.0b3 and did not have to change anything other than the version guard.

I guess the conda support is  conda-forge/python-feedstock#463

**Comment by esc** [comment]
> I've just tested [4ba6f53](https://github.com/numba/llvmlite/commit/4ba6f53ffd39076c487b075345ea9737f309c2d0) with LLVM 11.1.0 and a freshly built copy of Python 3.10.0b3 (on Arch Linux) and did not have to change anything other than the version guard.

Great, thanks for confirming!

> I guess the conda support is [conda-forge/python-feedstock#463](https://github.com/conda-forge/python-feedstock/issues/463)

The **conda-forge** support, yes.

**Comment by leifwalsh** [comment]
3.10 final is out so I think this can move forward whenever your CI is ready to run it, and you're ready to cut a fresh release

**Comment by esc** [comment]
@leifwalsh thank you for the ping. We depend on a Python 3.10 conda package for our internal build system, so it will be some more time until we can conclude this.

**Comment by seibert** [comment]
One thing to note is that while llvmlite would work with Python 3.10 now, Numba does not yet due to bytecode changes.  You'll want to track this PR to know when Numba is ready for Python 3.10 (at which point both Numba and llvmlite can be released together): https://github.com/numba/numba/pull/7381

**Comment by leifwalsh** [comment]
Ooh, thanks, I do want to track that.

**Comment by 2sn** [comment]
@esc  thanks.  Since I use my own Python compiled-from-scratch the dnf version might not work for me.

**Comment by bmerry** [comment]
Should this be closed now that 0.38 supports Python 3.10?

**Comment by esc** [comment]
> Should this be closed now that 0.38 supports Python 3.10?

Yes, thank you for the ping, 0.38 included support for 3.10 so I will close this now.
