### ISSUE TITLE
Install the latest developer version of llvmlite via conda on AArch64

### ISSUE THREAD

**Issue by guoqiangqi** [numba/llvmlite#755]
We can install the latest developer version of llvmlite via conda with simple command `conda install -c numba/label/dev llvmite` on `x86_64`, but the current version on `AArch64` is `llvmlite-0.32.0dev0` which is a much early version, maybe we should update the corresponding packages.

**Comment by esc** [comment]
@guoqiangqi I am not sure what you mean exactly. Looking at anaconda.org:

https://anaconda.org/numba/llvmlite/files?version=0.36.0

The latest aarch64 packages are there?!

Maybe you can supply:

a) What did you try to do?
b) What did you expect to happen?
c) What happened instead?

(including commands and relevant logs or output where appropriate to illustrate the point).

Thank you!

**Comment by guoqiangqi** [comment]
@esc Sorry for not making myself clear. When i install `llvmlite` on `x86_64` machines with `conda install -c numba/label/dev llvmlite`, i can get the latest developer version of llvmlite (`0.38.0dev0` exactly), output of conda as follows:
```
(numbaenv) qiguoqiang@ecs-ba0b:~/huawei/numba$ conda install -c numba/label/dev llvmlite
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/qiguoqiang/conda/envs/numbaenv

  added / updated specs:
    - llvmlite


The following NEW packages will be INSTALLED:

  llvmlite           numba/label/dev/linux-64::llvmlite-0.38.0dev0-py39hf484d3e_0
```
but on Aarch64 machines, the developer version i got was `0.32.0dev0`:
```
(numbaenv) [root@ecs-9d50 huawei]# conda install -c numba/label/dev llvmlite
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/miniconda3/envs/numbaenv

  added / updated specs:
    - llvmlite


The following NEW packages will be INSTALLED:

  llvmlite           numba/label/dev/linux-aarch64::llvmlite-0.32.0dev0-py38_4
```

**Comment by guoqiangqi** [comment]
@esc I can find the ` linux-aarch64/llvmlite-0.38.0dev0-py38hbfd4b83_0.tar.bz2` packages in the list you provided, so it may be that my operating system has small issues on conda support. The operating system I use is OpenEuler. I closed this issue and would notify you if there are new discoveries. Thanks for your quick reply and your patience.

**Comment by esc** [comment]
I am unable to reproduce on a raspberry-pi: 

```
(llvmlite-test02) vhaenel@colo-rpi64-01:~$ conda install -c numba/label/dev llvmlite
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/vhaenel/miniforge3/envs/llvmlite-test02

  added / updated specs:
    - llvmlite


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    llvmlite-0.38.0dev0        |   py39hbfd4b83_0        23.6 MB  numba/label/dev
    ------------------------------------------------------------
                                           Total:        23.6 MB

The following NEW packages will be INSTALLED:

  llvmlite           numba/label/dev/linux-aarch64::llvmlite-0.38.0dev0-py39hbfd4b83_0
```

Do you have more information about what kind of `aarch64` machine you have? Maybe the miniconda/miniforge version?

**Comment by esc** [comment]
> @esc I can find the ` linux-aarch64/llvmlite-0.38.0dev0-py38hbfd4b83_0.tar.bz2` packages in the list you provided, so it may be that my operating system has small issues on conda support. The operating system I use is OpenEuler. I closed this issue and would notify you if there are new discoveries. Thanks for your quick reply and your patience.

OK, no worries, please don't hesitate to re-open in case you don't manage to resolve.
