### ISSUE TITLE
LLVM ERROR: Unable to allocate memory for common symbols

### ISSUE THREAD

**Issue by Mikeworld-git** [numba/llvmlite#759]
My version
llvm=8.0
llvmlite=0.31.0
numba=0.48

When I run in this code, I get an "LLVM ERROR: Unable to allocate memory for common symbols" error
https://github.com/GeekAlexis/FastMOT/issues/168.

**Comment by gmarkall** [comment]
The linked issue appears to be resolved after uninstallation of LLVM 7.0.1 - is this now resolved?

Also, Numba 0.48 and llvmlite 0.31.0 are quite old now, from January 2020 - any issues in these versions may not be present in later released versions.
