### ISSUE TITLE
Add v0.37 Wheels for manylinux2010

### ISSUE THREAD

**Issue by freddyaboulton** [numba/llvmlite#768]
Hello!

I am trying to support the latest numba in a project (https://github.com/alan-turing-institute/sktime/pull/1348) and part of our CI is building the package for manylinux2010. That is currently failing when I install numba 0.54 for python 3.7 because it is trying to install llvmlite from source. 

Can you please publish wheels for manylinux 2010 for 0.37? They were published for 0.36 (corresponding to numba 0.53) so I'm wondering why the change happened.

Thank you!

**Comment by esc** [comment]
@freddyaboulton thank you for asking about this. With 0.37 we migrated to manylinux2014 wheels and we no longer ship the manylinux2010 wheels. Is there a chance you can upgrade to manylinux2014 too?

**Comment by esc** [comment]
I just researched this a bit more, and according to the following article, manylinux2010 has reached it's EOL last year:

https://labs.quansight.org/blog/2020/11/manylinux1-is-obsolete-manylinux2010-is-almost-eol-what-is-next/

**Comment by freddyaboulton** [comment]
@esc Thank you for answering my question. I think we'll move off of manylinux2010 sometime soon. Thank you for pointing us to that resource!

**Comment by esc** [comment]
@freddyaboulton no problem. I will close this issue now as it appears resolved. Thank you again for using/supporting Numba/llvmlite.
