### ISSUE TITLE
issue by numba installation on the Jetson Nano 

### ISSUE THREAD

**Issue by Zakaria1405** [numba/llvmlite#770]
i'm trying to download the library numba on my Jetson Nano. I followed the instruction described in this tutorial: 
[https://github.com/epicmario7133/install-Packages-Jetson-ARM-Family/blob/master/README.md](url)
but i got this error:
``nvidia@nvidia-desktop:~$ pip3 install numba==0.47
Defaulting to user installation because normal site-packages is not writeable
Collecting numba==0.47
  Downloading numba-0.47.0.tar.gz (1.9 MB)
     |████████████████████████████████| 1.9 MB 2.2 MB/s 
Requirement already satisfied: llvmlite>=0.31.0dev0 in ./.local/lib/python3.6/site-packages (from numba==0.47) (0.36.0)
Requirement already satisfied: numpy in ./.local/lib/python3.6/site-packages (from numba==0.47) (1.19.5)
Requirement already satisfied: setuptools in ./.local/lib/python3.6/site-packages (from numba==0.47) (57.0.0)
Building wheels for collected packages: numba
  Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status -4:
   command: /usr/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-d0h5x_il
       cwd: /tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/
  Complete output (0 lines):
  ----------------------------------------
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  ERROR: Command errored out with exit status -4:
   command: /usr/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a
  Complete output (0 lines):
  ----------------------------------------
  ERROR: Failed cleaning build dir for numba
Failed to build numba
Installing collected packages: numba
    Running setup.py install for numba ... error
    ERROR: Command errored out with exit status -4:
     command: /usr/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kvb8y68o/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/nvidia/.local/include/python3.6m/numba
         cwd: /tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/
    Complete output (0 lines):
    ----------------------------------------
ERROR: Command errored out with exit status -4: /usr/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yuxpeptm/numba_3045ac3c092f4285876678b04c6cc35a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kvb8y68o/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/nvidia/.local/include/python3.6m/numba Check the logs for full command output.
WARNING: You are using pip version 21.1.3; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/bin/python3.6 -m pip install --upgrade pip' command.

**Comment by esc** [comment]
@Zakaria1405 thank you for trying to install Numba. I don't think that 0.47 is supported on the Jetson Nano. But it is also fairly old. 0.54.0 is the latest and should support Jetson Nanon. Perhaps you could try to install that?

**Comment by Zakaria1405** [comment]
i tried the numba version 0.54 but i'm getting the same problem

**Comment by esc** [comment]
> i tried the numba version 0.54 but i'm getting the same problem

Thank you, can you post the exact backtrace for 0.54.0 installation also please. It will help us debug your problem!

**Comment by duomiger** [comment]
I meet the same question... and it can be solved by just upgrade your python to python3.8( numba only supports python later than 3.7 and the default python on jetson nano is python3.6.
