### ISSUE TITLE
Llvmlite Conda compatability

### ISSUE THREAD

**Issue by SledgeHammer01** [numba/llvmlite#781]
I'm using Conda on Windows 10 x64 Pro. In order for pandas_profiling to work, I need to install the numba llvmlite. If I install the conda version, pandas_profiling breaks saying it can't load llvmlite.

llvmlite           pkgs/main::llvmlite-0.36.0-py38h34b89~ --> numba::llvmlite-0.36.0-py38_0

Not sure why the main version doesn't work since its the same version. Does yours have a specific change that's not in the main channel? 

Reason is, this gets really annoying, as every conda upgrade --all is going to upgrade to the main channel one and break things and I have to remember to reapply the numba version.

**Comment by SledgeHammer01** [comment]
> Thanks for the report. On windows, nothing springs to mind that would create a difference. Does the conda-forge `llvmlite` build also have the same problem? Is this being used through Numba, if so does getting Numba from the Anaconda channels help?

Nope. pandas profiling is installed from conda-forge and installs the conda-forge llvmlite. Only works if I install from the numba channel.

**Comment by esc** [comment]
@SledgeHammer01 thank you for adding to this issue. We can try to reproduce this, we will need the following:

a) commands used to install Python
b) commands used to install llvmlite
c) commands to run to expose

Please be as accurate as possible when listing these commands so we can copy and paste them during the reproduction process. Also, it would be good to list what you expect to happen for each command and what happens instead. Thank you!

**Comment by h-vetinari** [comment]
> llvmlite pkgs/main::llvmlite-0.36.0-py38h34b89~ --> numba::llvmlite-0.36.0-py38_0

This is mixing channels (anaconda `main` and `numba`, which is not guaranteed to work). If you find that something is not working in a conda-forge-only environment (which has the highest chance of being current & working), then you can raise an issue on the feedstock for either [llvmlite](https://github.com/conda-forge/llvmlite-feedstock) or [pandas-profiling](https://github.com/conda-forge/pandas-profiling-feedstock).

To try that, see if
```
conda create -n your_env -c conda-forge python=3.8 pandas-profiling numba
```
yields a working environment. Note that to install the pandas-profiling from conda-forge, you don't even need numba.

**Comment by esc** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
