### ISSUE TITLE
Alloca: "TypeError: as_pointer() missing 1 required positional arguement: 'self'"

### ISSUE THREAD

**Issue by spidertyler2005** [numba/llvmlite#790]
I'm not 100% sure why I'm getting this error. If you have any answers just throw them at me.

# the line I'm having an issue with
```python
builder.alloca(ir.IntType, name="test")
```

# full error
```
File "/home/taustin/.local/lib/python3.9/site-packages/llvmlite/ir/builder.py", line 751, in alloca
    al = instructions.AllocaInstr(self.block, typ, size, name)
  File "/home/taustin/.local/lib/python3.9/site-packages/llvmlite/ir/instructions.py", line 477, in __init__
    super(AllocaInstr, self).__init__(parent, typ.as_pointer(), "alloca",
TypeError: as_pointer() missing 1 required positional argument: 'self'
```

# Info

```Yaml
python-version: 3.9.7
OS: arch linux
llvmlite-version: 0.37.0
llvm-version(from llc --version): 13.0.0
```

**Comment by esc** [comment]
@spidertyler2005 thank you for reporting this. I am not sure how you managed to install llvmlite with LLVM 13 -- llvmlite only supports LLVM 11. How did you install llvmlite?

**Comment by stuartarchibald** [comment]
The issue in the above is that `ir.IntType` is the "int" class, `alloca` needs a concrete instance of it so it knows how wide the `int` is. This sort of thing should work (using a 64 bit int as an example):
```python
builder.alloca(ir.IntType(64), name="foo")
```

**Comment by spidertyler2005** [comment]
> The issue in the above is that `ir.IntType` is the "int" class, `alloca` needs a concrete instance of it so it knows how wide the `int` is. This sort of thing should work (using a 64 bit int as an example):
> 
> ```python
> builder.alloca(ir.IntType(64), name="foo")
> ```

yeah, I am sitting in class and I just realized what I did wrong. I was about to close the issue and put that in a comment.

Thank you for the reply!

**Comment by spidertyler2005** [comment]
> @spidertyler2005 thank you for reporting this. I am not sure how you managed to install llvmlite with LLVM 13 -- llvmlite only supports LLVM 11. How did you install llvmlite?

I installed it via pip but then I installed llvm with pacman. I haven't had any issues with that so far. I'll make the downgrade if I have any issues.

Thank you for your reply!
