### ISSUE TITLE
Wheel support for Mac Arm (M1)

### ISSUE THREAD

**Issue by PhilipVinc** [numba/llvmlite#799]
There's no issue on this, so I'll open one to track this.

Currently LLVMLite does not provide Wheels on PyPi for Mac Arm (M1) processors, but they are only provided on Conda.
This is annoying because users cannot install using `pip` packages depending on Numba when running native. Releasing PyPi wheels for LLVMLite would be the first step towards addressing this.

**Comment by esc** [comment]
@PhilipVinc thank you for opening this issue. We hope to tackle this in Q1/Q2 2022 so that M1 wheels will be available for the 0.39.0 release.

**Comment by pikeas** [comment]
Until #813 is merged and released, what's the best way to install llvmlite in a Python 3.8+ virtualenv on an M1 Mac?

**Comment by PhilipVinc** [comment]
In my experience, annoying as it may be, conda-forge

**Comment by esc** [comment]
Good news, both llvmlite and numba have been extensively tested on an M1 now:

* https://github.com/numba/numba/issues/7822
* *https://github.com/numba/llvmlite/pull/813)

So, we are now in a position to build wheels too. If everything goes according to plan (which it rarely does) I'll be uploading some initial builds somewhere for testing, come next week.

**Comment by esc** [comment]
An initial set of wheels that I built are now available via anaconda.org:

https://anaconda.org/numba/llvmlite/files?channel=wheels_experimental_m1

While I have not tried this yet, the installation of the native wheels should simply be:

```
pip install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple llvmlite
```

Anyone waiting on these wheels is invited to "give them a spin". Please report back any issues you encounter with m1 wheels on this issue, thank you! 🙏

**Comment by esc** [comment]
Unfortunately, there seems to be an issue here, I just tried the instructions listed on:

https://anaconda.org/numba/llvmlite

However, I am unable to install the wheels.

```
(wheeltest) ci@colo-osxarm-02 ~ % pip install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple llvmlite

Looking in indexes: https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple
ERROR: Could not find a version that satisfies the requirement llvmlite (from versions: none)
ERROR: No matching distribution found for llvmlite
```

I will continue to look into this and keep you posted about progress.

**Comment by esc** [comment]
OK, so for some reason the wheels end up having the wrong tag:

```
(wheeltest) ci@colo-osxarm-02 llvmlite-0.39.0.dev0+61.gf27ac6f.dist-info % cat WHEEL
Wheel-Version: 1.0
Generator: bdist_wheel (0.37.1)
Root-Is-Purelib: false
Tag: cp310-cp310-macosx_10_9_x86_64
```

My assumption is that the suffix of the `Tag` entry should be `osx-arm64` and not `x86_64`.

**Comment by esc** [comment]
After some more fiddling with the CI system that builds the wheels, I managed to get some that work:

```
(wheeltest) ci@colo-osxarm-02 ~ % pip install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple llvmlite
Looking in indexes: https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple
Collecting llvmlite
  Downloading https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple/llvmlite/0.39.0.dev0%2B61.gf27ac6f/llvmlite-0.39.0.dev0%2B61.gf27ac6f-cp310-cp310-macosx_11_0_arm64.whl (23.1 MB)
     |████████████████████████████████| 23.1 MB 1.3 MB/s
Installing collected packages: llvmlite
Successfully installed llvmlite-0.39.0.dev0+61.gf27ac6f
```

These are for Python 3.8, 3.9 and 3.10 only. The system we use depends on `python` being available from `defaults` on anaconda.org and Python 3.7 is not (was not at the time of writing) available.

**Comment by henryiii** [comment]
Python 3.7 was never officially adapted to work on M1. 3.8 is the oldest the M1 changes were backported to (and officially, only 3.9+ is fully supported, 3.8 is considered experimental by CPython, but Apple provides their patched version)

**Comment by esc** [comment]
For reference, there are Numba wheels now too. See also: https://github.com/numba/numba/issues/7951

**Comment by esc** [comment]
An announcement for the wheels and a request to test them is here: https://numba.discourse.group/t/wheels-for-apple-silicon-m1/1282

**Comment by dbuades** [comment]
> An announcement for the wheels and a request to test them is here: https://numba.discourse.group/t/wheels-for-apple-silicon-m1/1282

I confirm that they work properly. Thank you!

**Comment by esc** [comment]
> > An announcement for the wheels and a request to test them is here: https://numba.discourse.group/t/wheels-for-apple-silicon-m1/1282
> 
> I confirm that they work properly. Thank you!

Thank you for checking and confirming!

**Comment by sbhatti2009** [comment]
> An announcement for the wheels and a request to test them is here: https://numba.discourse.group/t/wheels-for-apple-silicon-m1/1282

I can also confirm that the wheels are working as expected.

Thank you for finally releasing them!

**Comment by esc** [comment]
With llvmlite 0.38.1 M1 wheels are now available:

https://numba.discourse.group/t/llvmlite-0-38-1/1340
