### ISSUE TITLE
Instaling llvmlite on MacOS Monterey 12.1 (for chipwhisperer)

### ISSUE THREAD

**Issue by MrUndead13** [numba/llvmlite#804]
Good morning, 
I'm trying to install Jupiter requirements to work on a chipwhisperer lite (see tutorial here https://chipwhisperer.readthedocs.io/en/latest/installing.html#install-repo-git) and I'm getting stuck while installing llvmlite.
I'm getting this :

Installing collected packages: llvmlite, jupyter-contrib-core, distributed, bokeh, astcheck, xarray, scipy, panel, numba, lxml, kiwisolver, jupyter-nbextensions-configurator, jupyter-latex-envs, jupyter-highlight-selected-word, fonttools, datashape, cycler, colorcet, astsearch, terminaltables, PyCryptoDome, phoenixAES, nbparameterise, matplotlib, jupyter-contrib-nbextensions, holoviews, datashader
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/setup.py'"'"'; __file__='"'"'/private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-record-7ov_t9xt/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/nathanpaulet/Library/Python/3.10/include/python3.10/llvmlite
         cwd: /private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/
    Complete output (29 lines):
    running install
    running build
    got version from file /private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 /private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/ffi/build.py", line 191, in <module>
        main()
      File "/private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/ffi/build.py", line 185, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/setup.py'"'"'; __file__='"'"'/private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-install-umzoa9dn/llvmlite_ba87892ac5504a598b8dd5a2f8af261c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tw/nm_nrg_d2ss4db255j70pjwm0000gn/T/pip-record-7ov_t9xt/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/nathanpaulet/Library/Python/3.10/include/python3.10/llvmlite Check the logs for full command output.

I then tried to install llvmlite alone from pip but got the same issue.
Does someone know what could be causing this ?
I'm using macOS Monterey 12.1 and Python 3.10

**Comment by gmarkall** [comment]
The problem is that there isn't a released version that supports Python 3.10 yet, so you will need to use the 0.38 RC. Can you try:

```
pip install llvmlite==0.38.0rc1
```

and let me know if that works out please?

**Comment by MrUndead13** [comment]
Thanks for you reply :)
I tried that but it wasn't able to find the path to llvm-config.

So I specified it with LLVM_CONFIG=/opt/homebrew/opt/llvm@13/bin/llvm-config or just LLVM_CONFIG=/opt/homebrew/opt/llvm/bin/llvm-config and it said : 

Building llvmlite requires LLVM 11.x.x, got '13.0.0'. Be sure to set LLVM_CONFIG to the right executable path.

**Comment by gmarkall** [comment]
Ah - there is perhaps not a wheel available for your platform. Is your system x86_64 or AArch64?

**Comment by MrUndead13** [comment]
I'm using a MacBook Air M1 so I would say AArch64

**Comment by seibert** [comment]
We do not yet have wheels for macOS AArch64, although we have them for Linux AArch64.  Both conda-forge and Anaconda now have conda packages for macOS AArch64 (they call the platform `osx-arm64`), but we should be able to make wheels in the coming month as we add M1 support to the Numba build farm we use for wheel building (as well as testing).

**Comment by MrUndead13** [comment]
Thank you for that ! I'll be waiting for that release then !
Have a nice end of the year
