### ISSUE TITLE
import llvmlite race condition with multiple interpreters on Windows

### ISSUE THREAD

**Issue by crusaderky** [numba/llvmlite#808]
llvmlite                                   0.37.0  py37habb0c8c_1          conda-forge/win-64

I found a race condition on Windows when multiple Python interpreters try to import llvmlite in parallel.

The dask test suite just crashed on github actions windows:
https://github.com/dask/dask/runs/4761444273?check_suite_focus=true:

```python
ctx = mp.get_context("spawn")
with ProcessPoolExecutor(8, ctx) as pool:
     ... = set(pool.map(...))
```
Output:
```
E           concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[...]

    import numba

  File "C:\Miniconda3\envs\test-environment\lib\site-packages\numba\__init__.py", line 19, in <module>

    from numba.core import config

  File "C:\Miniconda3\envs\test-environment\lib\site-packages\numba\core\config.py", line 16, in <module>

    import llvmlite.binding as ll

  File "C:\Miniconda3\envs\test-environment\lib\site-packages\llvmlite\binding\__init__.py", line 4, in <module>

    from .dylib import *

  File "C:\Miniconda3\envs\test-environment\lib\site-packages\llvmlite\binding\dylib.py", line 3, in <module>

    from llvmlite.binding import ffi

  File "C:\Miniconda3\envs\test-environment\lib\site-packages\llvmlite\binding\ffi.py", line 191, in <module>

    raise OSError("Could not load shared object file: {}".format(_lib_name))

OSError: Could not load shared object file: llvmlite.dll
```

**Comment by esc** [comment]
@crusaderky thank you for reporting this. Would you be able to try the latest `v0.38.0rc1` ? Importantly it includes code to actually print the error message in such cases, which may help to diagnose the issue further. Thank you.

**Comment by crusaderky** [comment]
Sorry for the extremely delayed answer.
I ran a stress test but I can no longer reproduce the issue on llvmlite-0.39.1 / Python 3.8 / Windows (my project has since dropped Python 3.7 which is where the original failure happened; may or may not be related).
