### ISSUE TITLE
Put functions in specified sections

### ISSUE THREAD

**Issue by anlofw** [numba/llvmlite#822]
---

## Feature request

We are working on a language front-end using llvmlite and have a need to put functions in specified sections (similar to llvm.global_ctors). I generated IR code for the equivalent C constructs for comparison. See below.

```
static __attribute__ ((section (".p_init.200"))) void p_init1(void)
{
   printf("p_init1\n");
}
```
This results in the following IR code
```
; Function Attrs: nofree nounwind
define internal void @p_init1() #3 section ".p_init.200" {
  %1 = tail call i32 @puts(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @str.4, i32 0, i32 0))
  ret void
}
```
The part we want to be able to specify is the __section ".p_init.200"__.
Comments for #401 indicates that there is no support for this.

If anyone has any pointers on where/how this could be implemented, I am happy to (try to) implement the feature and provide a pull request.

**Comment by stuartarchibald** [comment]
Thanks for opening this request. IIRC adding a `section` to such a declaration is not supported yet. I think the code that would need changing is predominantly in the function Value class here:
https://github.com/numba/llvmlite/blob/df279499f515189b211ebc9c697345b39d8e7481/llvmlite/ir/values.py#L924
this method is used to encode the prototype as IR and would need to handle a `section` class member:
https://github.com/numba/llvmlite/blob/df279499f515189b211ebc9c697345b39d8e7481/llvmlite/ir/values.py#L966-L987

I envisage a patch to enable such a feature would be welcomed.
