### ISSUE TITLE
Building from source: should llvm_11_consecutive_registers.patch be used?

### ISSUE THREAD

**Issue by jaskij** [numba/llvmlite#839]
I am building llvmlite from source, and there seems to be a discrepancy/bug in the docs.  The docs only mention five patches to apply, while the `conda-recipes` directory has six patches in it, the unmnentioned patch being [`llvm_11_consecutive_registers.patch`](https://github.com/numba/llvmlite/blob/v0.38.0/conda-recipes/llvm_11_consecutive_registers.patch).

Should I apply this patch? I know it is only relevant to Aarch64, but that is the architecture I am building for.

**Comment by esc** [comment]
@jaskij thank you for asking about this!! I believe the answer is yes, it should be applied! And, It appears as though the documentation is behind. So, yes, do apply that patch and -- if you can -- please also supply a PR to update the docs. That would be very much appreciated.

**Comment by esc** [comment]
@jaskij I created a patch to fix this at #851 -- if you have spare cycles, please do consider reviewing it, thank you.
