### ISSUE TITLE
support the ParseIRFile API in llvmlite

### ISSUE THREAD

**Issue by dlee992** [numba/llvmlite#879]
## Feature request

Here is the thing. I wrote some C++ code for a new Numba type and its operations. At first, I compiled the C++ code into a pythonic `.so` file, and using `ir.FunctionType` to declare the C++ function, then generate the `call` IR to call the underlying C++ function. But awfully, I have to call this C++ functions frequently and switch the context from jitted function to `.so`, and back and forth many times. Thus this hurts the performance.

After a discussion with @gmarkall , I have to compile the C++ code to generate LLVM IR (say, from a `foo.cpp` to a `foo.ll`), read and convert it as a llvmlite IR module (during Numba compilation process, I guess this is kind of similar with `@cuda.jit(link=[foo.cu]`), then link it in the jitted IR module (the main module). Thus, LLVM can do some tricks about function inlining to avoid creating a new stack frame, switch registers, etc, to save much time.

But, llvmlite doesn't provide this kind of interface/wrapper for the LLVM `ParseIRFile` API (I guess the corresponding API in nvptx is `nvrtcCreateProgram`). Say, I can use clang to convert a C++ file to the corresponding IR file (e.g., from foo.cpp to foo.ll), and stuck in this place.

So, I think this is a feature request. And I want to contribute a wrapper for this specific API in llvmlite. Or maybe we can discuss an alternative way to fulfill my goal.

**Comment by esc** [comment]
@dlee992 thank you for opening this. I have labelled this as a feature request and we probably ought to discuss this during the developer meeting next week. 👍

**Comment by gmarkall** [comment]
Can you not use `llvmlite.binding.parse_assembly()`: https://llvmlite.readthedocs.io/en/latest/user-guide/binding/modules.html#llvmlite.binding.parse_assembly ?

**Comment by stuartarchibald** [comment]
I think this feature is already covered by the API suggested by @gmarkall. There's also `llvmlite.binding.parse_bitcode()` for creating a module from LLVM bitcode.

For creating a LLVM module from LLVM IR in a string:
https://github.com/numba/llvmlite/blob/6e8a86449e92a6b78498ec64922c39e2bd4f7a61/llvmlite/binding/module.py#L11-L26
For creating a LLVM module from LLVM bitcode held as bytes:
https://github.com/numba/llvmlite/blob/6e8a86449e92a6b78498ec64922c39e2bd4f7a61/llvmlite/binding/module.py#L29-L44
`clang` can produce both of these formats directly, so it's just a question of opening and reading a file in a manner most suitable to your use case and then consuming the contents via one of these functions to get a LLVM module. Does that cover the use case envisaged?

**Comment by dlee992** [comment]
Oh, yes, I could do this by using `parse_assembly` after reading the `ll` file into a string. Many thanks! Very awkward, I guess I'm just frightened by these magic things, and forgot the basic process to do this.

**Comment by esc** [comment]
> Oh, yes, I could do this by using `parse_assembly` after reading the `ll` file into a string. Many thanks! Very awkward, I guess I'm just frightened by these magic things, and forgot the basic process to do this.

Awesome! OK to close this issue again?
