### ISSUE TITLE
Can llvmlite compile Python3 code dirctly into LLVM

### ISSUE THREAD

**Issue by Lost-little-dinosaur** [numba/llvmlite#882]
Can llvmlite translate Python3 code dirctly into LLVM IR like the llvm_py2llvm tools rather than can only translate the python code which use api of the llvmlite's?

Now, I only know that llvmlite can translate these python3 code into LLVM IR
(from the example code)
```python
from llvmlite import ir

# Create some useful types
double = ir.DoubleType()
fnty = ir.FunctionType(double, (double, double))

# Create an empty module...
module = ir.Module(name=__file__)
# and declare a function named "fpadd" inside it
func = ir.Function(module, fnty, name="fpadd")

# Now implement the function
block = func.append_basic_block(name="entry")
builder = ir.IRBuilder(block)
a, b = func.args
result = builder.fadd(a, b, name="res")
builder.ret(result)

# Print the module IR
print(module)

```
But can llvmlite translate these python3 code into LLVM IR like the llvm_py2llvm code translate python2 code into LLVM IR?
```python
def fadd(a,b):
    return a+b

if __name__ == '__main__':
    print(llvmlite.translatePython3ToLLVMIR(fpadd))  # TODO: translatePython3ToLLVMIR
```
the output is as same as the first output
```
define double @"fpadd"(double %".1", double %".2") 
{
entry:
  %"res" = fadd double %".1", %".2"
  ret double %"res"
}

```

I cannot find this feature in the official documents, if you have made this feature, please accept my apology and tell me where to find it. If you can't do this for a while, you can recommend a similar tool that can do this function, I would be also very grateful

**Comment by esc** [comment]
@Lost-little-dinosaur thank you for asking about this. I think you may want to look at our other product: Numba. It can compile the example you suggested directly to machine code (via LLVM IR). A good introduction to Numba can be found here: https://numba.readthedocs.io/en/stable/user/5minguide.html#will-numba-work-for-my-code

**Comment by Lost-little-dinosaur** [comment]
> @Lost-little-dinosaur thank you for asking about this. I think you may want to look at our other product: Numba. It can compile the example you suggested directly to machine code (via LLVM IR). A good introduction to Numba can be found here: https://numba.readthedocs.io/en/stable/user/5minguide.html#will-numba-work-for-my-code

Oh, thank you! I an very appreciate that
