### ISSUE TITLE
llvm-3.6.1 ubunut14.10  undefined symbol: _ZNSt14error_categoryC2Ev

### ISSUE THREAD

**Issue by jiamo** [numba/llvmlite#89]
Download prebuild llvm from http://llvm.org/releases/download.html#3.6.1

~/Git/llvmlite$ LLVM_CONFIG=/home/ikfb/bin/clang+llvm-3.6.1-x86_64-linux-gnu/bin/llvm-config python3 setup.py build
    /usr/local/lib/python3.4/dist-packages/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '0.7.0.dev0' instead of '0.7.0.dev'.
      self.metadata.version,
    running build
    got version from VCS {'full': 'f97db81e0bdf0748aa52ed8080a71cb4a73e560f', 'version': '0.7.0.dev'}
    running build_ext
    /usr/bin/python3 ffi/build.py
    LLVM version... 3.6.1
    # static-libstdc++ avoids runtime dependencies on a
    # particular libstdc++ version.
    g++ -static-libstdc++ -shared -flto `/home/ikfb/bin/clang+llvm-3.6.1-x86_64-linux-gnu/bin/llvm-config --cxxflags` -fno-rtti -g assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -flto `/home/ikfb/bin/clang+llvm-3.6.1-x86_64-linux-gnu/bin/llvm-config --ldflags` -Wl,--exclude-libs=ALL `/home/ikfb/bin/clang+llvm-3.6.1-x86_64-linux-gnu/bin/llvm-config --system-libs --libs all`
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    creating build/lib.linux-x86_64-3.4/llvmlite
    copying llvmlite/utils.py -> build/lib.linux-x86_64-3.4/llvmlite
    copying llvmlite/six.py -> build/lib.linux-x86_64-3.4/llvmlite
    copying llvmlite/__init__.py -> build/lib.linux-x86_64-3.4/llvmlite
    copying llvmlite/_version.py -> build/lib.linux-x86_64-3.4/llvmlite
    creating build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/executionengine.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/__init__.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/dylib.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/module.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/initfini.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/value.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/targets.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/ffi.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/linker.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/transforms.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/options.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/passmanagers.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    copying llvmlite/binding/common.py -> build/lib.linux-x86_64-3.4/llvmlite/binding
    creating build/lib.linux-x86_64-3.4/llvmlite/ir
    copying llvmlite/ir/__init__.py -> build/lib.linux-x86_64-3.4/llvmlite/ir
    copying llvmlite/ir/module.py -> build/lib.linux-x86_64-3.4/llvmlite/ir
    copying llvmlite/ir/_utils.py -> build/lib.linux-x86_64-3.4/llvmlite/ir
    copying llvmlite/ir/builder.py -> build/lib.linux-x86_64-3.4/llvmlite/ir
    copying llvmlite/ir/transforms.py -> build/lib.linux-x86_64-3.4/llvmlite/ir
    copying llvmlite/ir/instructions.py -> build/lib.linux-x86_64-3.4/llvmlite/ir
    copying llvmlite/ir/context.py -> build/lib.linux-x86_64-3.4/llvmlite/ir
    copying llvmlite/ir/types.py -> build/lib.linux-x86_64-3.4/llvmlite/ir
    copying llvmlite/ir/values.py -> build/lib.linux-x86_64-3.4/llvmlite/ir
    creating build/lib.linux-x86_64-3.4/llvmlite/llvmpy
    copying llvmlite/llvmpy/__init__.py -> build/lib.linux-x86_64-3.4/llvmlite/llvmpy
    copying llvmlite/llvmpy/avx_support.py -> build/lib.linux-x86_64-3.4/llvmlite/llvmpy
    copying llvmlite/llvmpy/ee.py -> build/lib.linux-x86_64-3.4/llvmlite/llvmpy
    copying llvmlite/llvmpy/passes.py -> build/lib.linux-x86_64-3.4/llvmlite/llvmpy
    copying llvmlite/llvmpy/core.py -> build/lib.linux-x86_64-3.4/llvmlite/llvmpy
    creating build/lib.linux-x86_64-3.4/llvmlite/tests
    copying llvmlite/tests/test_binding.py -> build/lib.linux-x86_64-3.4/llvmlite/tests
    copying llvmlite/tests/__init__.py -> build/lib.linux-x86_64-3.4/llvmlite/tests
    copying llvmlite/tests/customize.py -> build/lib.linux-x86_64-3.4/llvmlite/tests
    copying llvmlite/tests/test_ir.py -> build/lib.linux-x86_64-3.4/llvmlite/tests
    copying llvmlite/tests/test_valuerepr.py -> build/lib.linux-x86_64-3.4/llvmlite/tests
    copying llvmlite/tests/__main__.py -> build/lib.linux-x86_64-3.4/llvmlite/tests
    copying llvmlite/binding/libllvmlite.so -> build/lib.linux-x86_64-3.4/llvmlite/binding
    UPDATING build/lib.linux-x86_64-3.4/llvmlite/_version.py
    ikfb@ikfb:~/Git/llvmlite$ ls^C
    ikfb@ikfb:~/Git/llvmlite$ python3 -m nose
    EEEE....
    ======================================================================
    ERROR: llvmlite.tests.test_binding (unittest.loader.ModuleImportFailure)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
      File "/usr/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
      File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
        raise exception
    ImportError: Failed to import test module: llvmlite.tests.test_binding
    Traceback (most recent call last):
      File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
        module = self._get_module_from_name(name)
      File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
        __import__(name)
      File "/home/ikfb/Git/llvmlite/llvmlite/tests/test_binding.py", line 13, in <module>
        from llvmlite import binding as llvm
      File "/home/ikfb/Git/llvmlite/llvmlite/binding/__init__.py", line 6, in <module>
        from .dylib import *
      File "/home/ikfb/Git/llvmlite/llvmlite/binding/dylib.py", line 4, in <module>
        from . import ffi
      File "/home/ikfb/Git/llvmlite/llvmlite/binding/ffi.py", line 36, in <module>
        lib = ctypes.CDLL(os.path.join(_lib_dir, get_library_name()))
      File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /home/ikfb/Git/llvmlite/llvmlite/binding/libllvmlite.so: undefined symbol: _ZNSt14error_categoryC2Ev

**Comment by jiamo** [comment]
while after intall llvm-dev-3.6 using system llvm-config path . It works. `LLVM_CONFIG=/usr/bin/llvm-config-3.6 python3 setup.py build`

**Comment by pitrou** [comment]
Which one did you take? If you took the 14.04 binary, please try the 15.04, and vice-versa.
The "undefined symbol" belongs to the C++ standard library, which tends to have a changing ABI. You'll find other people with the same problem on the Internet...

**Comment by jiamo** [comment]
Ok 15.04 work fine.
