### ISSUE TITLE
Cannot Uninstall 0.38.0

### ISSUE THREAD

**Issue by kjkoeller** [numba/llvmlite#901]
I tried to upgrade this package to 0.39.1 but it won't allow me to uninstall 0.38.0 which is causing issues with installing other packages. Specifically when installing Numba. I am using Python 3.9.12 as an FYI

```
(base) C:\WINDOWS\system32>pip install --upgrade llvmlite
Requirement already satisfied: llvmlite in c:\users\kyle\anaconda3\lib\site-packages (0.38.0)
Collecting llvmlite
  Using cached llvmlite-0.39.1-cp39-cp39-win_amd64.whl (23.2 MB)
Installing collected packages: llvmlite
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.38.0
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by esc** [comment]
@kjkoeller thank you for reporting this. This is a very unusual error and has little to do with Numba or llvmlite. This is most likely a result of how you installed the packages so I'm afraid we won't be of much use here. The best recommendation I can make is to setup your virtualenvironment if you are using that and otherwise to re-install Python on your machine. So sorry that I can't be of more help and good luck fixing this issue.

**Comment by kjkoeller** [comment]
@esc I use Numba for a Python package I have created and this issue has come up on both my laptop, desktop, and two different colleagues laptop and desktops.

**Comment by esc** [comment]
> thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

OK, I am not sure how to help you here. I can only guess for things to do:

* Upgrade

**Comment by esc** [comment]
@kjkoeller any updates? Did you manage to sort it out?

**Comment by kjkoeller** [comment]
The issues seems to stem only from Python 3.9.12. I tried in Python 3.8.16 and 3.10.9 and uninstalling 0.38.0 was not an issue. However, after uninstalling all files related to `llvmlite` there does not seem to be any issues any more with installing an upgrade for `llvmlite`.

**Comment by kjkoeller** [comment]
Thanks for the help!

**Comment by esc** [comment]
> Thanks for the help!

Awesome, thank you for reporting back and happy to hear you managed to resolve your issues! ❤️

**Comment by wangtiance** [comment]
> The issues seems to stem only from Python 3.9.12. I tried in Python 3.8.16 and 3.10.9 and uninstalling 0.38.0 was not an issue. However, after uninstalling all files related to `llvmlite` there does not seem to be any issues any more with installing an upgrade for `llvmlite`.

I'm using Python 3.9.13 and had the same issue. Likewise the issue was solved by manually removing the files. Thanks for sharing the solution!
