### ISSUE TITLE
“Escape hatch” for maximum Python version check

### ISSUE THREAD

**Issue by musicinmybrain** [numba/llvmlite#912]
---

## Feature request

I understand that `llvmlite` is developed together with Numba, and new Python interpreter versions will probably continue to be officially unsupported here until both packages have fully-validated support ready.

In Fedora Linux, we are currently unable to package Numba because we must build all Python packages with the current Python interpreter version. Because Fedora is a fast-moving distribution, a new CPython release happens almost at the same time as the first Fedora Linux stable release that contains it; incompatibilities are sorted out using CPython pre-releases. To be successfully included in Fedora, Numba would need to have support for a new Python version around the time of its final release—at least in some kind of development branch.

Despite the obstacles to packaging Numba, `llvmlite` is [usefully packaged in Fedora Linux](https://src.fedoraproject.org/rpms/python-llvmlite), where it is used by Sympy and Mathics3. We have been able to build it for Python 3.11 and 3.12 by simply loosening the bound on the maximum Python version in `setup.py`. Because we run the full test suite in the RPM build, we have pretty good confidence in the resulting package even without official upstream support for the current Python release.

So that we, and other Linux distributions, do not have to carry a downstream patch, would you consider a PR that allowed explicitly bypassing the maximum Python version check—perhaps by setting an environment variable like `LLVMLITE_NO_MAX_PYTHON_CHECK`?

Alternatively, would you consider supporting new Python releases in `llvmlite` once its tests pass on them, rather than waiting for Numba to catch up?

**Comment by apmasell** [comment]
That makes sense for non-Numba uses. We will discuss during our triage tomorrow and determine the possible designs. We rarely have issues with Python upgrades in llvmlite, but we also have no infrastructure to test Python versions newer than what Numba is capable of handling.

**Comment by apmasell** [comment]
We've discussed this and will simply remove the check and expand the testing infrastructure to include Python up to whatever is available in our Azure testing environment. We have seen very little breakage of llvmlite from newer Python versions and most of the problem will likely be in the packages that depend on llvmlite.

**Comment by musicinmybrain** [comment]
Thank you for considering this request! From Fedora’s perspective, your decision represents the best possible outcome.
