### ISSUE TITLE
 I tried berryconda, miniconda but getting no success in installing llvmlite package. I am having ARMv7I architecture on Rpi 4b+. Also berryconda and miniconda degrading python version. Ealier I am using python 3.9

### ISSUE THREAD

**Issue by jainharshita275** [numba/llvmlite#928]
pi@raspberrypi:~ $ conda install llvmlite
Fetching package metadata .....

PackageNotFoundError: Package missing in current linux-aarch64 channels:

llvmlite
..........................................

pi@raspberrypi:~ $ pip install llvmlite
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting llvmlite
Using cached llvmlite-0.36.0.tar.gz (126 kB)
Preparing metadata (setup.py) ... done
Building wheels for collected packages: llvmlite
Building wheel for llvmlite (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/pi/berryconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/setup.py'"'"'; file='"'"'/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-06e5g_9v
cwd: /tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/
Complete output (15 lines):
running bdist_wheel
/home/pi/berryconda3/bin/python /tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/ffi/build.py
LLVM version... 7.0.1
Traceback (most recent call last):
File "/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/ffi/build.py", line 220, in
main()
File "/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/ffi/build.py", line 210, in main
main_posix('linux', '.so')
File "/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/ffi/build.py", line 172, in main_posix
raise RuntimeError(msg)
RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '7.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

error: command '/home/pi/berryconda3/bin/python' failed with exit status 1
ERROR: Failed building wheel for llvmlite
Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
Running setup.py install for llvmlite ... error
ERROR: Command errored out with exit status 1:
command: /home/pi/berryconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/setup.py'"'"'; file='"'"'/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-hp798ma9/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/berryconda3/include/python3.6m/llvmlite
cwd: /tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/
Complete output (18 lines):
running install
running build
got version from file /tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/llvmlite/_version.py {'version': '0.36.0', 'full': 'e6bb8d137d922bec8beeb01a237254778759becd'}
running build_ext
/home/pi/berryconda3/bin/python /tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/ffi/build.py
LLVM version... 7.0.1

Traceback (most recent call last):
  File "/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/ffi/build.py", line 220, in <module>
    main()
  File "/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/ffi/build.py", line 210, in main
    main_posix('linux', '.so')
  File "/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/ffi/build.py", line 172, in main_posix
    raise RuntimeError(msg)
RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '7.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

error: command '/home/pi/berryconda3/bin/python' failed with exit status 1
----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/berryconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/setup.py'"'"'; file='"'"'/tmp/pip-install-t1xx2jb4/llvmlite_98f0b002214d4beda34d73dca17ab8a9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-hp798ma9/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/berryconda3/include/python3.6m/llvmlite Check the logs for full command output.

**Comment by sklam** [comment]
IIRC, ARMv7 support is different enough, but I don't quite remember how it works. I'm asking someone who has more experience with ARMv7.

**Comment by seibert** [comment]
Hi!  Getting things to work on ARMv7 is going to be challenging as Berryconda has not been actively maintained for more than a year, and none of the other conda-based distributions (conda-forge or Anaconda) have ARMv7 support either.   I just checked and it doesn't look like piwheels.net (which builds wheels for ARMv7 and v6) has llvmlite wheels, which is the only source of regularly updated ARMv7 Python packages I'm aware of.

Since you mention that you have a Raspberry Pi 4 (which is an ARMv8 AKA "AArch64" CPU), I would suggest you look into switching to a 64-bit OS (Raspberry Pi OS is available in a 64-bit version, as well as Ubuntu and others) if possible.  You'll find much better support for Python packages, both for wheels and conda, and you'll be able to get llvmlite from PyPI, conda-forge, and Anaconda.

**Comment by jainharshita275** [comment]
(env) raspberrypi@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux
.........................................................
  Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/raspberrypi/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-u60wk0c_/install-record.txt --single-version-externally-managed --compile --install-headers /home/raspberrypi/env/include/site/python3.9/llvmlite
         cwd: /tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/
    Complete output (18 lines):
    running install
    running build
    got version from file /tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/llvmlite/_version.py {'version': '0.39.1', 'full': '31f808fa7a5796bb8d4b14e8a9e27c6dd15f2b6c'}
    running build_ext
    /home/raspberrypi/env/bin/python /tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/ffi/build.py
    LLVM version... 7.0.1
    
    Traceback (most recent call last):
      File "/tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/ffi/build.py", line 226, in <module>
        main()
      File "/tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/ffi/build.py", line 216, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/ffi/build.py", line 173, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 11.x.x, got '7.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
    
    error: command '/home/raspberrypi/env/bin/python' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/raspberrypi/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w6wiuxfg/llvmlite_2fa1f00b6eaa46c4b978020008a4e665/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-u60wk0c_/install-record.txt --single-version-externally-managed --compile --install-headers /home/raspberrypi/env/include/site/python3.9/llvmlite Check the logs for full command output.

showing this error. Can you please help me installing llvmlite. I need to install noisereduce module but module showing llvmlite dependancy.

**Comment by jainharshita275** [comment]
raspberrypi@raspberrypi:~/Downloads $ pip install llvmlite-0.39.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: llvmlite-0.39.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl is not a supported wheel on this platform.

**Comment by sklam** [comment]
@seibert, can rpi4 get newer ubuntu? is that what's necessary to get manylinux2014 compatibility?

**Comment by jainharshita275** [comment]
Hi, my problem has been solved with 64 bit OS.
Thanks

**Comment by esc** [comment]
@jainharshita275 thank you for closing.

Ref: https://github.com/numba/llvmlite/issues/604#issuecomment-1516365818
