### ISSUE TITLE
Test failure in 0.40.0 on 64-bit PowerPC: test_get_process_triple

### ISSUE THREAD

**Issue by musicinmybrain** [numba/llvmlite#941]
## Reporting a bug

- [x] I have tried using the latest released version of llvmlite (most recent is
 visible in the change log (https://github.com/numba/llvmlite/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'. **N/A**

I [just tested](https://src.fedoraproject.org/rpms/python-llvmlite/pull-request/5) updating the [`python-llvmlite` package](https://src.fedoraproject.org/rpms/python-llvmlite) in Fedora Linux to 0.40.0 (in Rawhide, the development version of Fedora).

I got exactly one test failure—only on `ppc64le`—as follows:

```
======================================================================
FAIL: test_get_process_triple (llvmlite.tests.test_binding.TestMisc.test_get_process_triple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/llvmlite-0.40.0/llvmlite/tests/test_binding.py", line 587, in test_get_process_triple
    self.assertEqual(default_parts[0], triple_parts[0])
AssertionError: 'ppc64le' != 'powerpc64le'
- ppc64le
+ powerpc64le
?  ++++
```

What do you think? Thanks!

**Comment by gmarkall** [comment]
Is there anything that might have recently changed the triple in Fedora or its build infrastructure lately?

**Comment by esc** [comment]
This was discussed in the Numba meeting yesterday, here is a link to the notes:

https://github.com/numba/numba/wiki/Minutes_2023_05_09

Unfortunately, the details have not been recorded, but IIRC this was a somewhat confusing issue, since in many places, the two strings are used synonymously. I think @sklam can recall the specifics? 

The bug question for this one is, does this warrant an llvmlite point release?

**Comment by musicinmybrain** [comment]
> Unfortunately, the details have not been recorded, but IIRC this was a somewhat confusing issue, since in many places, the two strings are used synonymously.

https://github.com/pypa/manylinux/issues/687 does not exactly apply here, but it gives a starting point for digging into the history of these names and their handling.

> The bug question for this one is, does this warrant an llvmlite point release? @musicinmybrain is this something you could work around during package building?

Was there a conclusion regarding what should be done about it? If the discrepancy is deemed harmless, I can easily skip the single affected test on `ppc64le`.

**Comment by apmasell** [comment]
I don't know how to test this, but I added normalization to the default triple: https://github.com/numba/llvmlite/pull/948

**Comment by musicinmybrain** [comment]
> I don't know how to test this, but I added normalization to the default triple: #948

When that PR is applied as a patch to the Fedora Linux package, the [tests still fail in the same way on `ppc64le`](https://koji.fedoraproject.org/koji/taskinfo?taskID=101249014):

```
======================================================================
FAIL: test_get_process_triple (llvmlite.tests.test_binding.TestMisc.test_get_process_triple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/llvmlite-0.40.0/llvmlite/tests/test_binding.py", line 587, in test_get_process_triple
    self.assertEqual(default_parts[0], triple_parts[0])
AssertionError: 'ppc64le' != 'powerpc64le'
- ppc64le
+ powerpc64le
?  ++++
----------------------------------------------------------------------
```

**Comment by apmasell** [comment]
Ah. That's unfortunate. I was hoping it would be a uniform way to handle this. I'll modify the test to handle this case specially.

**Comment by apmasell** [comment]
Okay, let's try brute force.

**Comment by esc** [comment]
@musicinmybrain :: will https://github.com/numba/llvmlite/issues/941 suffice to fix the issue you are seeing?

**Comment by musicinmybrain** [comment]
> @musicinmybrain :: will #941 suffice to fix the issue you are seeing?

I think you meant https://github.com/numba/llvmlite/pull/949. I commented there; it is not quite correct yet.
