### ISSUE TITLE
Wrong syntax for LLVM 14 argument attributes

### ISSUE THREAD

**Issue by thomasfire** [numba/llvmlite#946]
As of 3c2163ada3c6ce1acf78e6c06e8a5e38c5c24ced , llvmlite still outputs wrong syntax for LLVM 14. 

At least for `byval`, `sret` and `inalloca`  (others can be affected as well, but I couldn't find difference between LLVM 11 and LLVM 14 regarding attributes listed in https://github.com/numba/llvmlite/blob/3c2163ada3c6ce1acf78e6c06e8a5e38c5c24ced/llvmlite/ir/values.py#L1021), llvmlite outputs syntax for LLVM 11, which actually has been changed in LLVM 14. 
Please check language reference https://releases.llvm.org/14.0.0/docs/LangRef.html. 
In example below I get such error:
```
RuntimeError: LLVM IR parsing error
<string>:5:30: error: expected '('
define i32 @"sum"(i32* byval %".1", i32 %".2")
                             ^
```
And LLVM actually expects it to be `define i32 @"sum"(i32* byval({i32}) %".1", i32 %".2")`

Take this example (I took it from examples/sum.py and just added attributes):
```py
from __future__ import print_function

from ctypes import CFUNCTYPE, c_int, POINTER
import sys
try:
    from time import perf_counter as time
except ImportError:
    from time import time

import numpy as np

try:
    import faulthandler; faulthandler.enable()
except ImportError:
    pass

import llvmlite.ir as ll
import llvmlite.binding as llvm


llvm.initialize()
llvm.initialize_native_target()
llvm.initialize_native_asmprinter()


t1 = time()

fnty = ll.FunctionType(ll.IntType(32), [ll.IntType(32).as_pointer(),
                                        ll.IntType(32)])
module = ll.Module()

func = ll.Function(module, fnty, name="sum")

bb_entry = func.append_basic_block()
bb_loop = func.append_basic_block()
bb_exit = func.append_basic_block()

builder = ll.IRBuilder()
builder.position_at_end(bb_entry)

builder.branch(bb_loop)
builder.position_at_end(bb_loop)

index = builder.phi(ll.IntType(32))
index.add_incoming(ll.Constant(index.type, 0), bb_entry)
accum = builder.phi(ll.IntType(32))
accum.add_incoming(ll.Constant(accum.type, 0), bb_entry)

#func.args[0].add_attribute('sret')
func.args[0].add_attribute('byval')
ptr = builder.gep(func.args[0], [index])
value = builder.load(ptr)

added = builder.add(accum, value)
accum.add_incoming(added, bb_loop)

indexp1 = builder.add(index, ll.Constant(index.type, 1))
index.add_incoming(indexp1, bb_loop)

cond = builder.icmp_unsigned('<', indexp1, func.args[1])
builder.cbranch(cond, bb_loop, bb_exit)

builder.position_at_end(bb_exit)
builder.ret(added)

strmod = str(module)

t2 = time()

print("-- generate IR:", t2-t1)

t3 = time()

llmod = llvm.parse_assembly(strmod)

t4 = time()

print("-- parse assembly:", t4-t3)

print(llmod)

pmb = llvm.create_pass_manager_builder()
pmb.opt_level = 2
pm = llvm.create_module_pass_manager()
pmb.populate(pm)

t5 = time()

pm.run(llmod)

t6 = time()

print("-- optimize:", t6-t5)

t7 = time()

target_machine = llvm.Target.from_default_triple().create_target_machine()

with llvm.create_mcjit_compiler(llmod, target_machine) as ee:
    ee.finalize_object()
    cfptr = ee.get_function_address("sum")

    t8 = time()
    print("-- JIT compile:", t8 - t7)

    print(target_machine.emit_assembly(llmod))

    cfunc = CFUNCTYPE(c_int, POINTER(c_int), c_int)(cfptr)
    A = np.arange(10, dtype=np.int32)
    res = cfunc(A.ctypes.data_as(POINTER(c_int)), A.size)

    print(res, A.sum())
```

Affects https://github.com/msys2/MINGW-packages/issues/15467 and https://github.com/m-labs/artiq/issues/2050

**Comment by thomasfire** [comment]
Moreover, I've found that in tests it actually expects wrong syntax: https://github.com/numba/llvmlite/blob/3c2163ada3c6ce1acf78e6c06e8a5e38c5c24ced/llvmlite/tests/test_ir.py#L1373
And since this code passes tests, I think it needs to include checks that actual LLVM accepts the submitted IR. Otherwise there will be more such errors once LLVM change their syntax (again).

**Comment by esc** [comment]
@thomasfire thank you for the report, I can reproduce this. This is a bug and will need fixing for the upcoming llvmlite v0.40.1

**Comment by esc** [comment]
For reference the relevant section in the LLVM 14 docs are:

https://releases.llvm.org/14.0.0/docs/LangRef.html#parameter-attributes

And the section in the LLVM 11 docs are:

https://releases.llvm.org/11.0.0/docs/LangRef.html#parameter-attributes

This should be a good guide as to which parameter attributes will need a type in LLVM 14.
