### ISSUE TITLE
Why does the library raise exceptions for incorrect arguments to builder.py methods

### ISSUE THREAD

**Issue by crim4** [numba/llvmlite#971]
So, I'm using llvmlite in a personal project and I found my self to modify the llvmlite source code to convert all the `raise` statements in builder.py and values.py into `report(...)` and all asserts into `expect(...)`, so that my code doesn't suffer from llvmlite exceptions and doesn't have to crash every time an unsuitable argument is passed to its methods, or simply that my code doesn't have to be full of `if is_ok: llvmlite.do()`.

This happens because I internally track multiple semantic errors, but everytime llvmlite surprises me with an exception I have to patch somehow with an if or a try-except.

The C# wrap of LLVM, manages this in another way, no exceptions are involved, semantic errors of the llvm irbuilder are accumulated in a errors list and dumped with the module only if and when you want.

Why not adopt a similar mechanism? Maybe still supporting exceptions, but with a flag to the library allowing to patch these exceptions with report messages accumulated somewhere?

**Comment by esc** [comment]
@crim4 thank you for raising this, we will try to discuss this in the developer meeting today.

**Comment by esc** [comment]
@crim4 thank you for asking about this. We discussed this in the developer meeting and we don't quite understand what your use case is. Can you share a pseudocode example of what you are trying to do?

To set some expectations: it is rather unlikely that we will change our API as this will break all our dependents. But maybe you can create an automatic `try: except:` wrapper for all methods of the builder API?

**Comment by esc** [comment]
> Thanks for considering the request. The problem doesn't exist in my specific case, but it does lead the code that makes the library calls to be full of checks to make sure that wrong values are not passed to llvmlite, crashing the program. It happens that I pass semantically wrong values to llvmlite (for example calling `builder.ret(foo)`, where `foo` is a llvmlite value of type `i32`, but the function the builder is attached to wants a `void`)

Under what circumstances can the program continue in this case? How can anything other than a crash be reasonable in this case?

**Comment by crim4** [comment]
> How can anything other than a crash be reasonable in this case?

Well, I'm semantic checking a bunch of internal bytecodes and in the mean while emitting llvmlite.

> Under what circumstances can the program continue in this case?

Semantic error recovery.

NOTE: look at how C# LLVM wrapper manages this (I still think this is more generally a LLVM thing, not a of the C# wrapper).

**Comment by esc** [comment]
> > How can anything other than a crash be reasonable in this case?
> 
> Well, I'm semantic checking a bunch of internal bytecodes and in the mean while emitting llvmlite.
> 
> > Under what circumstances can the program continue in this case?
> 
> Semantic error recovery.
> 
> NOTE: look at how C# LLVM wrapper manages this (I still think this is more generally a LLVM thing, not a of the C# wrapper).

OK, thank you for your explanation. llvmlite is used in many places and changing the API at this level isn't realistic both from a resource and impact perspective. Although it may be possible to write a generalized wrapper around llvmlite which caters to this use-case. I.e. code that augments the current code with an additional API rather than changing the API that currently exists.
