### ISSUE TITLE
readthedocs (RTD) requires new configuration file

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#982]
Ref: https://blog.readthedocs.com/migrate-configuration-v2/

TL;DR

The llvmlite project needs an RTD configuration file by sept 25 such that RTD builds don't fail.

---

**Comment by gmarkall** [comment]
Is it not needed right now? For example, #979 is now failing because it says the configuration file is missing.

**Comment by esc** [comment]
> Is it not needed right now? For example, #979 is now failing because it says the configuration file is missing.

it's a scheduled brownout.

```
Monday, August 14, 2023: Do a second brownout (temporarily enforce this deprecation) for 24 hours: 00:01 PST to 23:59 PST (midnight)
```

**Comment by esc** [comment]
Potential fix at: https://github.com/numba/llvmlite/pull/983

**Comment by esc** [comment]
Closing as #983 was merged.
