### ISSUE TITLE
unable to install numba on i686 with Python 3.10.7 Gnu 12.2

### ISSUE THREAD

**Issue by krishnak** [numba/llvmlite#992]
I am trying to install numba on a x year old dual core Intel machine. I have installed Python 3.10.7 GNU 12.2 . I get the following error

`  × Building wheel for llvmlite (pyproject.toml) did not run successfully.
╰─> [11 lines of output]
      running bdist_wheel
      /extra_space/pythonworkspace/playwright/bin/python /tmp/pip-install-uizmd_kf/llvmlite_078b8f5b0e3d4be0b6aeda903ec927ff/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-uizmd_kf/llvmlite_078b8f5b0e3d4be0b6aeda903ec927ff/ffi/build.py", line 227, in <module>
          main()
        File "/tmp/pip-install-uizmd_kf/llvmlite_078b8f5b0e3d4be0b6aeda903ec927ff/ffi/build.py", line 217, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-uizmd_kf/llvmlite_078b8f5b0e3d4be0b6aeda903ec927ff/ffi/build.py", line 135, in main_posix
          raise RuntimeError(msg) from None
      RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
      error: command '/extra_space/pythonworkspace/playwright/bin/python' failed with exit code 1
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
Failed to build llvmlite
ERROR: Could not build wheels for llvmlite, which is required to install pyproject.toml-based projects
`

Any suggestions as to how to fix this.

**Comment by esc** [comment]
> I am trying to install numba on a x year old dual core Intel machine. I have installed Python 3.10.7 GNU 12.2 . I get the following error
> 
> ` × Building wheel for llvmlite (pyproject.toml) did not run successfully. ╰─> [11 lines of output] running bdist_wheel /extra_space/pythonworkspace/playwright/bin/python /tmp/pip-install-uizmd_kf/llvmlite_078b8f5b0e3d4be0b6aeda903ec927ff/ffi/build.py LLVM version... Traceback (most recent call last): File "/tmp/pip-install-uizmd_kf/llvmlite_078b8f5b0e3d4be0b6aeda903ec927ff/ffi/build.py", line 227, in <module> main() File "/tmp/pip-install-uizmd_kf/llvmlite_078b8f5b0e3d4be0b6aeda903ec927ff/ffi/build.py", line 217, in main main_posix('linux', '.so') File "/tmp/pip-install-uizmd_kf/llvmlite_078b8f5b0e3d4be0b6aeda903ec927ff/ffi/build.py", line 135, in main_posix raise RuntimeError(msg) from None RuntimeError: Could not find a`llvm-config`binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help. error: command '/extra_space/pythonworkspace/playwright/bin/python' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for llvmlite Failed to build llvmlite ERROR: Could not build wheels for llvmlite, which is required to install pyproject.toml-based projects`
> 
> Any suggestions as to how to fix this.

@krishnak thank you for asking about this -- from what I understand `i686` is 32-bit intel? I believe that all 32 bit platforms are no longer supported.

**Comment by krishnak** [comment]
Thanks for letting me know :) I should have looked for it before proceeding, I spent 2 nights to get gcc compiled to version 12 as numpy was complaining first. Could you please modify your dependency script to check whether it is a 32 bit machine and throw an exception? It would save time for people who didn't look in to the documentation :)  I just spent 2 days to get gcc compiled as the first error said gcc version > 8 needed by numpy.

But great work, otherwise.

**Comment by krishnak** [comment]
I just checked the website, the first line states this supported platforms Linux x86 (32-bit and 64-bit)

**Comment by esc** [comment]
> I just checked the website, the first line states this supported platforms Linux x86 (32-bit and 64-bit)

I presume that is because the documentation has not been updated. Do you have a link?

**Comment by esc** [comment]
> Thanks for letting me know :) I should have looked for it before proceeding, I spent 2 nights to get gcc compiled to version 12 as numpy was complaining first. Could you please modify your dependency script to check whether it is a 32 bit machine and throw an exception? It would save time for people who didn't look in to the documentation :) I just spent 2 days to get gcc compiled as the first error said gcc version > 8 needed by numpy.

Yeah, that is a good idea! Thank you for the suggestion. If you have time please do open an issue on the tracker. A pull-request would be even more convenient, of course! 😉 

> But great work, otherwise.

🙏

**Comment by esc** [comment]
> > I just checked the website, the first line states this supported platforms Linux x86 (32-bit and 64-bit)
> 
> I presume that is because the documentation has not been updated. Do you have a link?

Are you looking at:

https://numba.pydata.org/numba-doc/latest/user/5minguide.html

Because we unfortunately have a SEO problem... The docs have been moved to readthedocs here:

https://numba.readthedocs.io/en/stable/user/5minguide.html

But Google still points our users to the "old" site... I think there is an issue on the tracker somewhere that has been around for some years, I am not sure if we didn't know what to do about it or if we didn't have time to fix this. It is clearly a problem though as evidenced by your experience.

**Comment by krishnak** [comment]
I actually checked this https://numba.pydata.org/numba-doc/latest/user/installing.html

I probably could have missed the warning on top if it appeared at that time. Sleep deprived.

Any way it is clear now that it is not supported. Thanks for replying.
